'use client';

import { useEffect, useMemo, useState } from 'react';
import { createWorld, tick, type World, RESOURCE_LABELS, type Resource } from '@/lib/simulation';

const buildingOptions = [['Farm',150,3],['Woodcutter',125,2],['Quarry',175,4],['Mine',250,6],['Mill',250,5],['Bakery',300,6],['Carpenter',275,5],['Blacksmith',400,8],['Tailor',325,6],['House',100,1]] as const;

export default function Home(){
 const [world,setWorld]=useState<World>(()=>createWorld(481516)); const [paused,setPaused]=useState(false); const [selected,setSelected]=useState<'overview'|'bank'|'market'|'build'>('overview'); const [speed,setSpeed]=useState(1);
 useEffect(()=>{if(paused)return;const id=setInterval(()=>setWorld(w=>tick(w,speed)),1000);return()=>clearInterval(id)},[paused,speed]);
 const dayTime=`Day ${world.day} · ${String(world.hour).padStart(2,'0')}:00`; const food=Math.round(world.resources.bread+world.resources.wheat+world.resources.vegetables); const employed=world.citizens.filter(c=>c.job!=='unemployed').length; const happiness=Math.round(world.citizens.reduce((s,c)=>s+c.happiness,0)/world.citizens.length); const terrain=useMemo(()=>world.terrain.join(' + '),[world.terrain]);
 function build(type:string,cost:number){if(world.treasury<cost)return;setWorld(w=>({...w,treasury:w.treasury-cost,buildings:[...w.buildings,{id:`b${Date.now()}`,type,x:40+Math.floor(Math.random()*80),y:40+Math.floor(Math.random()*80),workers:[],active:true}],lastEvents:[`${type} constructed for ${cost} Gold.`,...w.lastEvents].slice(0,8)}));}
 return <main className="shell"><header className="topbar"><div className="brand"><div className="mark">E</div><div><div className="wordmark">EMERGE</div><div className="tagline">A new world. A life of its own.</div></div></div><div className="topstats"><span>◉ WORLD {world.id.replace('world-','').toUpperCase()}</span><span>{dayTime}</span><button onClick={()=>setPaused(!paused)}>{paused?'▶ Resume':'Ⅱ Pause'}</button></div></header><section className="layout"><aside className="sidebar"><div className="owner">WORLD OWNER<div className="ownername">YOU</div><div className="terrain">{terrain}</div></div><nav>{[['overview','Overview'],['bank','Bank'],['market','Market'],['build','Build']].map(([key,label])=><button className={selected===key?'active':''} onClick={()=>setSelected(key as any)} key={key}>{label}</button>)}</nav><div className="sidebottom"><div>SIMULATION SPEED</div><div className="speed"><button onClick={()=>setSpeed(1)} className={speed===1?'sel':''}>1×</button><button onClick={()=>setSpeed(2)} className={speed===2?'sel':''}>2×</button><button onClick={()=>setSpeed(6)} className={speed===6?'sel':''}>6×</button></div><div className="online">● WORLD ONLINE</div></div></aside><section className="content"><div className="hero"><div><div className="eyebrow">YOUR WORLD</div><h1>World of {world.families[0]?.name}</h1><p>Your civilization is alive and operating autonomously.</p></div><div className="treasury"><span>TREASURY</span><strong>{Math.floor(world.treasury).toLocaleString()} <small>GOLD</small></strong></div></div>
 {selected==='overview'&&<><div className="worldview"><div className="map"><div className="maplabel">LIVE WORLD</div><div className="terrainbg">{Array.from({length:144},(_,i)=><span key={i} className={i%17===0?'tree':i%29===0?'stone':'grass'}>{i%17===0?'♣':i%29===0?'◆':''}</span>)}</div>{world.buildings.slice(0,18).map((b,i)=><div key={b.id} className="building" style={{left:`${12+(i*17)%76}%`,top:`${18+(i*23)%66}%`}} title={b.type}>{b.type==='House'?'⌂':b.type==='Farm'?'♜':b.type==='Market'?'▦':'▰'}</div>)}<div className="mapcaption">Citizens are working, eating, resting and building.</div></div><div className="panel needs"><h3>WORLD CONDITION</h3><Stat label="Population" value={`${world.population}`} sub={`${world.families.length} families`}/><Stat label="Employment" value={`${Math.round(employed/world.population*100)}%`} sub={`${employed} working`}/><Stat label="Happiness" value={`${happiness}%`} sub="citizen average"/><Stat label="Food stock" value={`${food}`} sub="units"/><Stat label="Buildings" value={`${world.buildings.length}`} sub="active infrastructure"/></div></div><div className="lower"><div className="panel"><h3>RESOURCES</h3><div className="resourcegrid">{(Object.keys(RESOURCE_LABELS) as Resource[]).map(r=><div className="resource" key={r}><span>{RESOURCE_LABELS[r]}</span><b>{Math.floor(world.resources[r])}</b></div>)}</div></div><div className="panel"><h3>WORLD LOG</h3><div className="log">{world.lastEvents.map((e,i)=><div key={i}><span>DAY {world.day}</span>{e}</div>)}</div></div></div></>}
 {selected==='bank'&&<div className="panel big"><h2>Bank</h2><p className="muted">The bank is the bridge between $TOKEN and your world's internal Gold economy.</p><div className="bankbalance">{Math.floor(world.treasury).toLocaleString()} <small>GOLD</small></div><div className="bankcards"><div><span>SIMULATED TOKEN BALANCE</span><b>1,000 $TOKEN</b></div><div><span>CONVERSION</span><b>1 $TOKEN = 1 GOLD</b></div><div><span>WITHDRAWAL FEE</span><b>1%</b></div></div><button className="primary">Deposit $TOKEN</button></div>}
 {selected==='market'&&<div className="panel big"><h2>World Market</h2><p className="muted">All resource trading happens here. AI worlds will eventually buy and sell against these orders automatically.</p><div className="marketrows">{(['wheat','wood','stone','ironOre','bread','tools','clothing'] as Resource[]).map((r,i)=><div className="marketrow" key={r}><span>{RESOURCE_LABELS[r]}</span><b>{(2+i*2).toFixed(2)} Gold</b><span className="buy">BUY ORDERS</span><span>{i*7+3}</span><button>View</button></div>)}</div></div>}
 {selected==='build'&&<div className="panel big"><h2>Build</h2><p className="muted">Invest Gold into infrastructure. Your citizens decide how to staff and operate it.</p><div className="buildgrid">{buildingOptions.map(([name,cost,maint])=><div className="buildcard" key={name}><div className="buildicon">{name[0]}</div><h3>{name}</h3><span>{cost} Gold</span><small>{maint} Gold/day maintenance</small><button onClick={()=>build(name,cost)} disabled={world.treasury<cost}>Construct</button></div>)}</div></div>}</section></section></main>
}
function Stat({label,value,sub}:{label:string,value:string,sub:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
