'use client';

import { useEffect, useMemo, useState } from 'react';
import { createWorld, tick, type World, RESOURCE_LABELS, type Resource } from '@/lib/simulation';

const buildingOptions = [['Farm',150,3],['Woodcutter',125,2],['Quarry',175,4],['Mine',250,6],['Mill',250,5],['Bakery',300,6],['Carpenter',275,5],['Blacksmith',400,8],['Tailor',325,6],['House',100,1]] as const;
const marketResources: Resource[] = ['wheat','vegetables','wood','stone','ironOre','wool','flour','bread','furniture','tools','clothing'];

export default function Home(){
 const [world,setWorld]=useState<World>(()=>createWorld(481516)); const [paused,setPaused]=useState(false); const [selected,setSelected]=useState<'overview'|'bank'|'market'|'build'>('overview'); const [speed,setSpeed]=useState(1); const [marketFocus,setMarketFocus]=useState<Resource>('wheat');
 useEffect(()=>{if(paused)return;const id=setInterval(()=>setWorld(w=>tick(w,speed)),1000);return()=>clearInterval(id)},[paused,speed]);
 const dayTime=`Day ${world.day} · ${String(Math.floor(world.hour)).padStart(2,'0')}:00`; const food=Math.round(world.resources.bread+world.resources.wheat+world.resources.vegetables); const employed=world.citizens.filter(c=>c.job!=='unemployed').length; const happiness=Math.round(world.citizens.reduce((s,c)=>s+c.happiness,0)/world.citizens.length); const terrain=useMemo(()=>world.terrain.join(' + '),[world.terrain]);
 function build(type:string,cost:number){if(world.treasury<cost)return;setWorld(w=>({...w,treasury:w.treasury-cost,buildings:[...w.buildings,{id:`b${Date.now()}`,type,x:15+Math.floor(Math.random()*70),y:18+Math.floor(Math.random()*70),workers:[],active:true}],lastEvents:[`${type} constructed for ${cost} Gold.`,...w.lastEvents].slice(0,8)}));}
 return <main className="shell"><header className="topbar"><div className="brand"><div className="mark">E</div><div><div className="wordmark">EMERGE</div><div className="tagline">A new world. A life of its own.</div></div></div><div className="topstats"><span>◉ WORLD {world.id.replace('world-','').toUpperCase()}</span><span>{dayTime}</span><button onClick={()=>setPaused(!paused)}>{paused?'▶ Resume':'Ⅱ Pause'}</button></div></header><section className="layout"><aside className="sidebar"><div className="owner">WORLD OWNER<div className="ownername">YOU</div><div className="terrain">{terrain}</div></div><nav>{[['overview','Overview'],['bank','Bank'],['market','Market'],['build','Build']].map(([key,label])=><button className={selected===key?'active':''} onClick={()=>setSelected(key as any)} key={key}>{label}</button>)}</nav><div className="sidebottom"><div>SIMULATION SPEED</div><div className="speed"><button onClick={()=>setSpeed(1)} className={speed===1?'sel':''}>1×</button><button onClick={()=>setSpeed(2)} className={speed===2?'sel':''}>2×</button><button onClick={()=>setSpeed(6)} className={speed===6?'sel':''}>6×</button></div><div className="online">● WORLD ONLINE</div></div></aside><section className="content"><div className="hero"><div><div className="eyebrow">YOUR WORLD</div><h1>World of {world.families[0]?.name}</h1><p>Your civilization is alive and operating autonomously.</p></div><div className="treasury"><span>TREASURY</span><strong>{Math.floor(world.treasury).toLocaleString()} <small>GOLD</small></strong></div></div>
 {selected==='overview'&&<><div className="worldview"><div className="map"><div className="maplabel">LIVE WORLD <i>● {paused?'PAUSED':'LIVE'}</i></div><div className="terrainbg">{Array.from({length:144},(_,i)=><span key={i} className={i%17===0?'tree':i%29===0?'stone':'grass'}>{i%17===0?'♣':i%29===0?'◆':''}</span>)}</div>{world.buildings.slice(0,18).map((b)=><div key={b.id} className="building" style={{left:`${b.x}%`,top:`${b.y}%`}} title={b.type}>{b.type==='House'?'⌂':b.type==='Farm'?'♜':b.type==='Market'?'▦':'▰'}</div>)}{world.citizens.map(c=><div key={c.id} className={`citizen ${c.job==='unemployed'?'idle':''}`} style={{left:`${c.x}%`,top:`${c.y}%`}} title={`${c.name} · ${c.job}`}><span /></div>)}<div className="maplegend"><span><b className="dot citizen-dot"/> CITIZENS</span><span><b className="dot work-dot"/> WORKING</span><span><b className="dot idle-dot"/> IDLE</span></div><div className="mapcaption">Citizens are moving between homes, jobs, the market and gathering places.</div></div><div className="panel needs"><h3>WORLD CONDITION</h3><Stat label="Population" value={`${world.population}`} sub={`${world.families.length} families`}/><Stat label="Employment" value={`${Math.round(employed/world.population*100)}%`} sub={`${employed} working`}/><Stat label="Happiness" value={`${happiness}%`} sub="citizen average"/><Stat label="Food stock" value={`${food}`} sub="units"/><Stat label="Buildings" value={`${world.buildings.length}`} sub="active infrastructure"/></div></div><div className="lower"><div className="panel"><h3>RESOURCES</h3><div className="resourcegrid">{(Object.keys(RESOURCE_LABELS) as Resource[]).map(r=><div className="resource" key={r}><span>{RESOURCE_LABELS[r]}</span><b>{Math.floor(world.resources[r])}</b></div>)}</div></div><div className="panel"><h3>WORLD LOG</h3><div className="log">{world.lastEvents.map((e,i)=><div key={i}><span>DAY {world.day}</span>{e}</div>)}</div></div></div></>}
 {selected==='bank'&&<div className="panel big"><h2>Bank</h2><p className="muted">The bank is the bridge between $TOKEN and your world's internal Gold economy.</p><div className="bankbalance">{Math.floor(world.treasury).toLocaleString()} <small>GOLD</small></div><div className="bankcards"><div><span>SIMULATED TOKEN BALANCE</span><b>1,000 $TOKEN</b></div><div><span>CONVERSION</span><b>1 $TOKEN = 1 GOLD</b></div><div><span>WITHDRAWAL FEE</span><b>1%</b></div></div><button className="primary">Deposit $TOKEN</button></div>}
 {selected==='market'&&<div className="panel big"><div className="markethead"><div><h2>World Market</h2><p className="muted">Autonomous buyers and sellers continuously rebalance the world economy.</p></div><div className="marketpulse"><span>● LIVE MARKET</span><b>{world.market[marketFocus].volume.toFixed(0)} units</b><small>last cycle volume</small></div></div><div className="marketfeatured"><div><span>FOCUS</span><h3>{RESOURCE_LABELS[marketFocus]}</h3><strong>{world.market[marketFocus].price.toFixed(2)} <small>GOLD / UNIT</small></strong></div><div><span>SUPPLY</span><b>{Math.floor(world.market[marketFocus].supply)}</b></div><div><span>DEMAND</span><b>{Math.floor(world.market[marketFocus].demand)}</b></div><div><span>TREND</span><b className={world.market[marketFocus].trend>0?'up':world.market[marketFocus].trend<0?'down':''}>{world.market[marketFocus].trend>=0?'+':''}{world.market[marketFocus].trend.toFixed(2)}</b></div></div><div className="marketrows">{marketResources.map(r=>{const q=world.market[r];return <button className={`marketrow ${marketFocus===r?'focused':''}`} key={r} onClick={()=>setMarketFocus(r)}><span>{RESOURCE_LABELS[r]}</span><b>{q.price.toFixed(2)} Gold</b><span className="orderlabel">{q.demand>q.supply?'BUY PRESSURE':'SELL PRESSURE'}</span><span>{Math.floor(q.demand+q.supply)}</span><span className={q.trend>0?'up':q.trend<0?'down':''}>{q.trend>=0?'+':''}{q.trend.toFixed(2)}</span></button>})}</div></div>}
 {selected==='build'&&<div className="panel big"><h2>Build</h2><p className="muted">Invest Gold into infrastructure. Your citizens decide how to staff and operate it.</p><div className="buildgrid">{buildingOptions.map(([name,cost,maint])=><div className="buildcard" key={name}><div className="buildicon">{name[0]}</div><h3>{name}</h3><span>{cost} Gold</span><small>{maint} Gold/day maintenance</small><button onClick={()=>build(name,cost)} disabled={world.treasury<cost}>Construct</button></div>)}</div></div>}</section></section></main>
}
function Stat({label,value,sub}:{label:string,value:string,sub:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
