'use client';

import { useEffect, useMemo, useState } from 'react';
import { createWorld, tick, type World, RESOURCE_LABELS, type Resource } from '@/lib/simulation';

const buildingOptions=[['Farm',150,3],['Woodcutter',125,2],['Quarry',175,4],['Mine',250,6],['Mill',250,5],['Bakery',300,6],['Carpenter',275,5],['Blacksmith',400,8],['Tailor',325,6],['House',100,1]] as const;
const marketResources:Resource[]=['wheat','vegetables','wood','stone','ironOre','wool','flour','bread','furniture','tools','clothing'];
const jobLabels:Record<string,string>={farmer:'Farmer',woodcutter:'Woodcutter',miner:'Miner',quarry:'Quarry worker',miller:'Miller',baker:'Baker',carpenter:'Carpenter',blacksmith:'Blacksmith',tailor:'Tailor',unemployed:'Unemployed'};

function buildingName(b:World['buildings'][number],world:World){
 if(b.type==='House'){const f=world.families.find(x=>x.homeId===b.id);return f?`${f.name} Family House`:'Family House';}
 return b.type;
}
function buildingIcon(type:string){return type==='House'?'⌂':type==='Farm'?'♜':type==='Market'?'▦':type==='Bank'?'₲':type==='Storage'?'▤':type==='Mill'?'◫':type==='Bakery'?'◈':type==='Blacksmith'?'⚒':type==='Mine'?'◆':type==='Quarry'?'◇':type==='Woodcutter'?'♣':type==='Carpenter'?'▣':type==='Tailor'?'✦':'▰';}
function buildingStatus(b:World['buildings'][number]){return b.active?(b.workers.length?`Operating · ${b.workers.length} nearby`:'Operating · no workers nearby'):'Inactive';}

export default function Home(){
 const [world,setWorld]=useState<World>(()=>createWorld(481516));
 const [paused,setPaused]=useState(false);const [selected,setSelected]=useState<'overview'|'bank'|'market'|'build'>('overview');const [speed,setSpeed]=useState(1);const [marketFocus,setMarketFocus]=useState<Resource>('wheat');
 useEffect(()=>{if(paused)return;const id=setInterval(()=>setWorld(w=>tick(w,speed)),1000);return()=>clearInterval(id)},[paused,speed]);
 const dayTime=`Day ${world.day} · ${String(Math.floor(world.hour)).padStart(2,'0')}:00`;const food=Math.round(world.resources.bread+world.resources.wheat+world.resources.vegetables);const employed=world.citizens.filter(c=>c.job!=='unemployed').length;const happiness=Math.round(world.citizens.reduce((s,c)=>s+c.happiness,0)/Math.max(1,world.citizens.length));const terrain=useMemo(()=>world.terrain.join(' + '),[world.terrain]);
 function build(type:string,cost:number){if(world.treasury<cost)return;setWorld(w=>({...w,treasury:w.treasury-cost,buildings:[...w.buildings,{id:`b${Date.now()}`,type,x:12+Math.floor(Math.random()*76),y:16+Math.floor(Math.random()*76),workers:[],active:true}],lastEvents:[`${type} constructed for ${cost} Gold.`,...w.lastEvents].slice(0,8)}));}
 const market=world.buildings.find(b=>b.type==='Market');
 return <main className="shell"><header className="topbar"><div className="brand"><div className="mark">E</div><div><div className="wordmark">EMERGE</div><div className="tagline">A new world. A life of its own.</div></div></div><div className="topstats"><span>◉ WORLD {world.id.replace('world-','').toUpperCase()}</span><span>{dayTime}</span><button onClick={()=>setPaused(!paused)}>{paused?'▶ Resume':'Ⅱ Pause'}</button></div></header>
 <section className="layout"><aside className="sidebar"><div className="owner">WORLD OWNER<div className="ownername">YOU</div><div className="terrain">{terrain}</div></div><nav>{[['overview','Overview'],['bank','Bank'],['market','Market'],['build','Build']].map(([key,label])=><button className={selected===key?'active':''} onClick={()=>setSelected(key as 'overview'|'bank'|'market'|'build')} key={key}>{label}</button>)}</nav><div className="sidebottom"><div>SIMULATION SPEED</div><div className="speed"><button onClick={()=>setSpeed(1)} className={speed===1?'sel':''}>1×</button><button onClick={()=>setSpeed(2)} className={speed===2?'sel':''}>2×</button><button onClick={()=>setSpeed(6)} className={speed===6?'sel':''}>6×</button></div><div className="online">● WORLD ONLINE</div></div></aside>
 <section className="content"><div className="hero"><div><div className="eyebrow">YOUR WORLD</div><h1>World of {world.families[0]?.name}</h1><p>Your civilization is alive and operating autonomously.</p></div><div className="treasury"><span>TREASURY</span><strong>{Math.floor(world.treasury).toLocaleString()} <small>GOLD</small></strong></div></div>
 {selected==='overview'&&<><div className="worldview"><div className="map"><div className="maplabel">LIVE WORLD <i>● {paused?'PAUSED':'LIVE'}</i></div><div className="terrainbg">{Array.from({length:144},(_,i)=><span key={i} className={i%17===0?'tree':i%29===0?'stone':'grass'}>{i%17===0?'♣':i%29===0?'◆':''}</span>)}</div>
 <svg className="roads" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Road network"><path d="M29 24 L50 24 L50 48 L20 48 L20 76"/><path d="M29 24 L66 24 L66 58 L84 74"/><path d="M29 24 L34 34 L50 34 L64 62"/><path d="M50 48 L70 84"/></svg>
 {world.buildings.slice(0,22).map(b=><div key={b.id} className={`building ${b.workers.length?'operating':''}`} style={{left:`${b.x}%`,top:`${b.y}%`}} data-tooltip={`${buildingName(b,world)}\n${buildingStatus(b)}\nWorkers: ${b.workers.length}`}><span>{buildingIcon(b.type)}</span>{b.workers.length>0&&<em>{b.workers.length}</em>}<i className="door"/></div>)}
 <div className="resource-node forest-node" data-tooltip="Forest\nWood gathering site">♣</div><div className="resource-node rock-node" data-tooltip="Mountain quarry\nStone and ore site">◆</div><div className="resource-node farm-node" data-tooltip="Fertile fields\nWheat and vegetables">✣</div>
 {market&&[0,1,2,3].map(i=><div key={`stall${i}`} className="market-stall" style={{left:`${market.x+(i%2)*5-5}%`,top:`${market.y+Math.floor(i/2)*5+4}%`}}>▦</div>)}
 {marketResources.map((r,i)=>{const q=world.market[r];return q.volume>0?<span key={`trade${r}`} className="trade-particle" style={{left:`${(market?.x??50)+(i%3)*2-2}%`,top:`${(market?.y??50)+(i%2)*2}%`}}>✦</span>:null})}
 {world.citizens.map(c=>{const family=world.families.find(f=>f.id===c.familyId);return <div key={c.id} className={`citizen ${c.activity} ${c.job==='unemployed'?'idle':''}`} style={{left:`${c.x}%`,top:`${c.y}%`}} data-tooltip={`${c.name}\n${jobLabels[c.job]} · ${c.activity}\n${family?.name??'Unknown'} family · age ${c.age}\nHappiness ${Math.round(c.happiness)}%`}><span /></div>})}
 <div className="maplegend"><span><b className="dot citizen-dot"/> CITIZENS</span><span><b className="dot work-dot"/> WORKING</span><span><b className="dot idle-dot"/> IDLE</span><span><b className="dot market-dot"/> MARKET</span></div><div className="mapcaption">Roads connect homes to jobs. Citizens gather, work, trade and return home on their own.</div></div>
 <div className="panel needs"><h3>WORLD CONDITION</h3><Stat label="Population" value={`${world.population}`} sub={`${world.families.length} families`}/><Stat label="Employment" value={`${Math.round(employed/Math.max(1,world.population)*100)}%`} sub={`${employed} working`}/><Stat label="Happiness" value={`${happiness}%`} sub="citizen average"/><Stat label="Food stock" value={`${food}`} sub="units"/><Stat label="Buildings" value={`${world.buildings.length}`} sub="active infrastructure"/></div></div>
 <div className="lower"><div className="panel"><h3>RESOURCES</h3><div className="resourcegrid">{(Object.keys(RESOURCE_LABELS) as Resource[]).map(r=><div className="resource" key={r}><span>{RESOURCE_LABELS[r]}</span><b>{Math.floor(world.resources[r])}</b></div>)}</div></div><div className="panel"><h3>WORLD LOG</h3><div className="log">{world.lastEvents.map((e,i)=><div key={i}><span>DAY {world.day}</span>{e}</div>)}</div></div></div></>}
 {selected==='bank'&&<div className="panel big"><h2>Bank</h2><p className="muted">The bank is the bridge between $TOKEN and your world's internal Gold economy.</p><div className="bankbalance">{Math.floor(world.treasury).toLocaleString()} <small>GOLD</small></div><div className="bankcards"><div><span>SIMULATED TOKEN BALANCE</span><b>1,000 $TOKEN</b></div><div><span>CONVERSION</span><b>1 $TOKEN = 1 GOLD</b></div><div><span>WITHDRAWAL FEE</span><b>1%</b></div></div><button className="primary">Deposit $TOKEN</button></div>}
 {selected==='market'&&<div className="panel big"><div className="markethead"><div><h2>World Market</h2><p className="muted">Autonomous buyers and sellers continuously rebalance the world economy.</p></div><div className="marketpulse"><span>● LIVE MARKET</span><b>{world.market[marketFocus].volume.toFixed(0)} units</b><small>last cycle volume</small></div></div><div className="marketfeatured"><div><span>FOCUS</span><h3>{RESOURCE_LABELS[marketFocus]}</h3><strong>{world.market[marketFocus].price.toFixed(2)} <small>GOLD / UNIT</small></strong></div><div><span>SUPPLY</span><b>{Math.floor(world.market[marketFocus].supply)}</b></div><div><span>DEMAND</span><b>{Math.floor(world.market[marketFocus].demand)}</b></div><div><span>TREND</span><b className={world.market[marketFocus].trend>0?'up':world.market[marketFocus].trend<0?'down':''}>{world.market[marketFocus].trend>=0?'+':''}{world.market[marketFocus].trend.toFixed(2)}</b></div></div><div className="marketrows">{marketResources.map(r=>{const q=world.market[r];return <button className={`marketrow ${marketFocus===r?'focused':''}`} key={r} onClick={()=>setMarketFocus(r)}><span>{RESOURCE_LABELS[r]}</span><b>{q.price.toFixed(2)} Gold</b><span className="orderlabel">{q.demand>q.supply?'BUY PRESSURE':'SELL PRESSURE'}</span><span>{Math.floor(q.demand+q.supply)}</span><span className={q.trend>0?'up':q.trend<0?'down':''}>{q.trend>=0?'+':''}{q.trend.toFixed(2)}</span></button>})}</div></div>}
 {selected==='build'&&<div className="panel big"><h2>Build</h2><p className="muted">Invest Gold into infrastructure. Your citizens decide how to staff and operate it.</p><div className="buildgrid">{buildingOptions.map(([name,cost,maint])=><div className="buildcard" key={name}><div className="buildicon">{name[0]}</div><h3>{name}</h3><span>{cost} Gold</span><small>{maint} Gold/day maintenance</small><button onClick={()=>build(name,cost)} disabled={world.treasury<cost}>Construct</button></div>)}</div></div>}</section></section></main>
}
function Stat({label,value,sub}:{label:string,value:string,sub:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
