'use client';

/**
 * The land office.
 *
 * A map of the whole region, with every plot on it in its place. The land is
 * painted from the plots themselves — each one's territory takes the colour of
 * its biome — so the desert really is out west and the fen really is down by
 * the southern water, and choosing where to settle is a decision about a place
 * rather than a scroll through a list of cards.
 *
 * Selecting a plot brings up its real terrain, generated by the same code that
 * will run the world once it is claimed, so the ground shown is the ground you
 * get.
 *
 * Claims and listings are honest about where they stand: with no registry
 * contract deployed they are recorded in this browser, and the panel says so
 * rather than showing a transaction that bought nothing.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { defaultWorldName } from '@/lib/simulation';
import {
  drawPlotPreview, drawRegionMap, loadPlayer, marketPlots, prospectPlot, savePlayer,
  type ClaimedWorld, type PlayerRecord, type Plot,
} from '@/lib/world/plots';
import { ACTIVE_CHAIN, TOKEN, chainConfigured, claimPlot } from '@/lib/chain/emerge';
import { LOCAL_TEST_ALLOCATION, PROSPECT_COST_EMERGE } from '@/lib/chain/vault';
import { WalletPicker, useWallet } from './WalletPicker';

function PlotPreview({ seed }: { seed: number }) {
  const ref = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    // Generation takes a few tens of milliseconds; yielding a frame first keeps
    // the panel from appearing after a visible stall when the selection changes.
    const id = requestAnimationFrame(() => drawPlotPreview(canvas, seed));
    return () => cancelAnimationFrame(id);
  }, [seed]);
  return <canvas ref={ref} width={320} height={180} className="plot-canvas" />;
}

/**
 * The region.
 *
 * The canvas is painted once per set of plots and never re-rendered by React;
 * the markers are real buttons laid over it, so they can be tabbed to, focused
 * and read by a screen reader instead of being pixels with a hit test.
 */
function RegionMap({ plots, selected, onSelect }: {
  plots: Plot[];
  selected: Plot;
  onSelect: (plot: Plot) => void;
}) {
  const ref = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => {
    if (ref.current) drawRegionMap(ref.current, plots);
  }, [plots]);

  return (
    <div className="region">
      <canvas ref={ref} width={900} height={570} className="region-canvas" aria-hidden />
      <div className="region-pins">
        {plots.map((plot) => (
          <button
            key={plot.id}
            className={`region-pin ${plot.biome} ${plot.seed === selected.seed ? 'selected' : ''}`}
            style={{ left: `${plot.mapX * 100}%`, top: `${plot.mapY * 100}%` }}
            onClick={() => onSelect(plot)}
            aria-pressed={plot.seed === selected.seed}
          >
            <span className="pin-dot" aria-hidden />
            <span className="pin-label">
              <b>{plot.region}</b>
              <em>{plot.biomeLabel}</em>
            </span>
          </button>
        ))}
      </div>
      <div className="region-legend">
        <span>{plots.length} plots surveyed</span>
        <span>Tap a marker to inspect the land</span>
      </div>
    </div>
  );
}

export default function PlotSelect({ onEnter }: { onEnter: (world: ClaimedWorld) => void }) {
  const [player, setPlayer] = useState<PlayerRecord | null>(null);
  const [selectedSeed, setSelectedSeed] = useState<number | null>(null);
  const [name, setName] = useState('');
  const { wallet } = useWallet();
  const [claiming, setClaiming] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  // On a phone the map and the claim panel cannot both be on screen, so the
  // panel becomes a sheet that the map opens.
  const [sheetOpen, setSheetOpen] = useState(false);
  const configured = chainConfigured();

  useEffect(() => { setPlayer(loadPlayer()); }, []);

  const plots = useMemo(() => (player ? marketPlots(player) : []), [player]);
  const selected: Plot | null = plots.find((p) => p.seed === selectedSeed) ?? plots[0] ?? null;

  const choose = useCallback((plot: Plot) => {
    setSelectedSeed(plot.seed);
    setSheetOpen(true);
  }, []);

  const prospect = useCallback(() => {
    if (!player) return;
    if (player.ledger.balance < PROSPECT_COST_EMERGE) {
      setNotice(`Prospecting costs ${PROSPECT_COST_EMERGE.toLocaleString()} ${TOKEN.ticker}.`);
      return;
    }
    const found = prospectPlot(player.prospected.length);
    const next: PlayerRecord = {
      ...player,
      ledger: { ...player.ledger, balance: player.ledger.balance - PROSPECT_COST_EMERGE },
      prospected: [...player.prospected, found.seed],
    };
    savePlayer(next);
    setPlayer(next);
    setSelectedSeed(found.seed);
    setSheetOpen(true);
    setNotice(`Surveyed ${found.region} — ${found.biomeLabel.toLowerCase()}.`);
  }, [player]);

  const claim = useCallback(async () => {
    if (!selected) return;
    setClaiming(true);
    setNotice(null);
    const worldName = name.trim() || defaultWorldName(selected.seed);
    const result = await claimPlot({
      seed: selected.seed,
      region: selected.region,
      worldName,
      price: selected.price,
      address: wallet.address,
    });
    setClaiming(false);
    if (result.reason) setNotice(result.reason);
    onEnter({
      seed: selected.seed,
      name: worldName,
      region: selected.region,
      price: selected.price,
      claimedAt: Date.now(),
      owner: wallet.address,
      txHash: result.txHash,
    });
  }, [name, selected, wallet.address, onEnter]);

  const unlist = useCallback((seed: number) => {
    if (!player) return;
    const next = { ...player, listings: player.listings.filter((l) => l.seed !== seed) };
    savePlayer(next);
    setPlayer(next);
  }, [player]);

  if (!player || !selected) return <main className="land-office" />;

  return (
    <main className="land-office">
      <div className="land-inner">
        <header className="land-head">
          <div className="brand-line">
            <div className="brand-mark">✦</div>
            <div>
              <div className="wordmark">EMERGE</div>
              <div className="tagline">THE AI WORLD</div>
            </div>
          </div>
          <p className="land-intro">
            Every plot is a world waiting to happen, and no two are the same land. Claim one with
            {' '}{TOKEN.ticker}, give it a name, and the beings who live there will call it that.
          </p>
          <div className="land-head-side">
            <div className="land-balance">
              <span>YOUR BALANCE</span>
              <b>{Math.floor(player.ledger.balance).toLocaleString()}</b>
              <em>{TOKEN.ticker}</em>
            </div>
            <button
              className="ghost prospect"
              onClick={prospect}
              disabled={player.ledger.balance < PROSPECT_COST_EMERGE}
            >
              Prospect new land · {PROSPECT_COST_EMERGE.toLocaleString()} {TOKEN.ticker}
            </button>
          </div>
        </header>

        <div className="land-body">
          <RegionMap plots={plots} selected={selected} onSelect={choose} />

          <aside className={`land-claim ${sheetOpen ? 'open' : ''}`}>
            <button className="sheet-close" onClick={() => setSheetOpen(false)} aria-label="Back to the map">×</button>
            <span className="eyebrow">CLAIM</span>
            <h2>{selected.region}</h2>
            <div className="plot-traits">
              <span className={`biome-tag ${selected.biome}`}>{selected.biomeLabel}</span>
              <span>{selected.population} beings</span>
            </div>

            <PlotPreview seed={selected.seed} />
            <p className="muted">{selected.blurb}</p>

            <span className="eyebrow">TRADES THIS LAND SUPPORTS</span>
            <div className="plot-traits">
              {selected.trades.map((t) => <span key={t}>{t}</span>)}
            </div>

            <label className="name-field">
              <span>NAME YOUR WORLD</span>
              <input
                value={name}
                maxLength={24}
                placeholder={defaultWorldName(selected.seed)}
                onChange={(e) => setName(e.target.value)}
              />
            </label>

            <div className="claim-price">
              <span>PRICE</span>
              <b>{selected.price}</b>
              <em>{TOKEN.ticker}</em>
            </div>

            <div className="claim-wallet"><WalletPicker compact /></div>

            <button className="claim-button" onClick={claim} disabled={claiming}>
              {claiming ? 'Claiming…' : `Claim ${selected.region}`}
            </button>

            {player.listings.length > 0 && (
              <>
                <span className="eyebrow">YOUR LISTINGS</span>
                <div className="listing-list">
                  {player.listings.map((listing) => (
                    <div key={listing.seed} className="listing-row">
                      <span>{listing.region}</span>
                      <b>{listing.price.toLocaleString()} {TOKEN.ticker}</b>
                      <button className="ghost" onClick={() => unlist(listing.seed)}>Withdraw</button>
                    </div>
                  ))}
                </div>
                <p className="muted small">
                  Resale between players needs the plot registry on {ACTIVE_CHAIN.label}. Until it is
                  deployed a listing is recorded in this browser and no one else can see it.
                </p>
              </>
            )}

            {!configured && (
              <p className="muted small">
                {ACTIVE_CHAIN.label} is not configured in this build, so claims are recorded in this
                browser rather than on chain, and you start with a local development allocation of
                {' '}{LOCAL_TEST_ALLOCATION.toLocaleString()} {TOKEN.ticker}. Neither is a token transfer.
              </p>
            )}
            {notice && <p className="warn">{notice}</p>}
          </aside>
        </div>
      </div>
    </main>
  );
}
