'use client';

/**
 * The world map.
 *
 * A map of the whole region, with every plot on it in its place. The land is
 * painted from the plots themselves — each one's territory takes the colour of
 * its biome — so the desert really is out west and the fen really is down by
 * the southern water, and choosing where to settle is a decision about a place
 * rather than a scroll through a list of cards.
 *
 * Selecting a plot brings up its real terrain, generated by the same code that
 * will run the world once it is claimed, so the ground shown is the ground you
 * get.
 *
 * Claims are shared. The relay holds one row per plot, so land another player
 * took is marked here as theirs and cannot be claimed a second time — and their
 * settlement can be visited from the marker. That registry is the server's
 * word, not this browser's; when the contract is deployed it becomes the
 * chain's, and nothing above this line changes.
 */

import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { defaultWorldName } from '@/lib/simulation';
import {
  CHART_COUNT, HOME_CHART_INDEX, chartCapacity, chartName, chartRoom, claimOf, drawPlotPreview,
  drawRegionMap, inspectPlot, islandsFor, marketPlots, withoutClaim,
  type ClaimedWorld, type PlayerRecord, type Plot,
} from '@/lib/world/plots';
import { worldCapacity } from '@/lib/world/charts';
import {
  ACTIVE_CHAIN, TOKEN, claimPlot, plotOwner, registryLive, shortAddress, tokenLive,
  type PlotOwnership,
} from '@/lib/chain/emerge';
import {
  allOnChainPlots, claimOnChain, onChainClaimsLive, plotExplorerUrl, registryPrice,
} from '@/lib/chain/registry';
import { EARNING_PLOT_LIMIT, LOCAL_TEST_ALLOCATION, PROSPECT_COST_EMERGE, HAND_DAILY_CEILING, HAND_MIN_EMERGE, HAND_SHARE } from '@/lib/chain/vault';
import { pay, settleBurn, spend } from '@/lib/chain/spend';
import {
  buyPlot, fetchClaims, placeOffer, priceFor, reservePlot, surveyPlot, takePlot, withdrawOffer,
  type Claim, type Find, quitJob, takeJob,
} from '@/lib/net/registry';
import { WalletPicker, useWallet } from './WalletPicker';
import { music } from '@/lib/audio/music';
import { BrandLine } from './Brand';
import { LanguageSwitch } from './LanguageSwitch';
import { t, tn, tx, useLocale } from '@/lib/i18n';

/**
 * Ask the chain who owns a plot.
 *
 * Only answers once the registry contract exists. The shared relay below is
 * what actually keeps two players off the same land today; this is here so
 * that the moment the contract is deployed the chain's answer is the one shown.
 */
function useChainOwner(seed: number | null) {
  const [state, setState] = useState<PlotOwnership | null>(null);
  useEffect(() => {
    if (seed === null || !registryLive()) { setState(null); return; }
    let live = true;
    setState(null);
    plotOwner(seed).then((result) => { if (live) setState(result); });
    return () => { live = false; };
  }, [seed]);
  return state;
}

/**
 * What the contract will charge for a plot.
 *
 * The price on the button has to be the price the transaction enforces, or the
 * first time the contract's pricing is adjusted the claim reverts with nothing
 * on screen to explain why. Falls back to the game's own price when there is no
 * registry to ask, which is the same number the contract is configured to
 * produce.
 */
function useChainPrice(seed: number | null, fallback: number) {
  const [price, setPrice] = useState(fallback);
  useEffect(() => {
    setPrice(fallback);
    if (seed === null || !onChainClaimsLive()) return;
    let live = true;
    registryPrice(seed).then((quoted) => {
      if (live && quoted !== null && quoted > 0) setPrice(quoted);
    });
    return () => { live = false; };
  }, [seed, fallback]);
  return price;
}

/**
 * Keep submitting a paid request while the chain settles.
 *
 * The server checks a payment a few blocks deep, and the first ask almost
 * always lands before the node has it. `settling` is the server saying "real,
 * but not yet" — which is worth waiting through rather than reporting as a
 * refusal, because the player has already burned the tokens.
 */
async function whileSettling<T extends { ok: boolean; settling?: boolean }>(
  attempt: () => Promise<T>,
  tries = 10,
  gapMs = 2_500,
): Promise<T> {
  let last = await attempt();
  for (let i = 1; i < tries && !last.ok && last.settling; i++) {
    await new Promise((resolve) => setTimeout(resolve, gapMs));
    last = await attempt();
  }
  return last;
}

/** How often the map re-reads who owns what, in milliseconds. */
const CLAIMS_POLL = 12_000;

/**
 * Every claim anybody holds, kept fresh.
 *
 * Polled rather than pushed: land changes hands a few times an hour at most,
 * and a poll survives a serverless deployment where a socket does not.
 */
function useAllClaims() {
  const [claims, setClaims] = useState<Claim[]>([]);
  const [finds, setFinds] = useState<Find[]>([]);
  const [shared, setShared] = useState(true);
  useEffect(() => {
    let live = true;
    const tick = async () => {
      const result = await fetchClaims();
      if (!live) return;
      setFinds(result.finds);
      setShared(result.shared && !result.offline);

      /*
       * The chain outranks the relay.
       *
       * The relay is a cache that makes the map quick and gives a claim a name
       * and a date; the contract is the title. Where they disagree about who
       * holds a plot the chain wins, because it is the thing that is actually
       * enforced — but a relay row the chain has never heard of is kept rather
       * than dropped. Dropping it would put land somebody holds back on the
       * market, and no reading of the two records is worth that.
       */
      const chain = await allOnChainPlots();
      if (!live) return;
      if (!chain) { setClaims(result.claims); return; }

      const bySeed = new Map(result.claims.map((c) => [c.seed, c]));
      for (const plot of chain) {
        const cached = bySeed.get(plot.seed);
        bySeed.set(plot.seed, {
          seed: plot.seed,
          region: cached?.region ?? t('Plot {seed}', { seed: plot.seed }),
          worldName: plot.worldName || cached?.worldName || 'Emerge',
          owner: plot.owner,
          ownerName: cached?.ownerName ?? '',
          price: cached?.price ?? 0,
          at: cached?.at ?? 0,
        });
      }
      setClaims([...bySeed.values()]);
    };
    tick();
    const timer = window.setInterval(tick, CLAIMS_POLL);
    return () => { live = false; window.clearInterval(timer); };
  }, []);
  return { claims, finds, shared, setClaims, setFinds };
}

function PlotPreview({ seed }: { seed: number }) {
  const ref = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    // Generation takes a few tens of milliseconds; yielding a frame first keeps
    // the panel from appearing after a visible stall when the selection changes.
    const id = requestAnimationFrame(() => drawPlotPreview(canvas, seed));
    return () => cancelAnimationFrame(id);
  }, [seed]);
  return <canvas ref={ref} width={320} height={180} className="plot-canvas" />;
}

/**
 * The region.
 *
 * The canvas is painted once per set of plots and never re-rendered by React;
 * the markers are real buttons laid over it, so they can be tabbed to, focused
 * and read by a screen reader instead of being pixels with a hit test.
 */
/** How much clear air two markers keep between them, in pixels. */
const MARKER_GAP = 5;

/** How far a marker may be moved off its plot to make room, as a share of the map's height. */
const MAX_MARKER_NUDGE = 0.09;

/** Below this map width, in pixels, there is no room to lay names out at all. */
const LABELS_NEED_WIDTH = 560;

function RegionMap({ plots, selected, chart, owned, taken, claimedEverywhere, onSelect }: {
  plots: Plot[];
  selected: Plot | null;
  chart: number;
  /** How much land has been claimed across every chart in the game. */
  claimedEverywhere: number;
  /** Seeds this player holds, so their own land is marked on the map. */
  owned: Set<number>;
  /** Seeds somebody else holds, by seed, so their land is marked as theirs. */
  taken: Map<number, Claim>;
  onSelect: (plot: Plot) => void;
}) {
  const ref = useRef<HTMLCanvasElement | null>(null);
  const pinsRef = useRef<HTMLDivElement | null>(null);
  /*
   * On a narrow map, markers are dots.
   *
   * Not a preference — arithmetic. A marker carrying a name is about 140px
   * wide and 24px tall; a phone's map is 390px across and 247px down. Seventeen
   * of them need more height stacked in a single column than the map has, so
   * there is no arrangement in which every name is readable, and pushing them
   * around only decides which ones get buried. Below the width where labels can
   * be laid out, the map shows the land and the dots, keeps the name on the one
   * being looked at and on the player's own, and the card underneath says
   * everything else the moment a dot is tapped.
   */
  const [compact, setCompact] = useState(false);
  useLocale();
  useEffect(() => {
    if (ref.current) drawRegionMap(ref.current, plots, chart);
  }, [plots, chart]);

  /*
   * Unpick the markers that landed on top of each other.
   *
   * The plots are placed on a spiral out from each island's middle, which
   * spreads the *points* well enough — but a marker is not a point. It is a dot
   * with a name beside it, a sixth of the map wide, and on a chart carrying its
   * full seventeen plots two of them regularly came to rest with one label
   * sitting over another: the settlement underneath could be neither read nor
   * tapped.
   *
   * No amount of tuning the spiral fixes that, because the width of a marker
   * depends on the length of a name nobody chose in advance. So the labels are
   * measured as the browser actually laid them out, and any pair that overlaps
   * is pushed apart vertically until it does not. Vertically because that is
   * how a map separates labels — and because a marker's whole job is to sit on
   * its island, so the movement is capped well inside one.
   */
  useLayoutEffect(() => {
    const container = pinsRef.current;
    if (!container) return;
    let frame = 0;

    const settle = () => {
      // Enough room for two labels side by side, or there is no point drawing
      // any of them.
      const wide = container.getBoundingClientRect().width >= LABELS_NEED_WIDTH;
      setCompact((was) => (was === !wide ? was : !wide));

      const nodes = Array.from(container.querySelectorAll<HTMLElement>('.region-pin'));
      if (!nodes.length) return;

      // Measure where they *want* to be, not where the last pass put them —
      // and with the transition off while doing it. A marker's transform is
      // animated for the hover, so resetting the offset and measuring straight
      // away measured it a third of the way through a 150ms slide: the
      // separation was computed from positions nothing was ever at, and pairs
      // that were flat on top of each other were left there.
      container.classList.add('settling');
      for (const node of nodes) {
        node.style.setProperty('--nudge', '0px');
        node.style.setProperty('--slide', '0px');
      }
      const box = container.getBoundingClientRect();
      if (!box.height) { container.classList.remove('settling'); return; }

      const measure = (node: HTMLElement, fixed: boolean) => {
        const r = node.getBoundingClientRect();
        return {
          node,
          fixed,
          left: r.left - box.left,
          right: r.right - box.left,
          mid: r.top - box.top + r.height / 2,
          height: r.height,
          dy: 0,
        };
      };

      // The island names are part of the picture and do not move. A marker
      // pushed onto one is no more readable than a marker pushed onto another
      // marker, so they take part in the separation as things to keep clear of.
      const labels = Array.from(container.querySelectorAll<HTMLElement>('.island-name'));
      for (const node of labels) node.style.setProperty('--shift', '0px');

      const items = [
        ...nodes.map((node) => measure(node, false)),
        ...labels.map((node) => measure(node, true)),
      ];

      /*
       * Sideways first, and only as far as the edge demands.
       *
       * A marker is centred on its plot, so half a long name hangs either side
       * of it — and a plot near the coast of an eastern island had that half
       * hanging over the edge of the map, where it is clipped. Flipping the
       * label to the inside, which the marker already does, moves the text
       * but not the box.
       *
       * Done before the vertical pass rather than after, so the separation
       * below is worked out from where the labels finally are. Sliding them
       * afterwards would have been solving the puzzle and then moving the
       * pieces.
       */
      for (const item of items) {
        const over = item.right > box.width - 2 ? item.right - (box.width - 2)
          : item.left < 2 ? item.left - 2 : 0;
        if (!over) continue;
        item.node.style.setProperty(item.fixed ? '--shift' : '--slide', `${(-over).toFixed(2)}px`);
        item.left -= over;
        item.right -= over;
      }

      // How far a marker may be moved, as a share of the map rather than a
      // fixed number of pixels: thirty pixels is a nudge on a desktop map and
      // half an island on a phone.
      const room = Math.max(16, Math.min(64, box.height * MAX_MARKER_NUDGE));

      /*
       * Keep a marker on its land and inside the map.
       *
       * Applied on every pass, not only at the end. Clamping once at the end
       * meant a marker pushed down into the bottom edge simply stayed on top of
       * whatever it had been pushed away from — the solver never learned it had
       * nowhere to go, so the thing it was avoiding never gave way instead.
       */
      const hold = (item: { mid: number; height: number; dy: number }) => {
        const capped = Math.max(-room, Math.min(room, item.dy));
        const top = item.mid + capped - item.height / 2;
        const bottom = top + item.height;
        return top < 2 ? capped + (2 - top)
          : bottom > box.height - 2 ? capped - (bottom - (box.height - 2))
            : capped;
      };

      /*
       * How much clear air a pair needs.
       *
       * Less on a narrow map, where the markers are dots: two dots a hair apart
       * still read as two places, where two labels a hair apart read as one
       * unreadable smear. Giving the solver that slack is what lets it satisfy
       * everything on a map with seventeen plots and no room.
       */
      const gapNeeded = (againstFixed: boolean) =>
        (compact ? MARKER_GAP - 2 : MARKER_GAP) - (againstFixed ? 2 : 0);

      // Relaxation rather than a single sweep: separating one pair can push a
      // marker into a third, and a settlement is entitled to be legible even on
      // a crowded island.
      for (let pass = 0; pass < 40; pass += 1) {
        let moved = false;
        for (let i = 0; i < items.length; i += 1) {
          for (let j = i + 1; j < items.length; j += 1) {
            const a = items[i];
            const b = items[j];
            // Labels side by side are not in each other's way.
            if (a.right <= b.left || b.right <= a.left) continue;
            const clear = (a.height + b.height) / 2 + gapNeeded(a.fixed || b.fixed);
            const between = (a.mid + a.dy) - (b.mid + b.dy);
            if (Math.abs(between) >= clear) continue;
            if (a.fixed && b.fixed) continue;

            if (a.fixed || b.fixed) {
              /*
               * One of them is an island's name, which is not going anywhere.
               *
               * The marker is placed clear of it outright rather than shoved
               * a little at a time, and — this is the part that matters — it is
               * placed on whichever side it can actually reach. Always pushing
               * it the "natural" way put markers under the southern islands
               * into the bottom edge of the map, where they were held, still
               * sitting on the name they were meant to be avoiding.
               */
              const mover = a.fixed ? b : a;
              const wall = a.fixed ? a : b;
              const above = hold({ ...mover, dy: wall.mid - clear - mover.mid });
              const below = hold({ ...mover, dy: wall.mid + clear - mover.mid });
              const clearance = (dy: number) => Math.abs(mover.mid + dy - wall.mid);
              mover.dy = clearance(above) >= clearance(below) ? above : below;
              moved = true;
              continue;
            }

            const aFirst = between <= 0;
            const push = (clear - Math.abs(between)) / 2;
            a.dy += aFirst ? -push : push;
            b.dy += aFirst ? push : -push;
            moved = true;
          }
        }
        for (const item of items) {
          if (!item.fixed) item.dy = hold(item);
        }
        if (!moved) break;
      }

      for (const item of items) {
        if (item.fixed) continue;
        item.node.style.setProperty('--nudge', `${item.dy.toFixed(2)}px`);
      }
      container.classList.remove('settling');
    };

    // After a frame, so the measurement is of the laid-out page rather than of
    // markers the browser has not sized yet.
    frame = requestAnimationFrame(settle);
    // The map is fluid, and a label that clears its neighbour at one width sits
    // on top of it at another.
    const observer = new ResizeObserver(() => {
      cancelAnimationFrame(frame);
      frame = requestAnimationFrame(settle);
    });
    observer.observe(container);
    return () => {
      cancelAnimationFrame(frame);
      observer.disconnect();
    };
  }, [plots, chart, selected, owned, taken, compact]);

  /**
   * What each island holds, gathered from the plots standing on it.
   *
   * Read from the plots rather than from the island, because an island has no
   * character of its own — its plots do. Two on the same rock can be a fen and
   * a highland, and the trades they support are the union of the two.
   */
  const islandFacts = useMemo(() => islandsFor(chart).map((island) => {
    const here = plots.filter((p) => p.island === island.name);
    return {
      name: island.name,
      capacity: island.capacity,
      plots: here,
      biomes: [...new Set(here.map((p) => p.biomeLabel))],
      trades: [...new Set(here.flatMap((p) => p.trades))].sort(),
      free: here.filter((p) => !owned.has(p.seed) && !taken.has(p.seed)).length,
    };
  }), [plots, chart, owned, taken]);

  return (
    <div className="region">
      {/* The markers are laid over the map and nothing else. They used to be
          laid over the whole box, legend included, so a plot on a southern
          island was drawn on top of the line that says how many plots there
          are — which is what made it look cut off. */}
      <div className="region-plate">
      <canvas ref={ref} width={900} height={570} className="region-canvas" aria-hidden />
      <div className={`region-pins ${compact ? 'compact' : ''}`} ref={pinsRef}>
        {/* Every island is named, surveyed or not: an empty coast the player
            can see is what makes prospecting somewhere to go. */}
        {islandsFor(chart).map((island) => (
          <span
            key={island.name}
            className="island-name"
            // Below the island, where the markers are not.
            style={{ left: `${island.x * 100}%`, top: `${(island.y + island.ry * 0.92) * 100}%` }}
          >
            {island.name}
          </span>
        ))}
        {plots.map((plot) => {
          const mine = owned.has(plot.seed);
          const theirs = !mine ? taken.get(plot.seed) : undefined;
          return (
          <button
            key={plot.id}
            // A marker on the right-hand side of the map hangs its label to the
            // left, or it runs off the edge.
            className={`region-pin ${plot.biome} ${plot.mapX > 0.66 ? 'flip' : ''} ${plot.seed === selected?.seed ? 'selected' : ''} ${mine ? 'owned' : ''} ${theirs ? 'settled' : ''}`}
            style={{ left: `${plot.mapX * 100}%`, top: `${plot.mapY * 100}%` }}
            onClick={() => onSelect(plot)}
            aria-pressed={plot.seed === selected?.seed}
          >
            <span className="pin-dot" aria-hidden />
            <span className="pin-label">
              <b>
                {plot.region}
                {mine && <i className="yours">{t('yours')}</i>}
                {theirs && !theirs.forSale && !(theirs.hiring && !theirs.hand) && <i className="settled-tag">{t('settled')}</i>}
                {theirs && !!theirs.forSale && <i className="sale-tag">{t('for sale')}</i>}
                {theirs && !theirs.forSale && theirs.hiring && !theirs.hand && <i className="hiring-tag">{t('hiring')}</i>}
              </b>
              {/* The biome only on the one being looked at. Nine markers each
                  carrying two lines of text is more label than map. */}
              {plot.seed === selected?.seed && <em>{tn(plot.biomeLabel)}</em>}
            </span>
          </button>
          );
        })}
      </div>
      </div>
      <div className="region-legend">
        <span>
          {t('{plots} plots surveyed on {islands} islands', { plots: plots.length, islands: islandsFor(chart).length })}
          {/* Across every chart, not just this one: the interesting number is
              how much of the world is spoken for, and a per-chart figure reads
              as "this island chain is empty" when the game is busy. */}
          {claimedEverywhere > 0 && (
            <> · <b>{claimedEverywhere.toLocaleString()}</b> {t('claimed in all')}</>
          )}
        </span>
        <span>{plots.length ? t('Tap a marker to inspect the land') : t('Nothing here has been surveyed yet')}</span>
      </div>

      {/*
        What each island is made of.
        *
        * The markers say where the land is and the card on the right says what
        * one plot is like, but neither answers the question somebody choosing
        * land actually has: what is this island *for*? Two plots on the same
        * rock can be a fen and a highland, and which trades they support is the
        * real reason to prefer one island over another.
        */}
      {islandFacts.some((f) => f.plots.length > 0) && (
        <div className="island-facts">
          {islandFacts.map((fact) => (
            <div key={fact.name} className={`island-fact ${fact.plots.length ? '' : 'empty'}`}>
              <b>{fact.name}</b>
              {fact.plots.length === 0 ? (
                <span className="muted">{t('Unsurveyed — {n} berths', { n: fact.capacity })}</span>
              ) : (
                <>
                  <span className="island-land">{fact.biomes.map(tn).join(' · ')}</span>
                  <span className="island-trades">
                    {fact.trades.length ? fact.trades.map(tn).join(', ') : t('Nothing the land favours')}
                  </span>
                  <em>
                    {fact.free
                      ? t('{free} of {all} free', { free: fact.free, all: fact.plots.length })
                      : t('all {all} taken', { all: fact.plots.length })}
                  </em>
                </>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default function PlotSelect({ player, onPlayer, onEnter, onVisit, onHome, onDisconnect }: {
  player: PlayerRecord;
  onPlayer: (record: PlayerRecord) => void;
  onEnter: (world: ClaimedWorld) => void;
  /** Go and look at somebody else's settlement. Resolves to a refusal, or null. */
  onVisit: (seed: number) => Promise<string | null>;
  /** Back to the front page. */
  onHome: () => void;
  /** Let go of the wallet, staying on the map as a spectator. */
  onDisconnect: () => void;
}) {
  const [chart, setChart] = useState(HOME_CHART_INDEX);
  const [selectedSeed, setSelectedSeed] = useState<number | null>(null);
  const [name, setName] = useState('');
  const { wallet } = useWallet();
  const [claiming, setClaiming] = useState(false);
  const [surveying, setSurveying] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  // On a phone the map and the claim panel cannot both be on screen, so the
  // panel becomes a sheet that the map opens.
  const [sheetOpen, setSheetOpen] = useState(false);
  const configured = tokenLive();
  useLocale();

  const { claims: allClaims, finds, shared: registryShared, setClaims, setFinds } = useAllClaims();
  // Everybody's discoveries, in the shape the world model wants them.
  const discovered = useMemo(
    () => finds.map((f) => ({ seed: f.seed, chart: f.chart, slot: f.slot })),
    [finds],
  );
  const plots = useMemo(() => marketPlots(player, chart, discovered), [player, chart, discovered]);
  const room = useMemo(() => chartRoom(player, chart, discovered), [player, chart, discovered]);
  const selected: Plot | null = plots.find((p) => p.seed === selectedSeed) ?? plots[0] ?? null;
  const registry = useChainOwner(selected?.seed ?? null);
  // What the claim will actually cost: the contract's number where there is a
  // contract, and the game's own otherwise.
  const price = useChainPrice(selected?.seed ?? null, selected?.price ?? 0);
  const explorer = selected ? plotExplorerUrl(selected.seed) : null;
  /*
   * Land this wallet holds according to the registry, whatever this browser
   * remembers.
   *
   * Without it, a player who cleared their site data or picked up a different
   * device would find their own plot on the market and be charged for it a
   * second time — the browser's record is a cache, and the registry is the
   * title. This is what makes ownership belong to the wallet rather than to
   * the machine it was claimed from.
   */
  const mineBySeed = useMemo(() => {
    const map = new Map<number, Claim>();
    if (!wallet.address) return map;
    const me = wallet.address.toLowerCase();
    for (const claim of allClaims) {
      if (claim.owner.toLowerCase() === me) map.set(claim.seed, claim);
    }
    return map;
  }, [allClaims, wallet.address]);

  const ownedSeeds = useMemo(
    () => new Set([...player.claims.map((c) => c.seed), ...mineBySeed.keys()]),
    [player.claims, mineBySeed],
  );
  const [visiting, setVisiting] = useState(false);
  const [buying, setBuying] = useState(false);
  const [offerAmount, setOfferAmount] = useState('');
  const [offering, setOffering] = useState(false);
  const [jobBusy, setJobBusy] = useState(false);
  const [tune, setTune] = useState(false);
  useEffect(() => { setTune(music.enabled); return music.subscribe(setTune); }, []);
  const me = wallet.address?.toLowerCase() ?? '';
  /** The plot this wallet works at, if any. */
  const myJob = useMemo(() => (me ? allClaims.find((c) => c.hand?.address === me) ?? null : null), [allClaims, me]);

  /*
   * Who holds what, minus this player's own land.
   *
   * Compared by address, not by whether the seed appears in this browser's
   * record: a player who cleared their site data still owns their plots, and
   * should be shown them as theirs rather than as somebody else's.
   */
  const takenByOthers = useMemo(() => {
    const map = new Map<number, Claim>();
    for (const claim of allClaims) {
      const mine = wallet.address && claim.owner.toLowerCase() === wallet.address.toLowerCase();
      if (!mine) map.set(claim.seed, claim);
    }
    return map;
  }, [allClaims, wallet.address]);

  const heldByOther = selected ? takenByOthers.get(selected.seed) ?? null : null;

  /*
   * A plot sold from under this browser's record.
   *
   * The registry is the title. When it says somebody else now holds a seed
   * this record still lists — the plot was bought while this tab was closed —
   * the record lets go of it, so the seller is not shown a world that is no
   * longer theirs and the world map does not call it "yours".
   */
  useEffect(() => {
    if (!registryShared || !wallet.address || !allClaims.length) return;
    const gone = player.claims.filter((c) => takenByOthers.has(c.seed)).map((c) => c.seed);
    if (!gone.length) return;
    let next = player;
    for (const seed of gone) next = withoutClaim(next, seed);
    onPlayer(next);
  }, [allClaims, registryShared, takenByOthers, player, onPlayer, wallet.address]);

  /*
   * The world this player owns here, if any.
   *
   * This browser's own record first, since it carries the transaction hash and
   * the name they chose; the registry's row second, for a wallet arriving on a
   * machine that has never seen this plot. Everything the panel says about
   * ownership reads from this rather than from local storage alone.
   */
  const mine: ClaimedWorld | null = useMemo(() => {
    if (!selected) return null;
    const local = claimOf(player, selected.seed);
    if (local) return local;
    const row = mineBySeed.get(selected.seed);
    return row
      ? {
          seed: row.seed, name: row.worldName, region: row.region, price: row.price,
          claimedAt: row.at, owner: row.owner, txHash: null,
        }
      : null;
  }, [selected, player, mineBySeed]);

  const choose = useCallback((plot: Plot) => {
    setSelectedSeed(plot.seed);
    setSheetOpen(true);
  }, []);

  /**
   * Pay to find new land.
   *
   * The registry picks the berth, because it is the only party that can see
   * every plot already surveyed on this chart. A client choosing for itself
   * could only avoid the ones it knew about, so two players prospecting the
   * same chart took the same slot and put two settlements on one point of the
   * map — each invisible to the other. The fee is charged only after the
   * registry has actually handed over land.
   */
  const prospect = useCallback(async () => {
    if (!wallet.address) {
      setNotice(t('Connect a wallet first. Land you survey is recorded against your address.'));
      return;
    }
    if (player.ledger.balance < PROSPECT_COST_EMERGE) {
      setNotice(t('Prospecting costs {cost} {ticker}.', { cost: PROSPECT_COST_EMERGE.toLocaleString(), ticker: TOKEN.ticker }));
      return;
    }
    setSurveying(true);
    setNotice(null);

    /*
     * Pay first, then ask for the land.
     *
     * The server will not survey anything without a burn it has read off the
     * chain, so the order has to be this way round — and it means a dismissed
     * wallet prompt costs the player nothing and gets them nothing, rather than
     * getting them land they did not pay for.
     */
    const paid = await spend(player.ledger, PROSPECT_COST_EMERGE, wallet.address);
    if (!paid.ok) { setSurveying(false); setNotice(paid.refused); return; }
    onPlayer({ ...player, ledger: paid.ledger });

    setNotice(t('Payment sent. Waiting for the chain to settle it…'));
    const result = await whileSettling(() => surveyPlot({
      chart,
      capacity: chartCapacity(chart),
      owner: wallet.address!,
      ownerName: player.name,
      burnTx: paid.txHash ?? undefined,
    }));
    setSurveying(false);
    if (!result.ok) {
      // The tokens are gone and the land is not. Say so plainly rather than
      // leaving somebody to work it out from a balance.
      setNotice(paid.txHash
        ? `${result.reason} ${t('Your payment {tx}… was accepted by the chain — keep it, and tell us if the land never arrives.', { tx: paid.txHash.slice(0, 10) })}`
        : `${result.reason} ${t('Sail to another chart to find new land.')}`);
      return;
    }

    const { find } = result;
    const found = inspectPlot(find.seed, find.slot, find.chart);
    setFinds((held) => [...held.filter((f) => f.seed !== find.seed), find]);
    onPlayer({
      ...player,
      ledger: paid.ledger,
      prospected: [...player.prospected, { seed: find.seed, chart: find.chart, slot: find.slot }],
    });
    setSelectedSeed(find.seed);
    setSheetOpen(true);
    setNotice(t('Surveyed {region} on {island} — {biome}. Everyone can see it now.', { region: found.region, island: found.island, biome: tn(found.biomeLabel).toLowerCase() }));
  }, [player, chart, onPlayer, wallet.address, setFinds]);

  const sail = useCallback((delta: number) => {
    setChart((c) => (c + delta + CHART_COUNT) % CHART_COUNT);
    setSelectedSeed(null);
    setSheetOpen(false);
    setNotice(null);
  }, []);

  /**
   * Take a plot.
   *
   * Three things have to be true, and the order matters. A wallet must be
   * connected, because a plot belongs to an address and everything the player
   * owns is keyed by it. The claim has to be accepted — by the contract where
   * one is deployed, otherwise by the shared relay — and a refusal there is
   * final: falling back to "claim it locally anyway" is exactly the bug this
   * exists to fix. Only then is the price charged, so a refused claim never
   * costs anything.
   *
   * With the registry deployed the contract does both at once: it takes
   * payment, burns it, and mints the title in the same transaction, so there is
   * no moment where a player has paid and does not own the land. The relay is
   * written afterwards as a cache, and a relay that is down costs nothing
   * because the plot is already theirs on chain.
   */
  const claim = useCallback(async () => {
    if (!selected) return;
    const other = takenByOthers.get(selected.seed);
    // The registry outranks this browser's memory of what it owns.
    if (other) {
      setNotice(t('{region} already belongs to {who}.', { region: selected.region, who: other.ownerName || shortAddress(other.owner) }));
      return;
    }
    // Already yours — by this browser's record or the registry's. Either way
    // this is the door back in, not a second purchase.
    if (mine) { onEnter(mine); return; }
    if (!wallet.address) {
      setNotice(t('Connect a wallet first. A plot belongs to an address, and so does everything you earn on it.'));
      return;
    }
    if (player.ledger.balance < price) {
      setNotice(t('{region} costs {price} {ticker}.', { region: selected.region, price: price.toLocaleString(), ticker: TOKEN.ticker }));
      return;
    }

    setClaiming(true);
    setNotice(null);
    const worldName = name.trim() || defaultWorldName(selected.seed);

    if (onChainClaimsLive()) {
      setNotice(t('Approve the spend, then confirm the claim. Two signatures, and the second one is the title.'));
      const minted = await claimOnChain(wallet.address, selected.seed, worldName);
      setClaiming(false);
      if (!minted.ok) { setNotice(minted.message); return; }

      const charged = minted.price ?? price;
      onPlayer({ ...player, ledger: await settleBurn(player.ledger, charged, wallet.address) });

      // Cache it in the relay so the map, chat and visitor list have a name and
      // a date to show. The chain already holds the title, so a relay that
      // refuses this changes nothing about who owns the land.
      await takePlot({
        seed: selected.seed,
        region: selected.region,
        worldName,
        owner: wallet.address,
        ownerName: player.name,
        price: charged,
      });

      onEnter({
        seed: selected.seed,
        name: worldName,
        region: selected.region,
        price: charged,
        claimedAt: Date.now(),
        owner: wallet.address,
        txHash: minted.txHash,
      });
      return;
    }

    /*
     * Hold the plot, pay for it, then claim it with the receipt.
     *
     * Three steps in this order for three reasons. The hold means a refusal
     * arrives before any money moves, so nobody burns tokens for land somebody
     * else is taking. The payment comes second because the server will not
     * write a title without a burn it has read off the chain — this is what the
     * land contract used to guarantee by taking payment and minting in one
     * transaction, and with no contract deployed it has to be reconstructed out
     * of two steps and a receipt. And the claim comes last, so the row that
     * says who owns this land is only ever written against a payment that
     * really happened.
     */
    const reserved = await reservePlot(selected.seed, wallet.address);
    if (!reserved.ok) {
      setClaiming(false);
      setNotice(reserved.reason);
      return;
    }

    const paid = await spend(player.ledger, price, wallet.address);
    if (!paid.ok) {
      setClaiming(false);
      setNotice(paid.refused ?? t('Not enough {ticker} to claim {region}.', { ticker: TOKEN.ticker, region: selected.region }));
      return;
    }
    onPlayer({ ...player, ledger: paid.ledger });

    setNotice(t('Payment sent. Waiting for the chain to settle it…'));
    const registered = await whileSettling(() => takePlot({
      seed: selected.seed,
      region: selected.region,
      worldName,
      owner: wallet.address!,
      ownerName: player.name,
      price,
      burnTx: paid.txHash ?? undefined,
    }));
    setClaiming(false);

    if (!registered.ok) {
      setNotice(paid.txHash
        ? `${registered.reason} ${t('Your payment {tx}… went through — keep it, and tell us if the land never arrives.', { tx: paid.txHash.slice(0, 10) })}`
        : registered.reason);
      // Show the land as theirs straight away rather than making the player
      // wait for the next poll to understand why they were refused.
      if (registered.taken?.owner) {
        setClaims((held2) => [...held2.filter((c) => c.seed !== registered.taken!.seed), registered.taken!]);
      }
      return;
    }

    onEnter({
      seed: selected.seed,
      name: worldName,
      region: selected.region,
      price,
      claimedAt: Date.now(),
      owner: wallet.address,
      txHash: paid.txHash,
    });
  }, [name, selected, price, wallet.address, onEnter, onPlayer, player, takenByOthers, mineBySeed, setClaims]);

  /**
   * Buy a plot its owner has put up for sale.
   *
   * The price goes to the seller's wallet — a transfer, not a burn — and the
   * registry moves the title once it has seen the payment land. The
   * settlement comes with the land: the buyer walks into the town as the
   * seller left it.
   */
  const buy = useCallback(async (listing: Claim) => {
    if (!wallet.address) {
      setNotice(t('Connect a wallet first. A plot belongs to an address, and so does everything you earn on it.'));
      return;
    }
    const askPrice = priceFor(listing, wallet.address) ?? 0;
    if (player.ledger.balance < askPrice) {
      setNotice(t('{region} costs {price} {ticker}.', { region: listing.region, price: askPrice.toLocaleString(), ticker: TOKEN.ticker }));
      return;
    }
    setBuying(true);
    setNotice(configured
      ? t('Paying {who} directly. Sign the transfer to their wallet.', { who: listing.ownerName || shortAddress(listing.owner) })
      : t('Paying {who}…', { who: listing.ownerName || shortAddress(listing.owner) }));
    const paid = await pay(player.ledger, askPrice, wallet.address, listing.owner);
    if (!paid.ok) { setBuying(false); setNotice(paid.refused); return; }
    onPlayer({ ...player, ledger: paid.ledger });
    setNotice(t('Payment sent. Waiting for the chain to settle it…'));
    const moved = await whileSettling(() => buyPlot({
      seed: listing.seed,
      owner: wallet.address!,
      ownerName: player.name,
      transferTx: paid.txHash ?? undefined,
    }));
    setBuying(false);
    if (!moved.ok) {
      setNotice(paid.txHash
        ? `${moved.reason} ${t('Your payment {tx}… went through — keep it, and tell us if the land never arrives.', { tx: paid.txHash.slice(0, 10) })}`
        : moved.reason);
      return;
    }
    setClaims((held) => held.map((c) => (c.seed === listing.seed ? moved.claim : c)));
    onEnter({
      seed: listing.seed,
      name: moved.claim.worldName,
      region: moved.claim.region,
      price: moved.price,
      claimedAt: Date.now(),
      owner: wallet.address,
      txHash: paid.txHash,
    });
  }, [wallet.address, player, onPlayer, onEnter, setClaims, configured]),

  /** Offer a price for somebody else's plot, or take the offer back. */
  offer = useCallback(async (listing: Claim, price: number | null) => {
    if (!wallet.address) {
      setNotice(t('Connect a wallet first. A plot belongs to an address, and so does everything you earn on it.'));
      return;
    }
    setOffering(true);
    const result = price === null
      ? await withdrawOffer(listing.seed, wallet.address)
      : await placeOffer(listing.seed, wallet.address, player.name, price);
    setOffering(false);
    if (!result.ok || !result.claim) { setNotice(result.reason ?? null); return; }
    const row = result.claim;
    setClaims((held) => held.map((c) => (c.seed === row.seed ? row : c)));
    setNotice(price === null
      ? t('Your offer on {region} was withdrawn.', { region: listing.region })
      : t('Your offer of {price} {ticker} is with {who}. If they accept, the plot is held for you at that price for two days.', { price: price.toLocaleString(), ticker: TOKEN.ticker, who: listing.ownerName || shortAddress(listing.owner) }));
  }, [wallet.address, player.name, setClaims]),

  /** Take the job at somebody's plot, and go straight to work. */
  takeTheJob = useCallback(async (listing: Claim) => {
    if (!wallet.address) return;
    setJobBusy(true);
    const result = await takeJob(listing.seed, wallet.address, player.name);
    setJobBusy(false);
    if (!result.ok || !result.claim) { setNotice(result.reason ?? null); return; }
    const row = result.claim;
    setClaims((held) => held.map((c) => (c.seed === row.seed ? row : c)));
    setNotice(t('You work at {world} now. Keep it open and in view to be paid.', { world: listing.worldName }));
    setVisiting(true);
    const refused = await onVisit(listing.seed);
    setVisiting(false);
    if (refused) setNotice(refused);
  }, [wallet.address, player.name, setClaims, onVisit]),

  /** Leave the job. */
  leaveJob = useCallback(async (listing: Claim) => {
    if (!wallet.address) return;
    setJobBusy(true);
    const result = await quitJob(listing.seed, wallet.address);
    setJobBusy(false);
    if (!result.ok || !result.claim) { setNotice(result.reason ?? null); return; }
    const row = result.claim;
    setClaims((held) => held.map((c) => (c.seed === row.seed ? row : c)));
    setNotice(t('You left the job at {world}.', { world: listing.worldName }));
  }, [wallet.address, setClaims]),

  /** Go and look at the settlement somebody else built here. */
  visit = useCallback(async (seed: number) => {
    setVisiting(true);
    setNotice(null);
    const refused = await onVisit(seed);
    setVisiting(false);
    if (refused) setNotice(refused);
  }, [onVisit]);

  /** What this player has up for sale, as the registry has it. */
  const myListings = useMemo(
    () => allClaims.filter((c) => c.forSale && wallet.address && c.owner.toLowerCase() === wallet.address.toLowerCase()),
    [allClaims, wallet.address],
  );
  const worldTotal = worldCapacity();
  const claimedTotal = allClaims.length;
  /** This wallet's offer on the selected plot, and what the plot would cost it now. */
  const myOffer = heldByOther && wallet.address
    ? (heldByOther.offers ?? []).find((o) => o.buyer === wallet.address!.toLowerCase()) ?? null
    : null;
  const buyable = heldByOther ? priceFor(heldByOther, wallet.address) : null;
  const otherOffers = heldByOther ? (heldByOther.offers ?? []).filter((o) => o.buyer !== wallet.address?.toLowerCase()) : [];
  /** Every offer this wallet has out, across the whole map, so an accepted one is not missed. */
  const myOffers = useMemo(() => {
    const me = wallet.address?.toLowerCase();
    if (!me) return [] as { claim: Claim; offer: NonNullable<Claim['offers']>[number] }[];
    return allClaims.flatMap((c) => (c.offers ?? []).filter((o) => o.buyer === me).map((offer) => ({ claim: c, offer })));
  }, [allClaims, wallet.address]);


  return (
    <main className="world-map">
      <div className="land-inner">
        <header className="land-head">
          <BrandLine />
          <p className="land-intro">
            {t('Every plot is a world waiting to happen, and no two are the same land. Claim one with {ticker}, give it a name, and the beings who live there will call it that.', { ticker: TOKEN.ticker })}
          </p>
          <div className="land-head-side">
            <div className="map-nav">
              <button className="ghost" onClick={onHome}>{t('← Home')}</button>
              <button className={`ghost ${tune ? 'on' : ''}`} onClick={() => music.toggle()} title={tune ? t('Music off') : t('Music on')}>
                {tune ? '♪' : '♪̸'}
              </button>
              {wallet.address && (
                <button className="ghost" onClick={onDisconnect} title={t('Your plots and balance stay with the address; connect again any time.')}>
                  {t('Disconnect wallet')}
                </button>
              )}
              <LanguageSwitch />
            </div>
            <div className="land-balance">
              <span>{t('YOUR BALANCE')}</span>
              <b>{Math.floor(player.ledger.balance).toLocaleString()}</b>
              <em>{TOKEN.ticker}</em>
            </div>
            <button
              className="ghost prospect"
              onClick={prospect}
              disabled={surveying || !wallet.address || player.ledger.balance < PROSPECT_COST_EMERGE || room.free === 0}
            >
              {surveying
                ? t('Surveying…')
                : room.free === 0
                  ? t('This chart is fully surveyed')
                  : !wallet.address
                    ? t('Connect a wallet to survey')
                    : t('Prospect new land · {cost} {ticker}', { cost: PROSPECT_COST_EMERGE.toLocaleString(), ticker: TOKEN.ticker })}
            </button>
          </div>
        </header>

        {/* Where in the world you are looking. Each chart holds a fixed number
            of plots; when it is full the only way to new land is to sail. */}
        <nav className="charts">
          <button className="ghost" onClick={() => sail(-1)} aria-label={t('Previous chart')}>‹</button>
          <div className="chart-name">
            <b>{tx(chartName(chart))}</b>
            <em>
              {t('{used} of {all} plots surveyed', { used: room.used, all: room.capacity })}
              {room.free === 0 ? ` · ${t('nothing left to find here')}` : ` · ${t('room for {n} more', { n: room.free })}`}
            </em>
          </div>
          <button className="ghost" onClick={() => sail(1)} aria-label={t('Next chart')}>›</button>
        </nav>
        {/* The whole world, not this chart: how much land is spoken for and how
            much is still to be had, which is the number that says whether
            there is any hurry. */}
        <div className="world-count">
          <span><b>{claimedTotal.toLocaleString()}</b> {t('of {total} plots claimed', { total: worldTotal.toLocaleString() })}</span>
          <span><b>{Math.max(0, worldTotal - claimedTotal).toLocaleString()}</b> {t('left to claim')}</span>
        </div>

        <div className="land-body">
          <RegionMap
            plots={plots} selected={selected} chart={chart} owned={ownedSeeds}
            taken={takenByOthers} claimedEverywhere={allClaims.length} onSelect={choose}
          />

          {!selected ? (
            <aside className="land-claim empty">
              <span className="eyebrow">{t('UNSURVEYED')}</span>
              <h2>{tx(chartName(chart))}</h2>
              <p className="muted">
                {t('Nobody has set foot on these islands. There is room for {n} settlements out here; survey one to see what the land is made of.', { n: room.capacity })}
              </p>
              <button
                className="claim-button"
                onClick={prospect}
                disabled={surveying || !wallet.address || player.ledger.balance < PROSPECT_COST_EMERGE}
              >
                {surveying
                  ? t('Surveying…')
                  : !wallet.address
                    ? t('Connect a wallet to survey')
                    : t('Survey a plot · {cost} {ticker}', { cost: PROSPECT_COST_EMERGE.toLocaleString(), ticker: TOKEN.ticker })}
              </button>
              {notice && <p className="warn">{tx(notice)}</p>}
            </aside>
          ) : (
          <aside className={`land-claim ${sheetOpen ? 'open' : ''}`}>
            <button className="sheet-close" onClick={() => setSheetOpen(false)} aria-label={t('Back to the map')}>×</button>
            {/* The registry decides, not this browser's memory. A stale local
                claim on land somebody else now holds must read as theirs. */}
            <span className="eyebrow">{heldByOther ? (buyable !== null ? t('FOR SALE') : t('SETTLED')) : mine ? t('YOUR WORLD') : t('CLAIM')}</span>
            <h2>{heldByOther ? heldByOther.worldName : mine ? mine.name : selected.region}</h2>
            <div className="plot-traits">
              <span className={`biome-tag ${selected.biome}`}>{tn(selected.biomeLabel)}</span>
              <span>{selected.island}</span>
              <span>{t('{n} beings', { n: selected.population })}</span>
              {mine && !heldByOther && <span className="owned-tag">{t('Yours')}</span>}
              {heldByOther && !heldByOther.forSale && <span className="settled-tag-big">{t('Taken')}</span>}
              {heldByOther && !!heldByOther.forSale && <span className="sale-tag-big">{t('For sale')}</span>}
            </div>
            {mine && !heldByOther && (
              <p className="muted small">
                {t('Claimed {date} for {price} {ticker}', { date: new Date(mine.claimedAt).toLocaleDateString(), price: mine.price.toLocaleString(), ticker: TOKEN.ticker })}
                {mine.owner ? t(' by {address}', { address: shortAddress(mine.owner) }) : t(' with no wallet connected')}.
                {mine.txHash ? ` ${t('Paid on chain: {tx}.', { tx: mine.txHash })}` : ''}
              </p>
            )}
            {/* Who else holds this land. */}
            {heldByOther && (
              <div className="settled-by">
                <p className="muted small">
                  {t('Settled by {who} on {date}, and called {world}.', { who: heldByOther.ownerName || shortAddress(heldByOther.owner), date: new Date(heldByOther.at).toLocaleDateString(), world: heldByOther.worldName })}
                </p>
                <button className="ghost" onClick={() => visit(heldByOther.seed)} disabled={visiting}>
                  {visiting ? t('Travelling…') : t('Visit {world}', { world: heldByOther.worldName })}
                </button>
                {!!heldByOther.forSale && (
                  <p className="muted small">
                    {t('Up for sale at {price} {ticker}. The price goes to {who}’s wallet, not to the burn address, and the settlement comes with the land.', { price: heldByOther.forSale.toLocaleString(), ticker: TOKEN.ticker, who: heldByOther.ownerName || shortAddress(heldByOther.owner) })}
                  </p>
                )}
                {/* Work: the plot is hiring, or you already work here. Only for
                    players without land — a landholder has their own to run. */}
                {(heldByOther.hiring || heldByOther.hand?.address === me) && (
                  <div className="job-box">
                    <span className="eyebrow">{t('WORK')}</span>
                    {heldByOther.hand?.address === me ? (
                      <>
                        <p className="muted small">{t('You work here. Open the world and keep it in view to be paid; your shift counts as the owner’s attention.')}</p>
                        <div className="offer-row">
                          <button className="claim-button" onClick={() => visit(heldByOther.seed)} disabled={visiting}>{visiting ? t('Travelling…') : t('Go to work')}</button>
                          <button className="ghost" onClick={() => leaveJob(heldByOther)} disabled={jobBusy}>{t('Quit')}</button>
                        </div>
                      </>
                    ) : heldByOther.hand ? (
                      <p className="muted small">{t('{who} works here.', { who: heldByOther.hand.name || shortAddress(heldByOther.hand.address) })}</p>
                    ) : (
                      <>
                        <p className="muted small">
                          {t('{who} is hiring a hand. A hand holds at least {min} {ticker} and no land, attends the plot while its owner is away, and is paid {share} of its stewardship — up to {cap} {ticker} a day — by the vault.', { who: heldByOther.ownerName || shortAddress(heldByOther.owner), min: HAND_MIN_EMERGE.toLocaleString(), ticker: TOKEN.ticker, share: `${Math.round(HAND_SHARE * 100)}%`, cap: HAND_DAILY_CEILING.toLocaleString() })}
                        </p>
                        <button
                          className="ghost"
                          disabled={jobBusy || !wallet.address || ownedSeeds.size > 0 || player.ledger.balance < HAND_MIN_EMERGE}
                          onClick={() => takeTheJob(heldByOther)}
                        >
                          {jobBusy ? t('Asking…') : !wallet.address ? t('Connect a wallet to work') : ownedSeeds.size > 0 ? t('Landholders run their own plots') : player.ledger.balance < HAND_MIN_EMERGE ? t('Needs {min} {ticker}', { min: HAND_MIN_EMERGE.toLocaleString(), ticker: TOKEN.ticker }) : t('Work here')}
                        </button>
                      </>
                    )}
                  </div>
                )}
                {/* Offers: yours, and the fact of the others'. Any plot can be
                    offered for, listed or not; the owner decides. */}
                <div className="offer-box">
                  <span className="eyebrow">{t('OFFERS')}</span>
                  {otherOffers.length > 0 && (
                    <p className="muted small">
                      {t('{n} other offers, the best at {price} {ticker}.', { n: otherOffers.length, price: otherOffers[0].price.toLocaleString(), ticker: TOKEN.ticker })}
                    </p>
                  )}
                  {myOffer ? (
                    <div className="my-offer">
                      <b>{t('Your offer: {price} {ticker}', { price: myOffer.price.toLocaleString(), ticker: TOKEN.ticker })}</b>
                      <span className="muted small">
                        {myOffer.acceptedUntil && myOffer.acceptedUntil > Date.now()
                          ? t('Accepted. It is yours at that price until {when}.', { when: new Date(myOffer.acceptedUntil).toLocaleString() })
                          : t('Waiting on the owner.')}
                      </span>
                      {myOffer.acceptedUntil && myOffer.acceptedUntil > Date.now() ? (
                        // The payment itself: exactly the accepted amount, to the
                        // seller's wallet, and the plot is theirs when it lands.
                        <button
                          className="claim-button pay-offer"
                          disabled={buying || !wallet.address || player.ledger.balance < myOffer.price}
                          onClick={() => buy(heldByOther)}
                        >
                          {buying
                            ? t('Sending payment…')
                            : player.ledger.balance < myOffer.price
                              ? t('Not enough {ticker}', { ticker: TOKEN.ticker })
                              : t('Send {price} {ticker} to {who}', { price: myOffer.price.toLocaleString(), ticker: TOKEN.ticker, who: heldByOther.ownerName || shortAddress(heldByOther.owner) })}
                        </button>
                      ) : (
                        <button className="ghost" onClick={() => offer(heldByOther, null)} disabled={offering}>{t('Withdraw offer')}</button>
                      )}
                    </div>
                  ) : (
                    <div className="offer-row">
                      <input
                        value={offerAmount}
                        inputMode="numeric"
                        placeholder={String(Math.round((heldByOther.forSale ?? selected.price) * 0.8))}
                        onChange={(e) => setOfferAmount(e.target.value.replace(/[^0-9]/g, ''))}
                      />
                      <button
                        className="ghost"
                        disabled={offering || !wallet.address}
                        onClick={() => offer(heldByOther, Number(offerAmount) || Math.round((heldByOther.forSale ?? selected.price) * 0.8))}
                      >
                        {offering ? t('Sending…') : t('Make an offer')}
                      </button>
                    </div>
                  )}
                  <p className="muted small">
                    {t('An offer holds nothing back: if the owner accepts, the plot is held for you at that price for two days and you pay their wallet directly, as for any sale.')}
                  </p>
                </div>
              </div>
            )}
            {registry?.onChain && registry.owner && !mine && !heldByOther && (
              <p className="muted small">
                {t('Held on {chain} by {address}.', { chain: ACTIVE_CHAIN.label, address: shortAddress(registry.owner) })}
              </p>
            )}
            {/* The title itself, for anybody who would rather check than be
                told. It is an ordinary ERC-721 token whose id is this plot's
                seed, so an explorer can read it without going through us. */}
            {onChainClaimsLive() && explorer && (
              <p className="muted small">
                <a href={explorer} target="_blank" rel="noreferrer noopener">
                  {t('Verify this plot on {chain}', { chain: ACTIVE_CHAIN.label })}
                </a>{' '}— {t('token #{seed} of the Emerge Land registry.', { seed: selected.seed })}
              </p>
            )}
            {!registryShared && !mine && (
              <p className="muted small">
                {t('This build has no shared registry behind it, so the only claims on this map are the ones made in this browser. Other players’ land will not show until one is configured.')}
              </p>
            )}

            <PlotPreview seed={selected.seed} />
            <p className="muted">{t(selected.blurb)}</p>

            <span className="eyebrow">{t('TRADES THIS LAND SUPPORTS')}</span>
            <div className="plot-traits">
              {selected.trades.map((trade) => <span key={trade}>{tn(trade)}</span>)}
            </div>

            {!mine && (
              <label className="name-field">
                <span>{t('NAME YOUR WORLD')}</span>
                <input
                  value={name}
                  maxLength={24}
                  placeholder={defaultWorldName(selected.seed)}
                  onChange={(e) => setName(e.target.value)}
                />
              </label>
            )}

            <div className="claim-price">
              <span>{mine ? t('PAID') : buyable !== null ? t('ASKING') : t('PRICE')}</span>
              <b>{(mine ? mine.price : buyable !== null ? buyable : price).toLocaleString()}</b>
              <em>{TOKEN.ticker}</em>
            </div>

            <div className="claim-wallet"><WalletPicker compact /></div>

            <button
              className="claim-button"
              onClick={() => (heldByOther ? (buyable !== null ? buy(heldByOther) : visit(heldByOther.seed)) : claim())}
              disabled={
                claiming || visiting || buying
                || (!mine && !heldByOther && !wallet.address)
                || (!mine && !heldByOther && player.ledger.balance < price)
                || (buyable !== null && (!wallet.address || player.ledger.balance < buyable))
              }
            >
              {claiming
                ? t('Claiming…')
                : heldByOther && buyable !== null
                  ? (buying ? t('Buying…') : !wallet.address ? t('Connect a wallet to buy') : player.ledger.balance < buyable ? t('Not enough {ticker}', { ticker: TOKEN.ticker }) : t('Buy {region} · {price} {ticker}', { region: heldByOther.region, price: buyable.toLocaleString(), ticker: TOKEN.ticker }))
                : heldByOther
                  ? (visiting ? t('Travelling…') : t('Visit {world}', { world: heldByOther.worldName }))
                  : mine
                    ? t('Enter {world}', { world: mine.name })
                    : !wallet.address
                      ? t('Connect a wallet to claim land')
                      : player.ledger.balance < price
                        ? t('Not enough {ticker}', { ticker: TOKEN.ticker })
                        : t('Claim {region} · {price} {ticker}', { region: selected.region, price: price.toLocaleString(), ticker: TOKEN.ticker })}
            </button>
            {!wallet.address && !mine && !heldByOther && (
              <p className="muted small">
                {t('Your plots, your balance and your name all belong to a wallet address rather than to this browser, so there is nothing for a claim to belong to until one is connected.')}
              </p>
            )}

            {myJob && myJob.seed !== selected.seed && (
              <div className="owned-list">
                <span className="eyebrow">{t('YOUR JOB')}</span>
                <button className="owned-row" onClick={() => visit(myJob.seed)} disabled={visiting}>
                  <b>{myJob.worldName}</b>
                  <span className="muted small">{t('hired hand · {region}', { region: myJob.region })}</span>
                </button>
              </div>
            )}
            {player.claims.length > 0 && (
              <>
                <span className="eyebrow">{t('WORLDS YOU OWN')}</span>
                <div className="listing-list">
                  {[...player.claims].sort((a, b) => a.claimedAt - b.claimedAt).map((c, i) => (
                    <div key={c.seed} className={`listing-row ${c.seed === selected.seed ? 'here' : ''}`}>
                      <span>{c.name}{i >= EARNING_PLOT_LIMIT && <i className="idle-plot">{t('not earning')}</i>}</span>
                      <b>{c.region}</b>
                      <button className="ghost" onClick={() => onEnter(c)}>{t('Enter')}</button>
                    </div>
                  ))}
                </div>
                {player.claims.length > EARNING_PLOT_LIMIT && (
                  <p className="muted small">
                    {t('The first {n} worlds you claimed earn {ticker}; the rest are yours to play with. Give one up and the next in line starts earning.', { n: EARNING_PLOT_LIMIT, ticker: TOKEN.ticker })}
                  </p>
                )}
              </>
            )}

            {myOffers.length > 0 && (
              <>
                <span className="eyebrow">{t('YOUR OFFERS')}</span>
                <div className="listing-list">
                  {myOffers.map(({ claim: c, offer: o }) => {
                    const held = !!o.acceptedUntil && o.acceptedUntil > Date.now();
                    return (
                      <div key={c.seed} className={`listing-row ${held ? 'held' : ''} ${c.seed === selected.seed ? 'here' : ''}`}>
                        <span>{c.region}{held && <i className="idle-plot accepted">{t('accepted')}</i>}</span>
                        <b>{o.price.toLocaleString()} {TOKEN.ticker}</b>
                        <button className="ghost" onClick={() => choose(plots.find((pl) => pl.seed === c.seed) ?? selected)}>
                          {held ? t('Pay') : t('View')}
                        </button>
                      </div>
                    );
                  })}
                </div>
              </>
            )}

            {myListings.length > 0 && (
              <>
                <span className="eyebrow">{t('YOUR LISTINGS')}</span>
                <div className="listing-list">
                  {myListings.map((listing) => (
                    <div key={listing.seed} className="listing-row">
                      <span>{listing.region}</span>
                      <b>{(listing.forSale ?? 0).toLocaleString()} {TOKEN.ticker}</b>
                    </div>
                  ))}
                </div>
                <p className="muted small">
                  {onChainClaimsLive()
                    ? t('A plot is an ordinary ERC-721 token, so it sells anywhere that handles them — wallet to wallet, or on any marketplace on {chain}. A listing here is a note to yourself until this game carries a marketplace of its own.', { chain: ACTIVE_CHAIN.label })
                    : t('Everybody sees these on the map. A buyer pays your wallet directly in {ticker} — nothing is burned — and the plot and its settlement move to them. Take a listing down from the On-Chain panel inside the world.', { ticker: TOKEN.ticker })}
                </p>
              </>
            )}

            {onChainClaimsLive() ? (
              <p className="muted small">
                {t('This is real ownership. The price above is read from the land contract, so it is the price the transaction enforces; claiming mints token #{seed} of the Emerge Land registry to your address and burns what it cost inside the same transaction. Nobody, this game included, can move a plot out of the wallet holding it.', { seed: selected.seed })}
              </p>
            ) : configured ? (
              <p className="muted small">
                {t('Prices are real. Your balance is read from your wallet on {chain}, and claiming asks you to sign a transfer that destroys the {ticker} it costs. Ownership is recorded in the shared registry until the land contract is deployed, so a claim is enforced for every player but is not yet an on-chain title.', { chain: ACTIVE_CHAIN.label, ticker: TOKEN.ticker })}
              </p>
            ) : (
              <p className="muted small">
                {t('This build talks to {chain} (chain {id}), but the {ticker} contract is not deployed there yet, so claims are recorded in the shared registry rather than on chain and you start with a local development allocation of {allocation} {ticker}. Neither is a token transfer.', { chain: ACTIVE_CHAIN.label, id: ACTIVE_CHAIN.chainId ?? '', ticker: TOKEN.ticker, allocation: LOCAL_TEST_ALLOCATION.toLocaleString() })}
              </p>
            )}
            {notice && <p className="warn">{tx(notice)}</p>}
          </aside>
          )}
        </div>
      </div>
    </main>
  );
}
