'use client';

/**
 * The world map.
 *
 * A map of the whole region, with every plot on it in its place. The land is
 * painted from the plots themselves — each one's territory takes the colour of
 * its biome — so the desert really is out west and the fen really is down by
 * the southern water, and choosing where to settle is a decision about a place
 * rather than a scroll through a list of cards.
 *
 * Selecting a plot brings up its real terrain, generated by the same code that
 * will run the world once it is claimed, so the ground shown is the ground you
 * get.
 *
 * Claims are shared. The relay holds one row per plot, so land another player
 * took is marked here as theirs and cannot be claimed a second time — and their
 * settlement can be visited from the marker. That registry is the server's
 * word, not this browser's; when the contract is deployed it becomes the
 * chain's, and nothing above this line changes.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { defaultWorldName } from '@/lib/simulation';
import {
  CHART_COUNT, HOME_CHART_INDEX, chartCapacity, chartName, chartRoom, claimOf, drawPlotPreview,
  drawRegionMap, inspectPlot, islandsFor, marketPlots,
  type ClaimedWorld, type PlayerRecord, type Plot,
} from '@/lib/world/plots';
import {
  ACTIVE_CHAIN, TOKEN, claimPlot, plotOwner, registryLive, shortAddress, tokenLive,
  type PlotOwnership,
} from '@/lib/chain/emerge';
import {
  allOnChainPlots, claimOnChain, onChainClaimsLive, plotExplorerUrl, registryPrice,
} from '@/lib/chain/registry';
import { EARNING_PLOT_LIMIT, LOCAL_TEST_ALLOCATION, PROSPECT_COST_EMERGE } from '@/lib/chain/vault';
import { settleBurn, spend } from '@/lib/chain/spend';
import {
  fetchClaims, reservePlot, surveyPlot, takePlot, type Claim, type Find,
} from '@/lib/net/registry';
import { WalletPicker, useWallet } from './WalletPicker';
import { BrandLine } from './Brand';

/**
 * Ask the chain who owns a plot.
 *
 * Only answers once the registry contract exists. The shared relay below is
 * what actually keeps two players off the same land today; this is here so
 * that the moment the contract is deployed the chain's answer is the one shown.
 */
function useChainOwner(seed: number | null) {
  const [state, setState] = useState<PlotOwnership | null>(null);
  useEffect(() => {
    if (seed === null || !registryLive()) { setState(null); return; }
    let live = true;
    setState(null);
    plotOwner(seed).then((result) => { if (live) setState(result); });
    return () => { live = false; };
  }, [seed]);
  return state;
}

/**
 * What the contract will charge for a plot.
 *
 * The price on the button has to be the price the transaction enforces, or the
 * first time the contract's pricing is adjusted the claim reverts with nothing
 * on screen to explain why. Falls back to the game's own price when there is no
 * registry to ask, which is the same number the contract is configured to
 * produce.
 */
function useChainPrice(seed: number | null, fallback: number) {
  const [price, setPrice] = useState(fallback);
  useEffect(() => {
    setPrice(fallback);
    if (seed === null || !onChainClaimsLive()) return;
    let live = true;
    registryPrice(seed).then((quoted) => {
      if (live && quoted !== null && quoted > 0) setPrice(quoted);
    });
    return () => { live = false; };
  }, [seed, fallback]);
  return price;
}

/**
 * Keep submitting a paid request while the chain settles.
 *
 * The server checks a payment a few blocks deep, and the first ask almost
 * always lands before the node has it. `settling` is the server saying "real,
 * but not yet" — which is worth waiting through rather than reporting as a
 * refusal, because the player has already burned the tokens.
 */
async function whileSettling<T extends { ok: boolean; settling?: boolean }>(
  attempt: () => Promise<T>,
  tries = 10,
  gapMs = 2_500,
): Promise<T> {
  let last = await attempt();
  for (let i = 1; i < tries && !last.ok && last.settling; i++) {
    await new Promise((resolve) => setTimeout(resolve, gapMs));
    last = await attempt();
  }
  return last;
}

/** How often the map re-reads who owns what, in milliseconds. */
const CLAIMS_POLL = 12_000;

/**
 * Every claim anybody holds, kept fresh.
 *
 * Polled rather than pushed: land changes hands a few times an hour at most,
 * and a poll survives a serverless deployment where a socket does not.
 */
function useAllClaims() {
  const [claims, setClaims] = useState<Claim[]>([]);
  const [finds, setFinds] = useState<Find[]>([]);
  const [shared, setShared] = useState(true);
  useEffect(() => {
    let live = true;
    const tick = async () => {
      const result = await fetchClaims();
      if (!live) return;
      setFinds(result.finds);
      setShared(result.shared && !result.offline);

      /*
       * The chain outranks the relay.
       *
       * The relay is a cache that makes the map quick and gives a claim a name
       * and a date; the contract is the title. Where they disagree about who
       * holds a plot the chain wins, because it is the thing that is actually
       * enforced — but a relay row the chain has never heard of is kept rather
       * than dropped. Dropping it would put land somebody holds back on the
       * market, and no reading of the two records is worth that.
       */
      const chain = await allOnChainPlots();
      if (!live) return;
      if (!chain) { setClaims(result.claims); return; }

      const bySeed = new Map(result.claims.map((c) => [c.seed, c]));
      for (const plot of chain) {
        const cached = bySeed.get(plot.seed);
        bySeed.set(plot.seed, {
          seed: plot.seed,
          region: cached?.region ?? `Plot ${plot.seed}`,
          worldName: plot.worldName || cached?.worldName || 'Emerge',
          owner: plot.owner,
          ownerName: cached?.ownerName ?? '',
          price: cached?.price ?? 0,
          at: cached?.at ?? 0,
        });
      }
      setClaims([...bySeed.values()]);
    };
    tick();
    const timer = window.setInterval(tick, CLAIMS_POLL);
    return () => { live = false; window.clearInterval(timer); };
  }, []);
  return { claims, finds, shared, setClaims, setFinds };
}

function PlotPreview({ seed }: { seed: number }) {
  const ref = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    // Generation takes a few tens of milliseconds; yielding a frame first keeps
    // the panel from appearing after a visible stall when the selection changes.
    const id = requestAnimationFrame(() => drawPlotPreview(canvas, seed));
    return () => cancelAnimationFrame(id);
  }, [seed]);
  return <canvas ref={ref} width={320} height={180} className="plot-canvas" />;
}

/**
 * The region.
 *
 * The canvas is painted once per set of plots and never re-rendered by React;
 * the markers are real buttons laid over it, so they can be tabbed to, focused
 * and read by a screen reader instead of being pixels with a hit test.
 */
function RegionMap({ plots, selected, chart, owned, taken, onSelect }: {
  plots: Plot[];
  selected: Plot | null;
  chart: number;
  /** Seeds this player holds, so their own land is marked on the map. */
  owned: Set<number>;
  /** Seeds somebody else holds, by seed, so their land is marked as theirs. */
  taken: Map<number, Claim>;
  onSelect: (plot: Plot) => void;
}) {
  const ref = useRef<HTMLCanvasElement | null>(null);
  useEffect(() => {
    if (ref.current) drawRegionMap(ref.current, plots, chart);
  }, [plots, chart]);

  return (
    <div className="region">
      <canvas ref={ref} width={900} height={570} className="region-canvas" aria-hidden />
      <div className="region-pins">
        {/* Every island is named, surveyed or not: an empty coast the player
            can see is what makes prospecting somewhere to go. */}
        {islandsFor(chart).map((island) => (
          <span
            key={island.name}
            className="island-name"
            // Below the island, where the markers are not.
            style={{ left: `${island.x * 100}%`, top: `${(island.y + island.ry * 0.92) * 100}%` }}
          >
            {island.name}
          </span>
        ))}
        {plots.map((plot) => {
          const mine = owned.has(plot.seed);
          const theirs = !mine ? taken.get(plot.seed) : undefined;
          return (
          <button
            key={plot.id}
            // A marker on the right-hand side of the map hangs its label to the
            // left, or it runs off the edge.
            className={`region-pin ${plot.biome} ${plot.mapX > 0.66 ? 'flip' : ''} ${plot.seed === selected?.seed ? 'selected' : ''} ${mine ? 'owned' : ''} ${theirs ? 'settled' : ''}`}
            style={{ left: `${plot.mapX * 100}%`, top: `${plot.mapY * 100}%` }}
            onClick={() => onSelect(plot)}
            aria-pressed={plot.seed === selected?.seed}
          >
            <span className="pin-dot" aria-hidden />
            <span className="pin-label">
              <b>
                {plot.region}
                {mine && <i className="yours">yours</i>}
                {theirs && <i className="settled-tag">settled</i>}
              </b>
              {/* The biome only on the one being looked at. Nine markers each
                  carrying two lines of text is more label than map. */}
              {plot.seed === selected?.seed && <em>{plot.biomeLabel}</em>}
            </span>
          </button>
          );
        })}
      </div>
      <div className="region-legend">
        <span>
          {plots.length} {plots.length === 1 ? 'plot' : 'plots'} surveyed on {islandsFor(chart).length} islands
        </span>
        <span>{plots.length ? 'Tap a marker to inspect the land' : 'Nothing here has been surveyed yet'}</span>
      </div>
    </div>
  );
}

export default function PlotSelect({ player, onPlayer, onEnter, onVisit }: {
  player: PlayerRecord;
  onPlayer: (record: PlayerRecord) => void;
  onEnter: (world: ClaimedWorld) => void;
  /** Go and look at somebody else's settlement. Resolves to a refusal, or null. */
  onVisit: (seed: number) => Promise<string | null>;
}) {
  const [chart, setChart] = useState(HOME_CHART_INDEX);
  const [selectedSeed, setSelectedSeed] = useState<number | null>(null);
  const [name, setName] = useState('');
  const { wallet } = useWallet();
  const [claiming, setClaiming] = useState(false);
  const [surveying, setSurveying] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  // On a phone the map and the claim panel cannot both be on screen, so the
  // panel becomes a sheet that the map opens.
  const [sheetOpen, setSheetOpen] = useState(false);
  const configured = tokenLive();

  const { claims: allClaims, finds, shared: registryShared, setClaims, setFinds } = useAllClaims();
  // Everybody's discoveries, in the shape the world model wants them.
  const discovered = useMemo(
    () => finds.map((f) => ({ seed: f.seed, chart: f.chart, slot: f.slot })),
    [finds],
  );
  const plots = useMemo(() => marketPlots(player, chart, discovered), [player, chart, discovered]);
  const room = useMemo(() => chartRoom(player, chart, discovered), [player, chart, discovered]);
  const selected: Plot | null = plots.find((p) => p.seed === selectedSeed) ?? plots[0] ?? null;
  const registry = useChainOwner(selected?.seed ?? null);
  // What the claim will actually cost: the contract's number where there is a
  // contract, and the game's own otherwise.
  const price = useChainPrice(selected?.seed ?? null, selected?.price ?? 0);
  const explorer = selected ? plotExplorerUrl(selected.seed) : null;
  /*
   * Land this wallet holds according to the registry, whatever this browser
   * remembers.
   *
   * Without it, a player who cleared their site data or picked up a different
   * device would find their own plot on the market and be charged for it a
   * second time — the browser's record is a cache, and the registry is the
   * title. This is what makes ownership belong to the wallet rather than to
   * the machine it was claimed from.
   */
  const mineBySeed = useMemo(() => {
    const map = new Map<number, Claim>();
    if (!wallet.address) return map;
    const me = wallet.address.toLowerCase();
    for (const claim of allClaims) {
      if (claim.owner.toLowerCase() === me) map.set(claim.seed, claim);
    }
    return map;
  }, [allClaims, wallet.address]);

  const ownedSeeds = useMemo(
    () => new Set([...player.claims.map((c) => c.seed), ...mineBySeed.keys()]),
    [player.claims, mineBySeed],
  );
  const [visiting, setVisiting] = useState(false);

  /*
   * Who holds what, minus this player's own land.
   *
   * Compared by address, not by whether the seed appears in this browser's
   * record: a player who cleared their site data still owns their plots, and
   * should be shown them as theirs rather than as somebody else's.
   */
  const takenByOthers = useMemo(() => {
    const map = new Map<number, Claim>();
    for (const claim of allClaims) {
      const mine = wallet.address && claim.owner.toLowerCase() === wallet.address.toLowerCase();
      if (!mine) map.set(claim.seed, claim);
    }
    return map;
  }, [allClaims, wallet.address]);

  const heldByOther = selected ? takenByOthers.get(selected.seed) ?? null : null;

  /*
   * The world this player owns here, if any.
   *
   * This browser's own record first, since it carries the transaction hash and
   * the name they chose; the registry's row second, for a wallet arriving on a
   * machine that has never seen this plot. Everything the panel says about
   * ownership reads from this rather than from local storage alone.
   */
  const mine: ClaimedWorld | null = useMemo(() => {
    if (!selected) return null;
    const local = claimOf(player, selected.seed);
    if (local) return local;
    const row = mineBySeed.get(selected.seed);
    return row
      ? {
          seed: row.seed, name: row.worldName, region: row.region, price: row.price,
          claimedAt: row.at, owner: row.owner, txHash: null,
        }
      : null;
  }, [selected, player, mineBySeed]);

  const choose = useCallback((plot: Plot) => {
    setSelectedSeed(plot.seed);
    setSheetOpen(true);
  }, []);

  /**
   * Pay to find new land.
   *
   * The registry picks the berth, because it is the only party that can see
   * every plot already surveyed on this chart. A client choosing for itself
   * could only avoid the ones it knew about, so two players prospecting the
   * same chart took the same slot and put two settlements on one point of the
   * map — each invisible to the other. The fee is charged only after the
   * registry has actually handed over land.
   */
  const prospect = useCallback(async () => {
    if (!wallet.address) {
      setNotice('Connect a wallet first. Land you survey is recorded against your address.');
      return;
    }
    if (player.ledger.balance < PROSPECT_COST_EMERGE) {
      setNotice(`Prospecting costs ${PROSPECT_COST_EMERGE.toLocaleString()} ${TOKEN.ticker}.`);
      return;
    }
    setSurveying(true);
    setNotice(null);

    /*
     * Pay first, then ask for the land.
     *
     * The server will not survey anything without a burn it has read off the
     * chain, so the order has to be this way round — and it means a dismissed
     * wallet prompt costs the player nothing and gets them nothing, rather than
     * getting them land they did not pay for.
     */
    const paid = await spend(player.ledger, PROSPECT_COST_EMERGE, wallet.address);
    if (!paid.ok) { setSurveying(false); setNotice(paid.refused); return; }
    onPlayer({ ...player, ledger: paid.ledger });

    setNotice('Payment sent. Waiting for the chain to settle it…');
    const result = await whileSettling(() => surveyPlot({
      chart,
      capacity: chartCapacity(chart),
      owner: wallet.address!,
      ownerName: player.name,
      burnTx: paid.txHash ?? undefined,
    }));
    setSurveying(false);
    if (!result.ok) {
      // The tokens are gone and the land is not. Say so plainly rather than
      // leaving somebody to work it out from a balance.
      setNotice(paid.txHash
        ? `${result.reason} Your payment ${paid.txHash.slice(0, 10)}… was accepted by the chain — keep it, and tell us if the land never arrives.`
        : `${result.reason} Sail to another chart to find new land.`);
      return;
    }

    const { find } = result;
    const found = inspectPlot(find.seed, find.slot, find.chart);
    setFinds((held) => [...held.filter((f) => f.seed !== find.seed), find]);
    onPlayer({
      ...player,
      ledger: paid.ledger,
      prospected: [...player.prospected, { seed: find.seed, chart: find.chart, slot: find.slot }],
    });
    setSelectedSeed(find.seed);
    setSheetOpen(true);
    setNotice(`Surveyed ${found.region} on ${found.island} — ${found.biomeLabel.toLowerCase()}. Everyone can see it now.`);
  }, [player, chart, onPlayer, wallet.address, setFinds]);

  const sail = useCallback((delta: number) => {
    setChart((c) => (c + delta + CHART_COUNT) % CHART_COUNT);
    setSelectedSeed(null);
    setSheetOpen(false);
    setNotice(null);
  }, []);

  /**
   * Take a plot.
   *
   * Three things have to be true, and the order matters. A wallet must be
   * connected, because a plot belongs to an address and everything the player
   * owns is keyed by it. The claim has to be accepted — by the contract where
   * one is deployed, otherwise by the shared relay — and a refusal there is
   * final: falling back to "claim it locally anyway" is exactly the bug this
   * exists to fix. Only then is the price charged, so a refused claim never
   * costs anything.
   *
   * With the registry deployed the contract does both at once: it takes
   * payment, burns it, and mints the title in the same transaction, so there is
   * no moment where a player has paid and does not own the land. The relay is
   * written afterwards as a cache, and a relay that is down costs nothing
   * because the plot is already theirs on chain.
   */
  const claim = useCallback(async () => {
    if (!selected) return;
    const other = takenByOthers.get(selected.seed);
    // The registry outranks this browser's memory of what it owns.
    if (other) {
      setNotice(`${selected.region} already belongs to ${other.ownerName || shortAddress(other.owner)}.`);
      return;
    }
    // Already yours — by this browser's record or the registry's. Either way
    // this is the door back in, not a second purchase.
    if (mine) { onEnter(mine); return; }
    if (!wallet.address) {
      setNotice('Connect a wallet first. A plot belongs to an address, and so does everything you earn on it.');
      return;
    }
    if (player.ledger.balance < price) {
      setNotice(`${selected.region} costs ${price.toLocaleString()} ${TOKEN.ticker}.`);
      return;
    }

    setClaiming(true);
    setNotice(null);
    const worldName = name.trim() || defaultWorldName(selected.seed);

    if (onChainClaimsLive()) {
      setNotice('Approve the spend, then confirm the claim. Two signatures, and the second one is the title.');
      const minted = await claimOnChain(wallet.address, selected.seed, worldName);
      setClaiming(false);
      if (!minted.ok) { setNotice(minted.message); return; }

      const charged = minted.price ?? price;
      onPlayer({ ...player, ledger: await settleBurn(player.ledger, charged, wallet.address) });

      // Cache it in the relay so the map, chat and visitor list have a name and
      // a date to show. The chain already holds the title, so a relay that
      // refuses this changes nothing about who owns the land.
      await takePlot({
        seed: selected.seed,
        region: selected.region,
        worldName,
        owner: wallet.address,
        ownerName: player.name,
        price: charged,
      });

      onEnter({
        seed: selected.seed,
        name: worldName,
        region: selected.region,
        price: charged,
        claimedAt: Date.now(),
        owner: wallet.address,
        txHash: minted.txHash,
      });
      return;
    }

    /*
     * Hold the plot, pay for it, then claim it with the receipt.
     *
     * Three steps in this order for three reasons. The hold means a refusal
     * arrives before any money moves, so nobody burns tokens for land somebody
     * else is taking. The payment comes second because the server will not
     * write a title without a burn it has read off the chain — this is what the
     * land contract used to guarantee by taking payment and minting in one
     * transaction, and with no contract deployed it has to be reconstructed out
     * of two steps and a receipt. And the claim comes last, so the row that
     * says who owns this land is only ever written against a payment that
     * really happened.
     */
    const reserved = await reservePlot(selected.seed, wallet.address);
    if (!reserved.ok) {
      setClaiming(false);
      setNotice(reserved.reason);
      return;
    }

    const paid = await spend(player.ledger, price, wallet.address);
    if (!paid.ok) {
      setClaiming(false);
      setNotice(paid.refused ?? `Not enough ${TOKEN.ticker} to claim ${selected.region}.`);
      return;
    }
    onPlayer({ ...player, ledger: paid.ledger });

    setNotice('Payment sent. Waiting for the chain to settle it…');
    const registered = await whileSettling(() => takePlot({
      seed: selected.seed,
      region: selected.region,
      worldName,
      owner: wallet.address!,
      ownerName: player.name,
      price,
      burnTx: paid.txHash ?? undefined,
    }));
    setClaiming(false);

    if (!registered.ok) {
      setNotice(paid.txHash
        ? `${registered.reason} Your payment ${paid.txHash.slice(0, 10)}… went through — keep it, and tell us if the land never arrives.`
        : registered.reason);
      // Show the land as theirs straight away rather than making the player
      // wait for the next poll to understand why they were refused.
      if (registered.taken?.owner) {
        setClaims((held2) => [...held2.filter((c) => c.seed !== registered.taken!.seed), registered.taken!]);
      }
      return;
    }

    onEnter({
      seed: selected.seed,
      name: worldName,
      region: selected.region,
      price,
      claimedAt: Date.now(),
      owner: wallet.address,
      txHash: paid.txHash,
    });
  }, [name, selected, price, wallet.address, onEnter, onPlayer, player, takenByOthers, mineBySeed, setClaims]);

  /** Go and look at the settlement somebody else built here. */
  const visit = useCallback(async (seed: number) => {
    setVisiting(true);
    setNotice(null);
    const refused = await onVisit(seed);
    setVisiting(false);
    if (refused) setNotice(refused);
  }, [onVisit]);

  const unlist = useCallback((seed: number) => {
    onPlayer({ ...player, listings: player.listings.filter((l) => l.seed !== seed) });
  }, [player, onPlayer]);


  return (
    <main className="world-map">
      <div className="land-inner">
        <header className="land-head">
          <BrandLine />
          <p className="land-intro">
            Every plot is a world waiting to happen, and no two are the same land. Claim one with
            {' '}{TOKEN.ticker}, give it a name, and the beings who live there will call it that.
          </p>
          <div className="land-head-side">
            <div className="land-balance">
              <span>YOUR BALANCE</span>
              <b>{Math.floor(player.ledger.balance).toLocaleString()}</b>
              <em>{TOKEN.ticker}</em>
            </div>
            <button
              className="ghost prospect"
              onClick={prospect}
              disabled={surveying || !wallet.address || player.ledger.balance < PROSPECT_COST_EMERGE || room.free === 0}
            >
              {surveying
                ? 'Surveying…'
                : room.free === 0
                  ? 'This chart is fully surveyed'
                  : !wallet.address
                    ? 'Connect a wallet to survey'
                    : `Prospect new land · ${PROSPECT_COST_EMERGE.toLocaleString()} ${TOKEN.ticker}`}
            </button>
          </div>
        </header>

        {/* Where in the world you are looking. Each chart holds a fixed number
            of plots; when it is full the only way to new land is to sail. */}
        <nav className="charts">
          <button className="ghost" onClick={() => sail(-1)} aria-label="Previous chart">‹</button>
          <div className="chart-name">
            <b>{chartName(chart)}</b>
            <em>
              {room.used} of {room.capacity} plots surveyed
              {room.free === 0 ? ' · nothing left to find here' : ` · room for ${room.free} more`}
            </em>
          </div>
          <button className="ghost" onClick={() => sail(1)} aria-label="Next chart">›</button>
        </nav>

        <div className="land-body">
          <RegionMap plots={plots} selected={selected} chart={chart} owned={ownedSeeds} taken={takenByOthers} onSelect={choose} />

          {!selected ? (
            <aside className="land-claim empty">
              <span className="eyebrow">UNSURVEYED</span>
              <h2>{chartName(chart)}</h2>
              <p className="muted">
                Nobody has set foot on these islands. There is room for {room.capacity} settlements out
                here; survey one to see what the land is made of.
              </p>
              <button
                className="claim-button"
                onClick={prospect}
                disabled={surveying || !wallet.address || player.ledger.balance < PROSPECT_COST_EMERGE}
              >
                {surveying
                  ? 'Surveying…'
                  : !wallet.address
                    ? 'Connect a wallet to survey'
                    : `Survey a plot · ${PROSPECT_COST_EMERGE.toLocaleString()} ${TOKEN.ticker}`}
              </button>
              {notice && <p className="warn">{notice}</p>}
            </aside>
          ) : (
          <aside className={`land-claim ${sheetOpen ? 'open' : ''}`}>
            <button className="sheet-close" onClick={() => setSheetOpen(false)} aria-label="Back to the map">×</button>
            {/* The registry decides, not this browser's memory. A stale local
                claim on land somebody else now holds must read as theirs. */}
            <span className="eyebrow">{heldByOther ? 'SETTLED' : mine ? 'YOUR WORLD' : 'CLAIM'}</span>
            <h2>{heldByOther ? heldByOther.worldName : mine ? mine.name : selected.region}</h2>
            <div className="plot-traits">
              <span className={`biome-tag ${selected.biome}`}>{selected.biomeLabel}</span>
              <span>{selected.island}</span>
              <span>{selected.population} beings</span>
              {mine && !heldByOther && <span className="owned-tag">Yours</span>}
              {heldByOther && <span className="settled-tag-big">Taken</span>}
            </div>
            {mine && !heldByOther && (
              <p className="muted small">
                Claimed {new Date(mine.claimedAt).toLocaleDateString()} for {mine.price.toLocaleString()} {TOKEN.ticker}
                {mine.owner ? ` by ${shortAddress(mine.owner)}` : ' with no wallet connected'}.
                {mine.txHash ? ` Paid on chain: ${mine.txHash}.` : ''}
              </p>
            )}
            {/* Who else holds this land. */}
            {heldByOther && (
              <div className="settled-by">
                <p className="muted small">
                  Settled by <b>{heldByOther.ownerName || shortAddress(heldByOther.owner)}</b>
                  {' '}on {new Date(heldByOther.at).toLocaleDateString()}, and called
                  {' '}<b>{heldByOther.worldName}</b>.
                </p>
                <button className="ghost" onClick={() => visit(heldByOther.seed)} disabled={visiting}>
                  {visiting ? 'Travelling…' : `Visit ${heldByOther.worldName}`}
                </button>
              </div>
            )}
            {registry?.onChain && registry.owner && !mine && !heldByOther && (
              <p className="muted small">
                Held on {ACTIVE_CHAIN.label} by <b>{shortAddress(registry.owner)}</b>.
              </p>
            )}
            {/* The title itself, for anybody who would rather check than be
                told. It is an ordinary ERC-721 token whose id is this plot's
                seed, so an explorer can read it without going through us. */}
            {onChainClaimsLive() && explorer && (
              <p className="muted small">
                <a href={explorer} target="_blank" rel="noreferrer noopener">
                  Verify this plot on {ACTIVE_CHAIN.label}
                </a>{' '}— token #{selected.seed} of the Emerge Land registry.
              </p>
            )}
            {!registryShared && !mine && (
              <p className="muted small">
                This build has no shared registry behind it, so the only claims on this map are the ones
                made in this browser. Other players&rsquo; land will not show until one is configured.
              </p>
            )}

            <PlotPreview seed={selected.seed} />
            <p className="muted">{selected.blurb}</p>

            <span className="eyebrow">TRADES THIS LAND SUPPORTS</span>
            <div className="plot-traits">
              {selected.trades.map((t) => <span key={t}>{t}</span>)}
            </div>

            {!mine && (
              <label className="name-field">
                <span>NAME YOUR WORLD</span>
                <input
                  value={name}
                  maxLength={24}
                  placeholder={defaultWorldName(selected.seed)}
                  onChange={(e) => setName(e.target.value)}
                />
              </label>
            )}

            <div className="claim-price">
              <span>{mine ? 'PAID' : 'PRICE'}</span>
              <b>{(mine ? mine.price : price).toLocaleString()}</b>
              <em>{TOKEN.ticker}</em>
            </div>

            <div className="claim-wallet"><WalletPicker compact /></div>

            <button
              className="claim-button"
              onClick={() => (heldByOther ? visit(heldByOther.seed) : claim())}
              disabled={
                claiming || visiting
                || (!mine && !heldByOther && !wallet.address)
                || (!mine && !heldByOther && player.ledger.balance < price)
              }
            >
              {claiming
                ? 'Claiming…'
                : heldByOther
                  ? (visiting ? 'Travelling…' : `Visit ${heldByOther.worldName}`)
                  : mine
                    ? `Enter ${mine.name}`
                    : !wallet.address
                      ? 'Connect a wallet to claim land'
                      : player.ledger.balance < price
                        ? `Not enough ${TOKEN.ticker}`
                        : `Claim ${selected.region} · ${price.toLocaleString()} ${TOKEN.ticker}`}
            </button>
            {!wallet.address && !mine && !heldByOther && (
              <p className="muted small">
                Your plots, your balance and your name all belong to a wallet address rather than to this
                browser, so there is nothing for a claim to belong to until one is connected.
              </p>
            )}

            {player.claims.length > 0 && (
              <>
                <span className="eyebrow">WORLDS YOU OWN</span>
                <div className="listing-list">
                  {[...player.claims].sort((a, b) => a.claimedAt - b.claimedAt).map((c, i) => (
                    <div key={c.seed} className={`listing-row ${c.seed === selected.seed ? 'here' : ''}`}>
                      <span>{c.name}{i >= EARNING_PLOT_LIMIT && <i className="idle-plot">not earning</i>}</span>
                      <b>{c.region}</b>
                      <button className="ghost" onClick={() => onEnter(c)}>Enter</button>
                    </div>
                  ))}
                </div>
                {player.claims.length > EARNING_PLOT_LIMIT && (
                  <p className="muted small">
                    The first {EARNING_PLOT_LIMIT} worlds you claimed earn {TOKEN.ticker}; the rest are
                    yours to play with. Give one up and the next in line starts earning.
                  </p>
                )}
              </>
            )}

            {player.listings.length > 0 && (
              <>
                <span className="eyebrow">YOUR LISTINGS</span>
                <div className="listing-list">
                  {player.listings.map((listing) => (
                    <div key={listing.seed} className="listing-row">
                      <span>{listing.region}</span>
                      <b>{listing.price.toLocaleString()} {TOKEN.ticker}</b>
                      <button className="ghost" onClick={() => unlist(listing.seed)}>Withdraw</button>
                    </div>
                  ))}
                </div>
                <p className="muted small">
                  {onChainClaimsLive()
                    ? `A plot is an ordinary ERC-721 token, so it sells anywhere that handles them — wallet to wallet, or on any marketplace on ${ACTIVE_CHAIN.label}. A listing here is a note to yourself until this game carries a marketplace of its own.`
                    : `Resale between players needs the plot registry on ${ACTIVE_CHAIN.label}. Until it is deployed a listing is recorded in this browser and no one else can see it.`}
                </p>
              </>
            )}

            {onChainClaimsLive() ? (
              <p className="muted small">
                This is real ownership. The price above is read from the land contract, so it is the
                price the transaction enforces; claiming mints token #{selected.seed} of the Emerge
                Land registry to your address and burns what it cost inside the same transaction.
                Nobody, this game included, can move a plot out of the wallet holding it.
              </p>
            ) : configured ? (
              <p className="muted small">
                Prices are real. Your balance is read from your wallet on {ACTIVE_CHAIN.label}, and
                claiming asks you to sign a transfer that destroys the {TOKEN.ticker} it costs.
                Ownership is recorded in the shared registry until the land contract is deployed,
                so a claim is enforced for every player but is not yet an on-chain title.
              </p>
            ) : (
              <p className="muted small">
                This build talks to {ACTIVE_CHAIN.label} (chain {ACTIVE_CHAIN.chainId}), but the
                {' '}{TOKEN.ticker} contract is not deployed there yet, so claims are recorded in the shared
                registry rather than on chain and you start with a local development allocation of
                {' '}{LOCAL_TEST_ALLOCATION.toLocaleString()} {TOKEN.ticker}. Neither is a token transfer.
              </p>
            )}
            {notice && <p className="warn">{notice}</p>}
          </aside>
          )}
        </div>
      </div>
    </main>
  );
}
