export type Terrain='fertile'|'forest'|'mountain'|'rocky'|'coastal'|'river';
export type Job='farmer'|'woodcutter'|'miner'|'quarry'|'miller'|'baker'|'carpenter'|'blacksmith'|'tailor'|'unemployed';
export type WorkingJob=Exclude<Job,'unemployed'>;
export type Activity='walking'|'working'|'resting'|'trading'|'eating'|'idle';
export type Season='Spring'|'Summer'|'Autumn'|'Winter';
export type Weather='Clear'|'Cloudy'|'Rain'|'Storm'|'Fog'|'Snow';
export type Resource='wheat'|'vegetables'|'wood'|'stone'|'ironOre'|'wool'|'flour'|'bread'|'furniture'|'tools'|'clothing';
export interface Citizen{id:string;name:string;familyId:string;age:number;job:Job;hunger:number;rest:number;social:number;clothing:number;purpose:number;happiness:number;wage:number;wallet:number;x:number;y:number;activity:Activity;targetBuildingId?:string;inside:boolean;}
export interface Family{id:string;name:string;members:string[];homeId:string;wealth:number;}
export interface Building{id:string;type:string;x:number;y:number;workers:string[];active:boolean;production?:string;}
export interface MarketQuote{price:number;supply:number;demand:number;volume:number;trend:number;}
export interface World{id:string;seed:number;day:number;hour:number;terrain:Terrain[];season:Season;weather:Weather;weatherSeed:number;treasury:number;population:number;families:Family[];citizens:Citizen[];buildings:Building[];resources:Record<Resource,number>;market:Record<Resource,MarketQuote>;lastEvents:string[];}
export const RESOURCE_LABELS:Record<Resource,string>={wheat:'Wheat',vegetables:'Vegetables',wood:'Wood',stone:'Stone',ironOre:'Iron Ore',wool:'Wool',flour:'Flour',bread:'Bread',furniture:'Furniture',tools:'Tools',clothing:'Clothing'};
export const JOB_LABELS:Record<Job,string>={farmer:'Farmer',woodcutter:'Woodcutter',miner:'Miner',quarry:'Quarry worker',miller:'Miller',baker:'Baker',carpenter:'Carpenter',blacksmith:'Blacksmith',tailor:'Tailor',unemployed:'Unemployed'};
export const ACTIVITY_LABELS:Record<Activity,string>={walking:'Walking',working:'Working',resting:'At home',trading:'Socializing',eating:'Eating',idle:'Idle'};
const jobs:Record<WorkingJob,{wage:number;output:Partial<Record<Resource,number>>;input?:Partial<Record<Resource,number>>;building:string}>={farmer:{wage:10,output:{wheat:10,vegetables:5},building:'Farm'},woodcutter:{wage:11,output:{wood:12.5},building:'Woodcutter'},miner:{wage:14,output:{ironOre:3.33},building:'Mine'},quarry:{wage:12,output:{stone:9},building:'Quarry'},miller:{wage:13,output:{flour:10},input:{wheat:10},building:'Mill'},baker:{wage:15,output:{bread:10},input:{flour:10,wood:2.5},building:'Bakery'},carpenter:{wage:15,output:{furniture:5},input:{wood:10},building:'Carpenter'},blacksmith:{wage:18,output:{tools:4},input:{ironOre:8,wood:4},building:'Blacksmith'},tailor:{wage:16,output:{clothing:4},input:{wool:4},building:'Tailor'}};
const names=['Avery','Carter','Maya','Noah','Elena','Theo','Iris','Miles','Lena','Jonah','Ruby','Owen','Nora','Eli','Clara','Finn','Milo','June','Ada','Leo','Mae','Sam','Wren','Kai','Rose','Jack','Lily','Ben','Anna','Max'];
const familyNames=['Carter','Mason','Hayes','Bennett','Reed','Morgan','Brooks','Parker'];
const marketPrices:Record<Resource,number>={wheat:2,vegetables:2.5,wood:3,stone:4,ironOre:7,wool:6,flour:5,bread:7,furniture:14,tools:20,clothing:18};
const marketBuffers:Record<Resource,number>={wheat:60,vegetables:40,wood:70,stone:30,ironOre:20,wool:15,flour:25,bread:40,furniture:10,tools:8,clothing:15};
const terrainBonuses:Record<Terrain,Partial<Record<WorkingJob,number>>>= {fertile:{farmer:1.3},forest:{woodcutter:1.3},mountain:{miner:1.3},rocky:{quarry:1.25},coastal:{},river:{farmer:1.15}};
const roadNodes:[number,number][]=[[29,24],[50,24],[66,24],[50,46],[28,46],[20,72],[50,72],[70,82],[84,72]];
const roadEdges:number[][]=[[1],[0,2,3],[1,8],[1,4,6],[3,5,6],[4,6],[3,4,5,7],[6,8],[7,2]];
export function mulberry32(seed:number){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function createMarket():Record<Resource,MarketQuote>{return Object.fromEntries((Object.keys(marketPrices) as Resource[]).map(r=>[r,{price:marketPrices[r],supply:0,demand:0,volume:0,trend:0}])) as Record<Resource,MarketQuote>;}
function seasonForDay(day:number):Season{const n=(day-1)%120;return n<30?'Spring':n<60?'Summer':n<90?'Autumn':'Winter';}
function weatherFor(season:Season,seed:number,day:number):Weather{const r=mulberry32(seed+day*71)();if(season==='Winter')return r<.42?'Snow':r<.64?'Cloudy':r<.73?'Fog':'Clear';if(season==='Spring')return r<.25?'Rain':r<.42?'Cloudy':r<.48?'Fog':'Clear';if(season==='Autumn')return r<.2?'Rain':r<.42?'Cloudy':r<.5?'Fog':'Clear';return r<.15?'Storm':r<.3?'Rain':r<.5?'Cloudy':'Clear';}
function chooseJobFromSeed(terrain:Terrain[],n:number):WorkingJob{const a:WorkingJob[]=['farmer','woodcutter','miner','quarry','miller','baker','carpenter','blacksmith','tailor'];return a[Math.abs(n+terrain.reduce((s,t)=>s+t.length,0))%a.length];}
export function createWorld(seed=481516):World{const rand=mulberry32(seed);const terrain=Array.from({length:3},()=> (['fertile','forest','mountain','rocky','coastal','river'] as Terrain[])[Math.floor(rand()*6)]);const count=20+Math.floor(rand()*11);const families:Family[]=[];const citizens:Citizen[]=[];for(let i=0;i<Math.ceil(count/4);i++){const id=`f${i}`;families.push({id,name:familyNames[i%familyNames.length],members:[],homeId:`h${i}`,wealth:80+Math.floor(rand()*80)});}for(let i=0;i<count;i++){const family=families[i%families.length];const age=i%5===0?8+Math.floor(rand()*8):18+Math.floor(rand()*42);const citizen:Citizen={id:`c${i}`,name:names[i%names.length],familyId:family.id,age,job:age>=16?chooseJobFromSeed(terrain,i):'unemployed',hunger:82+rand()*18,rest:72+rand()*28,social:60+rand()*40,clothing:72+rand()*28,purpose:55+rand()*45,happiness:78,wage:0,wallet:45+Math.floor(rand()*55),x:12+Math.floor(rand()*76),y:12+Math.floor(rand()*76),activity:'idle',inside:false};citizens.push(citizen);family.members.push(citizen.id);}const buildings:Building[]=[{id:'bank',type:'Bank',x:24,y:24,workers:[],active:true},{id:'market',type:'Market',x:29,y:24,workers:[],active:true},{id:'storage',type:'Storage',x:34,y:24,workers:[],active:true},{id:'tavern',type:'Tavern',x:42,y:43,workers:[],active:true}];families.forEach((f,i)=>buildings.push({id:f.homeId,type:'House',x:20+(i%4)*5,y:34+Math.floor(i/4)*6,workers:[],active:true}));return{id:`world-${seed.toString(36)}`,seed,day:1,hour:8,terrain,season:'Spring',weather:weatherFor('Spring',seed,1),weatherSeed:seed,treasury:1000,population:count,families,citizens,buildings,resources:{wheat:60,vegetables:30,wood:50,stone:20,ironOre:10,wool:8,flour:0,bread:20,furniture:0,tools:5,clothing:10},market:createMarket(),lastEvents:['Your world has emerged.','Families are settling into their homes.','The market is open and trade has begun.']};}
function nearestRoad(x:number,y:number){let best=0,dist=Infinity;for(let i=0;i<roadNodes.length;i++){const n=roadNodes[i],d=(n[0]-x)**2+(n[1]-y)**2;if(d<dist){dist=d;best=i;}}return best;}
function roadDistance(a:number,b:number){return Math.hypot(roadNodes[a][0]-roadNodes[b][0],roadNodes[a][1]-roadNodes[b][1]);}
function roadPath(start:number,end:number){if(start===end)return [start];const open=[start],came=new Map<number,number>(),g=new Map<number,number>([[start,0]]),f=new Map<number,number>([[start,roadDistance(start,end)]]);while(open.length){open.sort((a,b)=>(f.get(a)??Infinity)-(f.get(b)??Infinity));const current=open.shift()!;if(current===end){const path=[current];let cursor=current;while(came.has(cursor)){cursor=came.get(cursor)!;path.unshift(cursor);}return path;}for(const next of roadEdges[current]){const score=(g.get(current)??Infinity)+roadDistance(current,next);if(score<(g.get(next)??Infinity)){came.set(next,current);g.set(next,score);f.set(next,score+roadDistance(next,end));if(!open.includes(next))open.push(next);}}}return [start,end];}
function jobBuilding(world:World,c:Citizen){if(c.job==='unemployed')return undefined;const job=jobs[c.job];return world.buildings.find(b=>b.type===job.building);}
function moveCitizens(world:World,hours:number){const rand=mulberry32(world.seed+world.day*997+Math.floor(world.hour*17));const market=world.buildings.find(b=>b.type==='Market');for(const c of world.citizens){const home=world.buildings.find(b=>b.id===world.families.find(f=>f.id===c.familyId)?.homeId);if(c.age<16)c.job='unemployed';const night=world.hour>=21||world.hour<6;const socialTime=world.hour>=18&&world.hour<21;let target=home,activity:Activity='idle';if(c.hunger<48&&market){target=market;activity='eating';}else if(night&&home){target=home;activity='resting';}else if(socialTime&&world.buildings.find(b=>b.type==='Tavern')){target=world.buildings.find(b=>b.type==='Tavern');activity='trading';}else{target=jobBuilding(world,c)||market;activity=c.job==='unemployed'?'idle':'working';}c.targetBuildingId=target?.id;c.inside=false;const dist=target?Math.hypot(target.x-c.x,target.y-c.y):0;const speed=(c.age<16?4.5:7.5)*hours;if(target&&dist>2.5){const start=nearestRoad(c.x,c.y),end=nearestRoad(target.x,target.y),path=roadPath(start,end);const onRoad=Math.hypot(roadNodes[start][0]-c.x,roadNodes[start][1]-c.y)<9;let tx=target.x,ty=target.y;if(path.length>1&&onRoad){const next=path[1];tx=roadNodes[next][0];ty=roadNodes[next][1];}else if(path.length>1&&dist>10){tx=roadNodes[start][0];ty=roadNodes[start][1];}const dx=tx-c.x,dy=ty-c.y,d=Math.hypot(dx,dy)||1,step=Math.min(d,speed);c.x=Math.max(4,Math.min(96,c.x+dx/d*step));c.y=Math.max(6,Math.min(94,c.y+dy/d*step));c.activity='walking';}else{if(target){c.x=target.x+(rand()-.5)*1.5;c.y=target.y+(rand()-.5)*1.5;}c.activity=activity;c.inside=!!target&&(activity==='working'||activity==='resting'||activity==='trading'||activity==='eating');}if(c.activity==='trading'&&c.wallet>4&&rand()>.35)c.wallet-=2;}}
function updateBuildingWorkers(world:World){for(const b of world.buildings){b.workers=[];b.production=undefined;}for(const c of world.citizens){if(!c.targetBuildingId)continue;const b=world.buildings.find(x=>x.id===c.targetBuildingId);if(b&&c.inside&&(c.activity==='working'||c.activity==='trading'||c.activity==='resting')){if(b.workers.length<8)b.workers.push(c.id);if(c.activity==='working')b.production=c.job;}}}
function householdTrade(world:World):string[]{const events:string[]=[];for(const c of world.citizens){if(c.age<16||c.hunger>62||c.wallet<1)continue;const r=(['bread','wheat','vegetables'] as Resource[]).find(x=>world.resources[x]>=1);if(!r)continue;const price=world.market[r].price;if(c.wallet>=price){c.wallet-=price;world.treasury+=price;world.resources[r]-=1;c.hunger=Math.min(100,c.hunger+18);c.activity='eating';events.push(`${c.name} bought ${RESOURCE_LABELS[r].toLowerCase()} at the market.`);}}return events;}
function marketStep(world:World,hours:number){const events:string[]=[];for(const r of Object.keys(marketPrices) as Resource[]){const q=world.market[r],stock=world.resources[r],buffer=marketBuffers[r],scarcity=Math.max(-1.5,Math.min(1.5,(buffer-stock)/Math.max(buffer,1))),old=q.price;q.price=Math.max(.5,Math.min(100,q.price*(1+scarcity*.025*hours)));q.supply=Math.max(0,stock-buffer);q.demand=Math.max(0,buffer-stock);q.volume=0;q.trend=q.price-old;if(stock<buffer*.65){const qty=Math.min(Math.max(1,Math.ceil((buffer-stock)*.05*hours)),Math.max(0,buffer-stock)),cost=qty*q.price;if(qty>0&&world.treasury>=cost){world.resources[r]+=qty;world.treasury-=cost;q.volume+=qty;if(qty>=2)events.push(`Market bought ${qty} ${RESOURCE_LABELS[r]} for ${cost.toFixed(0)} Gold.`);}}else if(stock>buffer*1.45){const qty=Math.min(Math.max(1,Math.ceil((stock-buffer)*.035*hours)),stock-buffer);if(qty>0){const revenue=qty*q.price;world.resources[r]-=qty;world.treasury+=revenue;q.volume+=qty;if(qty>=2)events.push(`Market sold ${qty} ${RESOURCE_LABELS[r]} for ${revenue.toFixed(0)} Gold.`);}}}events.push(...householdTrade(world).slice(0,2));if(events.length)world.lastEvents=[...events.slice(0,4),...world.lastEvents].slice(0,10);}
function daily(world:World){const events:string[]=[];let wageCost=0;for(const c of world.citizens){if(c.age<16){c.job='unemployed';c.wage=0;continue;}const need=Math.min(c.hunger,c.rest,c.social,c.clothing,c.purpose);let jobKey:WorkingJob=c.job==='unemployed'?chooseJob(world,c):c.job;if(need<35)jobKey=chooseJob(world,c);c.job=jobKey;const job=jobs[jobKey];c.wage=job.wage;wageCost+=c.wage;c.wallet+=c.wage;c.hunger=Math.max(0,c.hunger-7);c.rest=Math.max(0,c.rest-5);c.social=Math.max(0,c.social-2);c.clothing=Math.max(0,c.clothing-1);c.purpose=Math.min(100,c.purpose+.5);}produce(world,events);consume(world,events);world.treasury=Math.max(0,world.treasury-wageCost-world.buildings.filter(b=>b.active).reduce((s,b)=>s+maintenance(b.type),0));for(const f of world.families)f.wealth=world.citizens.filter(c=>c.familyId===f.id).reduce((s,c)=>s+c.wallet,0);world.lastEvents=[...events,...world.lastEvents].slice(0,10);world.population=world.citizens.length;}
function chooseJob(world:World,_c:Citizen):WorkingJob{const a:WorkingJob[]=['farmer','woodcutter','miner','quarry','miller','baker','carpenter','blacksmith','tailor'];return a.map(j=>({j,s:jobScore(world,j)})).sort((a,b)=>b.s-a.s)[0].j;}
function jobScore(world:World,j:WorkingJob){const spec=world.terrain.map(t=>terrainBonuses[t][j]||1).reduce((a,b)=>a+b,0)/world.terrain.length;const demand=j==='farmer'?(world.resources.wheat+world.resources.vegetables<100?2:1):j==='woodcutter'?(world.resources.wood<100?2:1):j==='miner'?(world.resources.ironOre<40?2:1):1;return spec*demand;}
function produce(world:World,events:string[]){const counts:Partial<Record<Job,number>>={};for(const c of world.citizens)counts[c.job]=(counts[c.job]||0)+1;for(const [job,count] of Object.entries(counts)){if(!job||job==='unemployed'||!count)continue;const workingJob=job as WorkingJob;const recipe=jobs[workingJob],workers=Math.min(count,workingJob==='miner'?3:2),seasonal=world.season==='Winter'&&workingJob==='farmer'?.65:world.season==='Summer'&&workingJob==='farmer'?1.15:1,weather=world.weather==='Storm'?.65:world.weather==='Rain'&&workingJob==='farmer'?1.08:world.weather==='Snow'?.7:1,canInput=!recipe.input||Object.entries(recipe.input).every(([r,n])=>world.resources[r as Resource]>=(n as number)*workers);if(!canInput)continue;for(const [r,n] of Object.entries(recipe.input||{}))world.resources[r as Resource]-=(n as number)*workers;for(const [r,n] of Object.entries(recipe.output))world.resources[r as Resource]+=(n as number)*workers*terrainMultiplier(world,workingJob)*seasonal*weather;}if(counts.farmer)events.push(`${counts.farmer} farmers tended the fields.`);if(counts.woodcutter)events.push(`${counts.woodcutter} woodcutters worked the forest.`);if(world.weather==='Storm')events.push('A storm slowed outdoor work today.');}
function terrainMultiplier(world:World,job:WorkingJob){return world.terrain.reduce((s,t)=>s+(terrainBonuses[t][job]||1),0)/world.terrain.length;}
function consume(world:World,events:string[]){const foodNeed=world.citizens.reduce((s,c)=>s+(c.age<16?.5:.9),0);let bread=Math.min(world.resources.bread,foodNeed);world.resources.bread-=bread;let remaining=foodNeed-bread;let wheat=Math.min(world.resources.wheat,remaining);world.resources.wheat-=wheat;remaining-=wheat;let veg=Math.min(world.resources.vegetables,remaining);world.resources.vegetables-=veg;remaining-=veg;if(remaining>0)events.push('Food is running low. Families are searching the market.');}
function maintenance(type:string){return({Bank:0,Market:15,Storage:3,House:1,Farm:3,Woodcutter:2,Quarry:4,Mine:6,Mill:5,Bakery:6,Carpenter:5,Blacksmith:8,Tailor:6,Tavern:7,'Town Hall':10} as Record<string,number>)[type]||2;}
export function tick(world:World,hours=1):World{const next=structuredClone(world);next.hour+=hours;moveCitizens(next,hours);marketStep(next,hours);while(next.hour>=24){next.hour-=24;next.day++;next.season=seasonForDay(next.day);next.weather=weatherFor(next.season,next.weatherSeed,next.day);daily(next);}updateBuildingWorkers(next);for(const c of next.citizens){c.rest=Math.max(0,c.rest-hours*(next.weather==='Storm'?2.3:2));c.social=Math.max(0,c.social-hours*.35);c.hunger=Math.max(0,c.hunger-hours*.75);if(c.activity==='eating')c.hunger=Math.min(100,c.hunger+hours*1.4);if(c.activity==='resting')c.rest=Math.min(100,c.rest+hours*1.1);c.happiness=Math.max(0,Math.min(100,(c.hunger+c.rest+c.social+c.clothing+c.purpose)/5));}return next;}
