/**
 * What changed, by version.
 *
 * Shown on the front page and in the guide, so a player does not have to find
 * the X account to learn what a new build does. Newest first. Written for the
 * player rather than the repository: what they can do now that they could not
 * before, and what was wrong that is not any more.
 */

export interface Update {
  version: string;
  /** ISO date of the release. */
  date: string;
  title: string;
  notes: string[];
}

export const UPDATES: Update[] = [
  {
    version: '2.7',
    date: '2026-09-07',
    title: 'Ages that replace',
    notes: [
      'A new age rebuilds the town. Advancing used to add a post to every workplace and a level to the cap, and players said what that felt like: a longer list, not a new age. Now every building has a form for each era, with its own name, look, room and output. Step into the township and the cabins become townhouses, the farms estate farms, the bakery a bakehouse, the mine a pit mine; the industrial age makes them terraces, mechanised farms, a cannery and a deep mine; the modern age apartment blocks and a food plant; the AI age habitat towers and an agri-tower. The rebuild also merges pairs of the same kind into one — two cabins into one townhouse with the beds of both, two farms into one estate farm with the posts of both — so a plot that was wall to wall to hold its people has open ground again. Every building raised after the step holds twice what the last age’s did on the same land.',
      'The market only trades what the age has a use for. Meals and steel belong to the industrial age, and a settlement was buying both from its first week — thirty meals and ten steel it could not eat, serve or forge, charged to a treasury of a few thousand Gold. Nothing from a later age is imported now, at any price.',
      'New goods for the later ages. From the industrial age the bakery’s cannery puts up meals from flour and vegetables, and a meal feeds better than a loaf; the food plant and the synth kitchen make nothing else. The ironworks pours steel beside its tools, and the machine works and the fabricator pour more. Both trade on the market like everything else.',
      'The city level and the era gates count homes and workplaces by age — a township one counts two settlement ones, an industrial four — so a rebuilt town is at least the size it was, and a smaller, better city is not a lower one.',
      'The improvement cap is the age’s: three in a settlement and a township, four in the industrial and modern ages, five in the AI age. That is a change from the old ladder of one more level per age up to seven, and it is deliberate: a level means more now, because the age it is reached in decides what the building is. A building keeps whatever level it had reached, so nothing already improved is taken away; one already above its age’s cap simply cannot be improved further until the plot advances.',
      'Every plot already past the settlement is rebuilt the first time it opens on this build, with a line in the feed saying what became what.',
      'Towns grow again. Players reported that the population had stopped and the breeding looked as though it had been removed, and both were real. Two things were wrong. A town never rebuilt its own ruins — only the owner could, from the building card — so every quake and flood took a house for good, the ruin kept its plot so nothing new could be raised there, and a plot left to run had no beds at all inside a season: measured at nine ruined houses out of nine, thirty adults sleeping rough and a township of forty down to eighteen with thirty thousand Gold in the treasury. And the ceiling on births counted houses, four people to each, which the age advance halved by merging cabins into townhouses while it doubled the beds — a township of thirty-six people in thirty-six beds was judged full at twenty-eight and never had another child. The settlement now raises its ruins itself, homes first, one a morning, out of gold and materials it has; and room for children is counted in beds. A township left to itself for sixty days now goes from twenty-seven people to fifty-five instead of down to twenty-three, and its stewardship from 61% to 81%, which is also why a judged yield was falling day on day.',
      'The vault’s day opens gradually. The whole day’s emission used to exist at midnight UTC, so a wallet that woke and claimed early took what it could and everybody after found the vault empty until the next day: “no withdrawal quota left” before they had claimed anything. Now 15% is open at midnight and the rest comes free evenly through the day, and the Bank says which it is — your own ceiling spent, or the vault’s next hour — and when more opens.',
      'The land weight on the dividend card is this week’s, and says so. It counts the days you were present since Monday, so it starts again each week and grows with every day you play; a player who saw 3.4 on Sunday and 0.4 on Monday saw the week turn, not a loss.',
      'Any claimed plot can be visited, however long its owner has been away. A plot whose owner had never published was turned away with “nobody has opened this world lately”, which read as though a settlement went dark when its owner did. Spectators and players can now walk any claimed plot: where the owner has published, it is their settlement as they left it, with how long ago on the banner; where they never have, it is the land grown from its seed at the age the registry records, running on its own, and the banner says so.',
      'The soft-stake card says what its figure is. A registered wallet showed a bare number — 0, for a week in which its lowest sampled balance was nothing — with no register button, and read as a stake that could not be made. The stake is registered once per wallet and is simply the balance held through the week; the card now says that, says why a week pays nothing and when the next one counts, and a wallet is sampled the moment it registers rather than at the next morning’s cron.',
      'Nothing paid into the vault is lost any more. Two players paid for surveys and claims — five payments on one wallet — and got no land: their pages had been open since before the repricing, so they paid the old prices, and the registry refused each payment as short and kept nothing of it. Three things changed. The page now asks the registry what a survey or a plot costs today and pays that, never the number in its own bundle. A page on an older build than the game does not pay at all: it is told to reload first, and the update notice can no longer be put off past a payment. And a real payment that falls short is banked against the wallet instead of refused — the message says how much is on account and how much more settles it — and whatever is on account pays for the next survey or claim. For payments already refused, the world map has “Paid and got nothing? Redeem the payment”: paste the transaction hash from your wallet and it goes on account.',
    ],
  },
  {
    version: '2.6',
    date: '2026-09-11',
    title: 'Ages that mean something, and a Bank that tells the truth',
    notes: [
      'Wealth classes, and transport as a luxury. Each morning everybody over sixteen is ranked by their purse: the top slice are well off, then comfortable, then getting by, then poor, and it shows on the card. A Stables used to put every working adult on a cart and a Harbour put every crosser in a boat of their own, and the roads and channels were a traffic jam. Now only the well-off ride — cart, rail, car, pod, or a boat across the water — in every age. Everybody else walks, and needs a bridge; a workplace on an island still has to be bridged to count as reachable, so the settlement builds crossings as it did before there was a ferry.',
      'Every GLD win is announced. When the vault pays a win at the GLD table, a card comes up on every screen in the game, the settlement and the world map alike, naming the winner and the GLD they took home. The front-page tracker now shows GLD won to enough places to read a win worth a few dollars, and its Gold cells say in-game Gold so nobody mistakes them for the token.',
      'The casino sells as many plays as you like: pick 5, 10, 25 or 50 in one payment, priced by the pass.',
      'The tables on the front page: one line under the ledger with Gold bet, Gold won, $EMERGE won, plays bought and what the passes have brought in.',
      'A GLD win that could not be bought. The router refused the vault’s swap and the table could only say that it reverted. The vault now names the reason the chain gives, can be asked to rehearse the swap without sending it, and knows how to trade through Uniswap v4 pools as well as v3. A win that is waiting is kept and paid on the next try.',
      'A big city could not advance its era. The registry judges the era step on the published copy of the world, and a settlement of about 170 people and 100 buildings had grown past the size the relay would take, so the publish was refused and the button only said to try again. Saves are now a third smaller — routes are dropped and long decimals cut — the relay takes worlds two and a half times the old limit, and the era card says the actual reason when a publish is refused.',
      'Soft staking from the world map. A wallet that holds $EMERGE but no plot can now register its soft stake, see the week’s pool and claim its GLD from the map, the first screen after connecting, instead of needing a settlement to reach the Bank.',
      'The GLD table. The coin and the cups can now be played for $EMERGE, 5,000 to 100,000 a stake, outside the daily plays. The stake goes into the vault before the draw. Lose, and it is burned, kept and pooled like every charge. Win, and the vault swaps the winnings for GLD through the router and sends the GLD to your wallet, with the transaction shown on the table; a slow chain leaves the win waiting and it is sent on the next try. Capped at 500,000 $EMERGE worth a wallet a day. The front-page tracker shows $EMERGE staked for GLD and GLD won.',
      'Nobody sets out for a place they cannot walk to. With the ferry carrying only the well-off, a baker posted to a bakery on an island, or a family given a house there, walked to the shore and stood facing it. Workplaces and houses on an island with no bridge now go only to the well-off; everybody else is matched to buildings they can reach, and any destination across the water — a bench, a friend, a wander spot — is swapped for the nearest one on their own ground.',
      'Improve every house at once. A building’s card now carries a second button that improves every building of that type by one level in one go, cheapest first, as far as the treasury and the yard allow; with Gold for four of seven, four go up and the card says so.',
      'The 1,500 Gold goodwill grant from v1.1 is withdrawn. It was meant for settlements that lived through the bread bug, but it was handed to every world on its first open, new ones included. A new settlement now opens on its 400 Gold and nothing more.',
      'The Casino. A new door on the action bar: a coin flip that pays 1.9 to 1 and three cups that pay 2.7 to 1, staked in Gold from 100 (500 when the prize is $EMERGE). The draw is made in the vault, never in the browser. Win Gold, or win $EMERGE that the Bank pays out under the same daily room and burn share as stewardship — 2 $EMERGE per Gold staked on the coin, 3 on the cups, capped at 15,000 a day per wallet so the tables cannot drain the vault. Three plays a day are free; a pass of five more is about $5, paid in $EMERGE into the vault (burned and kept like every charge) or in ETH, of which 30% goes to development and the rest stays in the vault.',
      'Names that stay. A nickname chosen on one device was lost when the game opened on another: the fresh device’s random name was newer, so it won the merge and was written back over the server’s copy. The name now follows whoever actually changed it.',
      'The world map shows the name you gave your world. Renaming carried to the plot’s token but not to the claim row the map and the leaderboard read, so they kept the old name. It travels there now.',
      'Discord. The invite is in the footer of the front page.',
      'The look, eased. Players found the first version hard on the eyes and the dialogue hard to read: the grade was going over the speech bubbles too. It now goes over the picture only, the bubbles sit on top of it crisp, larger and with a dark edge, and the bloom, warmth, vignette and saturation are all pulled back to about half.',
      'The look. The finished frame now goes through one pass that does what a camera does to a scene: a bloom round every lit window, lantern and torch, a warm grade, a filmic tone curve so the brights roll off instead of clipping, a little more saturation and a vignette toward the corners. It is toned in linear light, not on the pixels, so shadows stay shadows. The ✧ button beside the clock, or V, turns it off and on; the choice is kept on the device.',
      'Ground that runs into ground. Every tile used to stop dead at its diamond, so a meadow met a wood along a sawtooth of perfect edges. Each kind of ground now spills a ragged, dithered tongue over its lower neighbour along the edge they share — grass over sand, the wood’s floor over the meadow, never the other way — so the land reads as one surface.',
      'A grid for planning. The ⌗ button beside the clock, or G, lays a tile grid over the ground, drawn at each tile’s own height with the buildable edge picked out in gold. Off by default; remembered on the device.',
      'Ponds and channels by your own hand. The Build panel’s Pond tool digs water where you tap, on open ground clear of the square, the buildings and the bridges, for Gold; dig beside it and the two join into a channel. Fishers cast into it, people walk round it, the roads through it are cut and the islands it makes are bridged like any other. A pond you dug can be filled in again. Saved with the world and judged with it.',
      'The ledger, live, on the front page: what has been paid into the game, what the vault has burned of it (and what awaits the next sweep), and what has been withdrawn to players’ wallets, read from the vault every half minute and counted up to the new figure.',
      'The world map lagged. Every marker carried a backdrop blur, which made the browser re-sample the map under each of them on every hover, and the twelve-second poll re-rendered the whole map even when nothing had changed. Both are gone.',
      'Twenty-four withdrawals that were six. The day’s count of withdrawals was taken before the vault checked the day’s room, so every refusal for room spent one, and a player asking for exactly the figure the Bank showed — a figure that moves as yield accrues and attention slides — could be refused a few tokens short again and again until the count said twenty-four with six on the ledger. The count is now taken only when the vault is about to sign; a refusal costs nothing. Asked for more than the day has room for, the vault pays the room and says so instead of refusing. The refusals name the time until the day turns, and speak Chinese.',
      'A second bakery works. Everybody in a trade used to walk to the first building of its type, so a second bakery or carpenter’s shop never had a soul inside: its card said quiet, its crew read nought, and players wrote in that it was broken while the trade as a whole was producing. Each worker now reports to a site of their own, chosen for the free posts it has, and a workplace’s card says how many of its posts are filled. When a trade cannot work in full for want of an input, the card says so: which input, and how many of them worked.',
      'Conversations you can watch. Two people who start talking now stop and face each other for it, and the bubble follows the exchange, hopping to whoever is speaking, so an exchange reads as one: before, people talked as they walked past each other, the talk was cut two paces later with one line said, and the answer went to somebody with no bubble to say it in. Every conversation now runs its course, and every line of it is drawn.',
      'Photo mode. The ◉ button beside the clock, or P, hides the whole interface for a clean screenshot; P, Esc or the pill in the corner brings it back.',
      'Every age builds its own way. The settlement is log cabins: round logs notched at the corners under a low roof of split shakes or thatch, a porch on posts over the door, a fieldstone chimney, firewood against the wall, plank lodges for its halls. The township is the first place built to last: timber-framed homes on two floors with plaster between the beams and fired tile above, a dormer in the roof and a stone course at the foot; halls in dressed stone under slate. A building keeps the look of the age it was raised in until it is improved.',
      'People talk like people. Every citizen now has a temperament — warm, blunt, a dreamer, a worrier, a joker, proud, quiet, curious, a grumbler or steady — and it colours how they answer. A conversation is composed for the two having it: an opening that knows what they are to each other (a spouse, kin, a friend, someone they have met, a stranger, a rival), a subject one of them has a real reason to raise, a reply in the listener’s own voice, and a parting that says where they are off to. People remember what happens to them — a night gone hungry, going unpaid, sleeping rough, a fight they saw, a new friend, setting up house, a child, arriving, mastering a trade, jail, sickness, a festival, a falling-out, a loss — and ask each other about it, and they remember what they last talked about with each person and pick it up next time. The card shows their temperament, what has happened to them lately, and who they last talked with and about what.',
      'The settlement is painted in the sun. A new colour script keyed to golden hour: warm cream plaster with its timber frame and braces showing, dressed stone laid in courses, round logs lit along the top, terracotta and slate in scalloped rows, thatch in bundles with a ragged eave. The sun sits upper right on everything — the lit face, the shaded face, a band of shadow under the eave and at the foot of the wall, a shadow thrown to the lower left — and windows glow warm by day. Doors are arched in stone with a step. Conifers are chevron tiers with a lit side; broadleaf canopies are clusters of small lobes with the sun on their upper right. Grass is mottled with tufts, the square is laid in irregular flagstones, water is teal with softer shallows, dusk is amber. The stray dots that hung round every roof are gone, and so are the dark diamonds where raised ground showed the backdrop through.',
      'An age is a step up for the whole town. Every workplace takes one more person per age the plot has reached, every house sleeps one more, every pair of hands makes 12% more, the improvement cap rises a level, and the Build panel opens on the age’s own buildings with the earlier ages a tab away and the later ones there to look at. Players said advancing felt like unlocking a few buildings; it is now the town growing.',
      'The level cap follows the age. A settlement improves a building to level 3; each age opens one more, to 7 in the AI age. A building keeps the level it reached when the plot advanced, and improving one raised in an earlier age re-dresses it in the plot’s current one. Each step past the third costs more again.',
      'The Bank shows what the vault will pay. Under Collect, “Judged by the vault today” is the figure a withdrawal is measured against, across all your earning plots together, with each plot’s paid level, how it is run and how attended it is. A plot is paid at its city level or one level per three days you have been present, whichever is lower, and the card says how many days you have — the “earning per day” on your own screen counts the plot at full city level, which is why it could show more than arrived. Collectable today is measured against the same figure, the collect field fills with it, and a refusal is now a notice on screen rather than a line at the foot of the panel.',
      'A withdrawal is paid when the chain says so. The vault now waits for the transfer’s receipt before telling you it was sent; a transfer the chain rejects is refused outright and nothing leaves your balance. One that takes longer than the wait is listed as “sending” under Paid out with its explorer link, checked again on your next look at the Bank, and if it turns out to have been rejected the amount goes back into your in-game balance with a notice saying so.',
      'A bridge lands where people can step off. A crossing’s banks are the first dry ground along its line, and on a spit, a cove or a slanting shore the ramp still ended inside the water’s walking margin: the deck walked people to its end and the shore refused the step, so a queue stood on the bridge all night beside whatever bush was there. A third of hand-built crossings ended like that. Crossings are now chosen for banks with a way off them, ramps run on until they reach open ground, and bridges already built are lengthened the same way when the plot loads. Bushes are scenery: they never blocked anybody.',
      'A crossing can come down. Once a plot has a bridge, the Build panel’s Bridge card carries Take a crossing down: tap the deck and it goes, with some of its planks back in the yard, the road across the water cut and anybody on it stepped off at the nearer bank. The one crossing to an island with buildings on it is refused until they are pulled down or another crossing stands, so nothing is stranded.',
      'Bridges anywhere. Tap the water you want bridged, or the land across it, and the crew stakes out the narrowest crossing there, including across a lake in the middle of town that people could already walk round. On an expanded plot the crossing search now covers the outer belt.',
      'Bridges stay clear. Nothing can be placed on a deck or its ramps, and if a building already stands on one the helper says which and asks you to move it: people bound for the far bank were walking to it and stopping.',
      'Newcomers are housed the moment they arrive, by the same shared-house rule as everybody else, instead of sleeping rough until the next morning while a house had a spare bed.',
      'Children again. Somebody who arrived alone can now pair off, and a couple needs a bed rather than a whole empty house, so a grown town of newcomers has households and births again instead of only the road.',
      'Send people away. An adult’s card has Send away: a few days’ pay and they leave on the road, their bed and post free the same day. And the gates: close them on the People panel and nobody new is taken in. Newcomers now only come while there is a post to fill, so a big plot no longer fills with people who have nothing to do.',
      'Keep in store. On the Market panel each good has a keep: the market never sells below it, so iron ore saved for the next era stays in the barn. It does not buy up to it.',
      'Bread. A trade with an input now works as far as the store stretches instead of all or nothing: three bakeries and twenty bakers used to want two hundred flour and fifty timber before a single loaf was baked, and on a short day baked none while wheat and flour piled up. The feed says which input ran short and how many worked.',
      'The helper stops asking for a seventh farm. With farms already standing it says whether the fields lack hands or a level, and what else feeds a town.',
      'The building cursor tells the truth. It asks the same rule the placement does, so green means it will go there, and a refusal now says why on screen rather than only in the feed.',
    ],
  },
  {
    version: '2.5',
    date: '2026-09-10',
    title: 'The lodge, and plots you are not looking at',
    notes: [
      'Hunting is paid like every other trade. The stalking you can watch is the visible part of the day; the snares, the lines and the ground beyond the plot’s edge bring in the rest, so a lodge full of hunters no longer shares one herd of ten and reports 0 a day. An improved lodge and a full quiver raise the take as they should.',
      'Animals now spread over the whole of an expanded plot, and the Lodge’s card says how many are on the land and in reach.',
      'Attention is yours, not the plot’s. Acting on any of your plots keeps every plot you own attended, on this device, on another, and in what the vault judges. A plot you leave running earns at the shape you left it in, against the clock, whether or not it is open.',
      'The Town Hall can be built. It was in the Township’s conditions and in every list but the Build panel’s; it is on the Civic shelf now, for 480 Gold, 20 timber and 30 stone.',
      'Moving a building works on a phone. A tap places it where the finger is; before, the ghost only ever followed a mouse.',
      'A lived-in house can be pulled down. The family moves to another house with room, or sleeps rough until one is raised, and the card says so. The market, the bank and the town hall say why they cannot come down instead of hiding the button.',
      'A first day. A new settlement opens with a card that says what the game pays you for and gives five things to do — a person, a house, the Bank, an improvement, and coming back — each ticked off by doing it. Skip it any time.',
      'A leaderboard on the world map. Every city ranked by the level the vault judges it at, then by how well it is run, with its banner, era and GLD beside it. Tap a row to go and look.',
      'A pass over the phone: every panel by touch. The language switch no longer sits over the population pill in the world, and everything a finger has to hit is big enough to hit.',
      'Nine more charts. The world grows from twelve charts and 204 plots to twenty-one charts and 357, seventy-two new islands with names of their own, and the map counts across all of them.',
      'The GLD swap goes through Uniswap’s Universal Router, routed: $EMERGE is sold into its own pool and GLD bought with the proceeds in one trade, paid through Permit2 and floored under the quoter, because that is the router Robinhood Chain has and GLD’s pool is against USDG.',
    ],
  },
  {
    version: '2.4',
    date: '2026-09-09',
    title: 'The GLD dividend',
    notes: [
      'Every charge now splits three ways: 60% burned by the vault, 25% kept to pay withdrawals, 15% set aside in a dividend pool. Withdrawal holds split the same way.',
      'Each Monday the vault sends 30% of the pool to development, swaps the rest into GLD on Robinhood Chain, and books the GLD to holders: 55% to land, weighted by the level each plot is judged at and the days its owner was present that week; 15% to soft stakes.',
      'A soft stake is a registration, not a lock. Register once on the Bank’s DIVIDENDS card, and your lowest $EMERGE balance through the week counts, from 100,000 up to a cap of 5,000,000. Sell mid-week and the week is forfeited; nothing else changes.',
      'GLD waits under your wallet until you claim it, and the vault sends it. The pool, your land weight, your stake and your GLD are all on the card, and the settlements are on the public book.',
    ],
  },
  {
    version: '2.3',
    date: '2026-09-08',
    title: 'The flywheel, judged: every improvement counts, every charge feeds the vault, and the vault pays what it can see',
    notes: [
      'Every improvement does something, and the building’s card says what. Workplaces make 22% more per level as before; a house adds two beds; a school, library, lab, clinic, hospital, cafe, tavern, chapel and the rest do their job a quarter more strongly per level; a market sells exports for 5% more per level; a bank makes every building’s upkeep 5% cheaper per level; a town hall lifts stewardship quality 2% per level; an improved store counts half again toward readiness; stables, stations, depots and pod hubs move people 10% faster per level; an improved jail halves the odds again and stops a rogue sooner.',
      'Stewardship is now judged on the server. The level a plot is paid on is the smaller of what its published world shows and one level per three days its owner has actually been present, which the heartbeat records and the client cannot write. Its score is computed from the published world with the same function the settlement runs, and its attention from the owner’s last heartbeat. The payout route pays the lesser of what the client claims and that. Hands are paid a tenth of the plot’s judged ceiling.',
      'Prices, for a game where a plot can earn 250,000 a day: plots cost about three times what they did; a fresh plot’s ceiling starts at 40,000; a charter is four days of the plot’s own ceiling (160,000 for a new plot, 1,000,000 for a top city), the same bargain at every level; eras cost a million per step already taken, 1M, 2M, 3M, 4M; expansion is 1,000,000; renames, surveys and digs are doubled; a withdrawal holds back 10%, half burned and half kept; a hand needs 50,000 to be hired and the owner pays 10,000 to open the job; a resale carries a 5% registry fee into the vault.',
      'Bets in $EMERGE at the colosseum, beside the Gold ones. The stake goes into the vault, a win is paid by the vault at the odds shown, a loss stays. 50,000 a bout, 250,000 a day. The house edge is booked like every charge.',
      'Prestige. A monument in the square, 250,000, unique to the plot, lifts everyone a little each day and stands as long as the city does. A banner, 100,000, an emblem of your choosing over your name and on every world map.',
      'Rewards are paid against the clock whether or not the game is open. A player who saw 16,000 a day and received 8,800 had the tab closed for eleven hours: accrual used to run only while the page drew frames. Now the stretch since the last accrual is paid at the attention it actually had through it, up to a month at a time, and a stretch that comes to more than the day’s ceiling stays banked for tomorrow instead of being lost. The payout route allows a day’s grace after your last visit before attention starts to slide.',
    ],
  },
  {
    version: '2.2',
    date: '2026-09-07',
    title: 'The flywheel, one of each, and no more twenty-seven-building rogues',
    notes: [
      'The split on every charge is now three quarters burned and a quarter kept in the vault to pay withdrawals from. The Bank has a THE FLYWHEEL card showing the vault’s book: paid in by players, burned by the vault, kept for withdrawals, owed to the burn.',
      'Master builders: 120,000 $EMERGE puts a crew in the square for thirty days, and every building you raise and every improvement you pay for costs a quarter less Gold. Buying again adds the days on. On the On-Chain panel with the charter and the insurance.',
      'One of each. A town hall, a jail, a tavern, a school, a harbour: every building whose whole effect is that one stands is now unique to the plot. The Build panel marks the one you have as Built, the cursor refuses a second, and the settlement’s own builder never raises one. Houses, stores and every workplace with posts are still worth more of.',
      'Houses sleep 3, 5 and 7 by level. Improving a house adds two beds each time, and the house’s card says who sleeps there against the beds and what an improvement would add. That is what improving a house is for.',
      'The jail’s level is what counts now, not how many jails: a level-three jail cuts the chance of anybody turning to an eighth, and a rogue is stopped at the first building. Without a jail a rogue can bring down three at most; with one, three, two or one by its level; and any rogue still loose by morning is cornered by the whole settlement. A rogue at night now wakes the nearest people rather than having the town to themselves. This closes the twenty-seven-buildings report.',
    ],
  },
  {
    version: '2.1',
    date: '2026-09-07',
    title: 'Ten times the rewards, and charges that fund them',
    notes: [
      'Rewards are ten times what they were. A plot’s daily ceiling now runs from 60,000 $EMERGE at level one to 250,000 for a level-ten city in the AI era. Five plots earn instead of four, and a wallet can collect up to 1,000,000 a day across them. A single withdrawal can be up to 1,000,000.',
      'Every charge now goes into the vault instead of straight to the burn address. The vault burns half of it itself, from its own key, in one transaction for many charges; the other half stays in the vault to pay withdrawals from. Same one signature for you; what players spend is what players are paid from, and the vault can cover what it owes. The book is public at /api/vault: paid in, kept, owed to the burn, burned, with the burn transactions.',
      'Three more things to spend on, from the SUPPLIES card on the On-Chain panel, delivered the moment the payment settles: a party of five settlers (50,000, needs room in the houses), a shipment of 400 timber, 300 stone and 240 portions of food (40,000), and a restoration that rebuilds every ruin and finishes the bridge under way (100,000).',
      'Charters and insurance repriced for the new ceilings: 300,000 and 150,000.',
    ],
  },
  {
    version: '2.0',
    date: '2026-09-06',
    title: 'City levels, Gold with somewhere to go, and $EMERGE worth holding',
    notes: [
      'City levels. Every plot has a level, one to ten, read from its people and its buildings standing. Size earns the next level; Gold pays for the public works that confirm it, from 1,500 Gold at level two to 130,000 at level ten. The CITY card in the Bank shows the level, what the next one asks, and the button. An existing city is graded on what it already is, with nothing to pay for the levels it has grown into.',
      'Rewards run on the level. A plot’s daily ceiling runs from 6,000 $EMERGE at level one to 25,000 at level ten, times the era: a level-ten city in the AI era can earn up to 40,000 a day. A fresh claim earns a fraction of a developed city, so growing what you have is worth more than claiming another. The payout route reads the level from your published world, so the ceiling cannot be reached by editing a save.',
      'Gold has somewhere to go. Public works, festivals (Gold by the head for the whole town’s happiness, once a day), bridges you order yourself, and upkeep that rises a quarter per era a building was raised in. The treasury is for building a city with, not for counting.',
      'Charters: 100,000 $EMERGE burned for a fifth more on the plot’s ceiling for thirty days. Insurance: 50,000 $EMERGE burned so the plot takes half of whatever a fire, a quake, a flood or a rogue does, for thirty days. Both on the On-Chain panel, recorded on the claim row, and both add days on if bought again while one runs.',
      'No disaster can flatten a city. An earthquake or a tornado can damage at most a quarter of what stands (never fewer than three buildings). A player who came back to two buildings out of forty had not been set back, they had been given a reason to stop; that cannot happen now.',
      'Jails work. Every jail standing halves how often anybody turns, down to a tenth, and with a jail a rogue in a scuffle breaks free once in ten rather than once in three. Two jails in a town of a hundred and fifty now make a visible difference.',
      'Houses hold families. A house sleeps as many people as it has room for, three at level one and more with each improvement, so a newcomer who came alone shares a roof rather than taking a whole house for one bed. "One house, one person" is gone.',
      'Bridges by hand. The Build panel has a Bridge tool: tap land across the water and the crew stakes out the narrowest sound crossing to it, 600 Gold to start, timber and wages by the day. When the yard is short of timber the crew buys it in with Gold rather than standing idle, which is why some towns had stopped bridging.',
      'The era gate asks for a city level as well: level three for the township, five for industrial, seven for modern, nine for AI.',
    ],
  },
  {
    version: '1.6',
    date: '2026-09-05',
    title: 'People, training, and rewards that grow with the city',
    notes: [
      'A People panel in the bar. Every adult with their trade, their skill and where they work, the unemployed first, filterable by trade. Every trade with its workers against its posts and how many stand open. Every workplace with its crew and its posts, ruins flagged. No more guessing what a building is or which jobs you are missing.',
      'Targeted training. Retrain one person into any trade that has a workplace, or fill every open post in a trade at once with the people who can best be spared: the unemployed first, then anyone in a trade with more hands than posts, then the least skilled. 60 Gold a head. A trained person keeps the trade for forty days against the settlement\u2019s own reshuffling and starts with a head start in skill, doubled by a School.',
      'Rewards grow with the era. Each era a plot advances to lifts its daily stewardship ceiling by 15% of the base: a township can earn up to 15% more than a settlement, an AI-era city up to 60% more. The payout route reads the era from the claim row, which only the gated, burn-verified advance can raise.',
    ],
  },
  {
    version: '1.5',
    date: '2026-09-04',
    title: 'Every era, to the AI age',
    notes: [
      'The three remaining eras are built and open: Industrial, Modern and AI. A plot advances one step at a time, 1,000,000 $EMERGE burned per step, once it has earned it. The checklists are on the ERA card.',
      'Industrial: brick and iron, setts with rails on the roads, chimneys. A Railway Station puts every working adult on the rails, faster than carts; the ferry becomes a steamboat. Factory, Foundry, Telegraph and Gasworks. Smog hangs over the town and drains happiness until a Gasworks stands.',
      'Modern: concrete and glass, tarmac with markings, jackets and jeans. A Bus Depot puts people in cars, a third of them on bikes; the ferry becomes a motorboat. Hospital, Stadium, Supermarket, Office and Power Plant. The Hospital takes most of the risk out of a bad week.',
      'AI: white composite, light strips, gardens on the roofs, pale quiet roads. A Pod Hub puts everybody in autonomous pods, fastest of all; the ferry becomes a hydrofoil. Data Centre, Research Campus, Vertical Farm and Drone Port.',
      'Every building already standing is redrawn in the new era\u2019s style when you improve it, and keeps its old look until then. People change clothes and hats with the era: bonnets and tricorns, bowlers and goggles, caps and beanies, visors.',
      'Streets connect. A road reads its neighbours and runs unbroken into the next tile or the plaza; every other edge gets the era\u2019s kerb and pavement. Ruts on a dirt lane, rails on the setts, a dashed line down the tarmac, a light seam along the composite.',
      'Each era rebuilds a building in its own shape, not a new colour. The township raises mansard-roofed stone homes, steep gables and tall hipped halls; the industrial era long brick terraces with a stack, sawtooth glass roofs over the works and flat-topped blocks; the modern era stepped concrete homes, wide sheds and towers; the AI era rounded white pods with garden decks and domes of light.',
      'People ride what they ride. Every vehicle is drawn at their scale and in two layers, so a rider sits inside the car or the pod, astride the bike, on the box seat of a horse-drawn cart or in the tram, and in the boat. Boats appear only over water.',
    ],
  },
  {
    version: '1.4',
    date: '2026-09-04',
    title: 'Eras: the Township',
    notes: [
      'A plot can advance from the Settlement era to the Township era. It has to earn it first: sixty days in the era, forty people, thirty buildings standing, a Town Hall, a Bank, a School and a Jail, 20,000 Gold in the treasury and no ruins. Then 1,000,000 $EMERGE, burned, once per step. The ERA card in the On-Chain panel shows the checklist as it fills in.',
      'A township looks like one: stone walls and tiled roofs on everything raised or improved after the step, cobbled streets in place of dirt, and people in wool coats and hats. What was built before keeps its timber until you improve it.',
      'Six new buildings: Chapel, Guildhall, Brewery, Printer, Stables and Harbour. A Stables puts every working adult on a cart, faster than walking. A Harbour runs a ferry: people cross open water on a boat, and every island counts as reachable without a bridge.',
      'The Build panel is sorted into shelves: Homes, Food, Materials, Civic, Care and learning, Leisure, Transport and Utilities. Buildings from a later era are shown greyed with the era they belong to. The settlement\u2019s own builder only raises what its era allows.',
      'Three more eras are named and gated but not yet built: Industrial, Modern and AI. The checklist for each is already on the card, so a plot can start working toward it.',
    ],
  },
  {
    version: '1.3',
    date: '2026-09-03',
    title: 'Your settlement can no longer be lost',
    notes: [
      'Published worlds are kept for over a year, not a day and a half, and the server refuses any copy of your world that goes backwards. Every device reads the furthest-along copy before it plays, and again whenever you come back to the tab.',
      'Hired hands: a player with no plot who holds 1,000 $EMERGE can take a job on a plot that is hiring and is paid a tenth of its stewardship, up to 2,500 a day, by the vault. Their shift counts as the owner\u2019s attention.',
      'Just watch: the front door opens the world map without a wallet. Spectators can visit any settlement and talk in chat, badged as spectators.',
      'Plot expansion: the land itself grows, a ring of new ground on every side, about half as much land again, for 500,000 $EMERGE, once per plot.',
      'The world map has a Home button and a Disconnect wallet button. The guide has pictures, and this list.',
      'A soundtrack: six loops for the settlement by day, dusk, night, danger, the world map and visiting. Press the note to hear it.',
    ],
  },
  {
    version: '1.2',
    date: '2026-08-30',
    title: 'Two hundred plots, a plot market, and the wild',
    notes: [
      'Twelve charts and room for about two hundred settlements. Plots are sold player to player, wallet to wallet, and anybody can make an offer on any plot.',
      'Fishing, hunting and foraging. Fishers cast from the shore and buy bait; hunters stalk deer, boar and whatever the biome keeps; foragers bring in berries and herbs. All of it sells at the market.',
      'Earthquakes, tornados, floods and plagues you can spend Gold to fight; ruins you rebuild; people who turn rogue and have to be jailed or stopped by the settlement itself.',
      'The settlement builds what it needs from a full treasury. Trees can be cleared, and regrow on open ground when they are built over. Desert trees can be felled.',
      'Chinese, throughout the game and the guide. Better pathfinding, one deck per bridge, and settlers who keep arriving as a plot improves.',
    ],
  },
  {
    version: '1.1',
    date: '2026-08-20',
    title: 'The guide, the market and the colosseum',
    notes: [
      'A public guide that explains every system, including which parts settle on chain today and which do not.',
      'One market across every world, wages you set, and a card when your people sell something.',
      'The colosseum on its own island, with Gold bets on duels. Schools, labs, cafes, studios, clinics and libraries. Buildings can be moved and improved.',
      'A graphics overhaul toward the target style, redrawn citizens, and a plot helper that says what to build next and why.',
      'How many players are online, and a settlement that follows your wallet across devices.',
    ],
  },
];

export const UPDATES_ZH: Update[] = [
  {
    version: '2.7',
    date: '2026-09-07',
    title: '换代重建的时代',
    notes: [
      '新时代重建整座城。以前推进时代只是给每个工作场所加一个岗位、给上限加一级，玩家说那感觉像一张更长的清单，不像一个新时代。现在每栋建筑在每个时代都有自己的形态：自己的名字、样子、容量和产出。进入城镇，木屋变成联排石屋，农场变成庄园农场，面包坊变成烘焙坊，矿井变成露天矿；工业时代把它们变成排屋、机械化农场、罐头厂和深井矿；现代变成公寓楼和食品厂；人工智能时代变成居住塔和农业塔。重建还会把同类建筑两两合并为一栋——两间木屋合成一栋联排石屋，床位是两间之和；两座农场合成一座庄园农场，岗位是两座之和——所以原本挤得满满的地块又有了空地。推进之后每一栋新建的建筑，在同样的地上容纳上一个时代的两倍。',
      '市场只交易这个时代用得上的东西。餐食和钢材属于工业时代，而一个聚落从第一周就在买这两样——三十份吃不了、端不出的餐食和十份炼不了的钢材，记在只有几千金币的金库上。现在后面时代的货物无论什么价都不会再进口。',
      '后面时代的新货物。从工业时代起，烘焙坊的罐头厂用面粉和蔬菜做餐食，一份餐食比一条面包更顶饱；食品厂和合成厨房只做餐食。铁工坊在工具之外炼钢，机械厂和制造舱炼得更多。两样都和其他货物一样在市场上交易。',
      '城市等级和时代门槛按时代计算住房和工作场所——一栋城镇的算两栋聚落的，工业的算四栋——所以重建后的城至少和原来一样大，更小更好的城不会更低级。',
      '升级上限看时代：聚落和城镇三级，工业和现代四级，人工智能时代五级。这和以前每个时代多一级、最高七级的阶梯不同，而且是有意为之：一级现在更有分量，因为达到它的时代决定了建筑是什么。建筑保留已经达到的等级，已升级的不会被收回；已经超过本时代上限的，只是要等地块推进后才能再升。',
      '每块已经越过聚落时代的地块，在这个版本第一次打开时会被重建，动态里有一行说明什么变成了什么。',
      '城又开始生长了。玩家反映人口停止增长、繁衍系统像是消失了，两件都是真的，各有一个原因。聚落从不重建自己的废墟——只有地主能从建筑卡片重建——所以每次地震和洪水都会永久带走一栋房子，废墟占着地，新房子也没处盖，放着不管的地块一个季度内就一张床都不剩：实测九栋房子九栋废墟，三十个成年人露宿，一座四十人的城镇掉到十八人，而金库里躺着三万金币。另外，生育的上限按房子数算、每栋四人，而推进时代把木屋两两合并成联排石屋，房子数减半、床位翻倍——一座三十六人住三十六张床的城镇被判定为二十八人就满员，从此再没有孩子出生。现在聚落会自己重建废墟，先住房、每天早上一栋，用它手头的金币和材料；孩子的余地按床位算。一座放六十天不管的城镇，现在从二十七人长到五十五人，而不是掉到二十三人；经营从 61% 升到 81%——这也是裁定收益一天比一天低的原因。',
      '金库的一天是逐步开放的。以前整天的排放额在 UTC 零点一次到位，早醒早领的钱包能领多少领多少，后面的人发现金库空了只能等第二天：什么都还没领就看到"今天没有提取额度了"。现在零点开放 15%，其余的在一天里匀速释放，银行会说明是哪一种情况——是你自己的上限用完了，还是要等金库的下一个小时——以及什么时候会再开放。',
      '分红卡上的土地权重是本周的，并且写明了。它计算从周一起你在场的天数，所以每周重新开始，你每玩一天它就长一点；周日看到 3.4、周一看到 0.4 的玩家看到的是一周的翻篇，不是损失。',
      '任何已认领的地块都可以参观，不论地主离开了多久。以前地主从未发布过的地块会被拒之门外，提示“最近没有人打开过这个世界”，读起来像是地主一走聚落就熄灯了。现在观众和玩家都能走进任何已认领的地块：地主发布过的，看到的是他们离开时的聚落，横幅上写着多久以前；从未发布过的，看到的是按登记处记录的时代从种子生成的土地，自行运转，横幅会写明。',
      '软质押卡片会说明它的数字是什么。已登记的钱包只显示一个光秃秃的数字——比如某一周采样到的最低余额是零时显示 0——又没有登记按钮，读起来像是一个无法建立的质押。软质押每个钱包登记一次，就是整周持有的余额；卡片现在会说明这一点，说明为什么某一周没有分红、下一周何时计入，而且钱包在登记的那一刻就会被采样，而不必等到第二天早上的定时任务。',
      '付进金库的钱不会再丢了。两位玩家为勘测和认领付了款——一个钱包五笔——却没有拿到土地：他们的页面在调价之前就一直开着，付的是旧价格，登记处把每一笔都判为不足而拒绝，而且一分都没有留下。改了三件事。页面现在先向登记处询问今天勘测或地块的价格，然后付这个数，绝不再用自己代码里写死的数字。比游戏版本旧的页面完全不会付款：它会先被要求刷新，更新提示也不能再拖到付款之后。真实但不足的付款会记入钱包账户而不是被拒绝——提示会说明账户上有多少、还差多少——账户上的余额用于支付下一次勘测或认领。已经被拒绝的付款，世界地图上有“付了款却什么都没得到？兑现这笔付款”：粘贴钱包里的交易哈希，它就会记入你的账户。',
    ],
  },
  {
    version: '2.6',
    date: '2026-09-11',
    title: '有分量的时代，和说实话的银行',
    notes: [
      '阶层，和作为奢侈品的交通。每天早上，所有十六岁以上的人按钱包排名：最上面一小部分是富裕，然后是小康、过得去、清贫，卡片上会显示。以前马厩让每个上班的成年人坐马车，港口让每个过水的人各乘一船，路上和水道上挤成一团。现在只有富裕的人乘车——马车、铁路、汽车、出行舱，或者乘船过水——每个时代都是如此。其他人步行，需要桥；岛上的工作场所仍要架桥才算能到达，所以聚落会像有渡船之前那样修渡口。',
      '赌场想买多少次就买多少次：一次付款可选 5、10、25 或 50 次，按通行证计价。',
      '首页上的赌桌一行：账本下方一行显示已下注金币、已赢得金币、已赢得 $EMERGE、已购买局数以及通行证带来的收入。',
      '赢到的 GLD 买不到。路由拒绝了金库的兑换，桌上只能说它回滚了。金库现在会说出链上给出的原因，可以在不发送的情况下演练兑换，并且除了 v3 还会通过 Uniswap v4 池交易。等待中的赢款会保留，下次尝试时支付。',
      '大城市无法推进时代。登记处根据已发布的世界副本判断时代升级，而一个约 170 人、100 座建筑的定居点已经超过中继接受的大小，发布被拒绝，按钮却只说请稍后再试。存档现在小了三分之一——去掉了路线、截短了长小数——中继接受的世界大小是原来上限的两倍半，发布被拒绝时时代卡片会说明真正的原因。',
      '在世界地图上软质押。持有 $EMERGE 但没有地块的钱包，现在可以在地图上——连接后看到的第一个界面——登记软质押、查看本周奖池并领取 GLD，不再需要先有定居点才能进银行。',
      'GLD 桌。硬币和纸杯现在可以用 $EMERGE 玩，每把押 5,000 到 100,000，不占每日局数。押注在开奖前进入金库。输了，它像每笔收费一样被销毁、留存、入池。赢了，金库通过路由把赢款兑换成 GLD 发到你的钱包，桌上显示交易；链上慢的时候赢款会等待，下一次尝试时发送。每个钱包每天上限价值 500,000 $EMERGE。首页追踪器显示押注换 GLD 的 $EMERGE 和赢得的 GLD。',
      '没人会出发去走不到的地方。渡船只载富人后，被派到岛上面包房的面包师、或分到岛上房子的家庭，会走到岸边对着水站着。没有桥的岛上的工作场所和房子现在只分给富人；其他人只会被安排到走得到的建筑，任何隔水的目的地——长椅、朋友、闲逛点——都会换成自己这块地上最近的一个。',
      '一键升级全部房屋。建筑卡片上新增第二个按钮，一次把该类型的所有建筑各升一级，先升便宜的，国库和堆场能付多少升多少；七座里付得起四座就升四座，卡片会说明。',
      '取消 v1.1 的 1,500 金币补偿。它本是给经历过面包 bug 的定居点的，却发放给了每个首次打开的世界，包括新世界。新定居点现在只以 400 金币开局。',
      '赌场。行动栏上新开一扇门：抛硬币赔 1.9 比 1，三个纸杯赔 2.7 比 1，用金币下注，最少 100（奖品是 $EMERGE 时最少 500）。开奖在金库进行，从不在浏览器里。可以赢金币，也可以赢由银行按与经营收益相同的每日额度和销毁比例支付的 $EMERGE——硬币每押 1 金币赢 2 $EMERGE，纸杯赢 3，每个钱包每天最多 15,000，牌桌不会掏空金库。每天三次免费；再买五次约 $5，用 $EMERGE 支付进金库（和每笔收费一样销毁并留存），或用 ETH 支付，其中 30% 归开发，其余留在金库。',
      '名字会留住。在一台设备上改的昵称，换台设备打开就没了：新设备的随机名字更新，合并时赢了，还被写回了服务器。现在名字跟随真正改过它的那份记录。',
      '世界地图显示你给世界起的名字。改名以前只写到了地块代币上，没写到地图和排行榜读取的认领记录里，所以它们仍显示旧名。现在会一起更新。',
      'Discord。邀请链接在首页页脚。',
      '画面效果减弱。玩家觉得第一版刺眼、对话难读：调色也叠在了对话气泡上。现在只处理画面本身，气泡在上面保持清晰，更大并带深色描边，泛光、暖色、暗角和饱和度都减到了约一半。',
      '画面效果。完成的每一帧现在会过一道处理，做的是相机对场景做的事：每扇亮着的窗、每盏灯和火把周围有泛光，暖色调，胶片式的曲线让高光柔和滚落而不是溢出，饱和度略高，四角有暗角。它在线性光下调色而不是在像素上，所以暗部仍是暗部。时钟旁的 ✧ 按钮或 V 键可以关闭和打开；选择保存在本设备。',
      '地面连成一片。以前每块地砖到菱形边缘就戛然而止，草地和林地相接是一排锯齿般的直边。现在每种地面沿共享的边向较低的邻居伸出一条参差、抖色的舌头——草压过沙、林地压过草甸，绝不反过来——所以土地读起来是一整块。',
      '规划网格。时钟旁的 ⌗ 按钮或 G 键在地面上铺一层网格，按每块地砖自己的高度绘制，可建造范围的边缘用金色标出。默认关闭；本设备记住选择。',
      '亲手挖池塘和水道。建造面板的「池塘」工具在你点的地方挖出水面，须是远离广场、建筑和桥的空地，花金币；在旁边再挖，两个就连成一条水道。渔夫会来这里下钩，人会绕着走，穿过它的路会被切断，它造出的岛会像其他岛一样被架桥。自己挖的池塘可以再填回去。随世界保存，一起裁定。',
      '首页上的实时账本：已投入游戏的数额、其中金库已销毁的（以及等待下次销毁的）、以及已提现到玩家钱包的，每半分钟从金库读取一次并滚动到新数字。',
      '世界地图卡顿。每个标记都带着背景模糊，浏览器在每次悬停时都要重新采样每个标记下方的地图；十二秒一次的轮询即使没有变化也会重绘整张地图。两者都去掉了。',
      '明明六次却说二十四次。每日提现次数在金库核对当日额度之前就被计入，所以每次因额度不足被拒都算一次；玩家按银行显示的数字精确提取——而这个数字随收益累积和关注度下滑而变动——可能因差几枚而一再被拒，直到账上只有六笔却被告知已提二十四次。现在只有金库真正要签名时才计数；被拒不计。要求的数额超过当日额度时，金库改为按额度支付并说明，而不是拒绝。拒绝信息会写明距离新的一天还有多久，并且有中文。',
      '第二家面包房开工了。以前同一行当的每个人都走去该类型的第一栋建筑，所以第二家面包房或木匠铺里永远没人：卡片写着「安静」，人手是零，玩家来信说它坏了，而整个行当其实在产出。现在每个工人都有自己报到的工作场所，按空岗位分配；工作场所的卡片会写明填了几个岗位。行当因缺原料不能全员开工时，卡片会说明缺什么、几个人开了工。',
      '看得见的对话。两个人开始交谈时会停下来面对面，气泡跟着这段对话走，跳到正在说话的那个人头上，所以一段对话读起来是完整的：以前人们边擦肩而过边说话，两步之后对话就被打断、只说了一句，而回答落在了一个没有气泡的人身上。现在每段对话都会说完，每一句都画出来。',
      '拍照模式。时钟旁的 ◉ 按钮或 P 键隐藏整个界面，截一张干净的图；P、Esc 或角落的小按钮把界面叫回来。',
      '每个时代有自己的建法。聚落是木屋：圆木在转角处交错咬合，低矮的屋顶铺木瓦或茅草，门前有柱子撑起的门廊，毛石烟囱，柴火靠墙码着，公共建筑是木板搭的大屋。城镇是第一个为长久而建的地方：两层的木架房，梁间抹灰、上盖烧制的瓦，屋顶有老虎窗、墙脚有石砌基座；公共建筑是切石砌成、覆着石板瓦。建筑在升级之前保留它建成时那个时代的样子。',
      '人说起话来像人了。每个居民现在都有性情——热心、直率、爱做梦、爱操心、爱开玩笑、骄傲、寡言、好奇、爱抱怨或稳重——它决定他们怎样回话。每段对话都是为这两个人编的：开场知道彼此是什么关系（配偶、亲人、朋友、见过的人、陌生人、冤家），一个其中一方真有理由提起的话题，听者用自己的口气作答，告别时说自己要去哪儿。人们记得自己经历的事——饿着肚子睡、没领到工钱、露宿、看见的打架、新朋友、成家、孩子、初来乍到、出师、坐牢、生病、节庆、闹翻、丧事——会互相问起，也记得上次和每个人聊了什么，下次接着聊。卡片上显示他们的性情、近况，以及最近和谁聊了什么。',
      '聚落被画进了阳光里。全新的色彩脚本以黄金时刻为基调：暖米色灰泥露出木架和斜撑，切石按层砌筑，圆木上沿受光，陶瓦和石板成扇形排列，茅草成束、屋檐参差。太阳在一切的右上方——受光面、背光面、屋檐下和墙脚的一道阴影、投向左下的影子——窗户白天也透出暖光。门是带台阶的石拱门。针叶树是有受光面的层叠人字，阔叶树冠由许多小簇组成，右上受光。草地有斑驳和草丛，广场铺着不规则石板，水面青绿、浅滩更柔，黄昏是琥珀色。每个屋顶周围的杂点没有了，抬高地面透出背景的黑色菱形也没有了。',
      '时代是整座城的升级。地块每推进一个时代，每个工作场所多容纳一人，每座房子多睡一人，每双手多产出 12%，升级上限提高一级，建造面板默认打开本时代的建筑，早期时代在旁边的标签里，后面的时代也能先看。玩家说推进时代像只是解锁几栋建筑；现在它是整座城在成长。',
      '等级上限跟随时代。聚落可把建筑升到 3 级；每进一个时代多开一级，AI 时代最高 7 级。地块进入新时代时建筑保留已达到的等级，升级早期时代建的建筑会换成地块当前时代的样式。第三级之后每步更贵。',
      '银行显示金库会付多少。「收取」下方的「金库今日裁定」就是提取时实际衡量的数字，是你所有产出地块加在一起的，并列出每块地的支付等级、经营和关注度。一块地按城市等级或每在场三天一级中较低者支付，卡片会写明你已在场多少天——你屏幕上的「每日收益」按完整城市等级计算，所以可能比到账的多。「今日可收取」按同一数字衡量，收取栏默认填入它，拒绝时会弹出屏幕通知，而不再只是面板底部的一行字。',
      '提取以链上确认为准。金库现在会等转账收据再告诉你已发出；被链拒绝的转账直接拒绝，余额分文不动。超过等待时间的转账在「已支付」下显示为「发送中」并附浏览器链接，你下次打开银行时再核对；若查明被拒绝，金额会退回游戏内余额，并弹出通知说明。',
      '桥会落在人能走下去的地方。渡口的两岸取的是沿线第一块干地，在沙嘴、小湾或斜岸上，坡道末端仍在水边的步行边距之内：桥面把人送到尽头，岸边却拒绝这一步，于是一队人整晚站在桥上，旁边碰巧是一丛灌木。手动架的桥有三分之一是这样收尾的。现在选渡口时要求两岸都有出路，坡道会一直延伸到开阔地面，已建好的桥在地块载入时也会同样加长。灌木只是布景，从来不挡人。',
      '桥也能拆了。地块上一旦有桥，建造面板的桥梁卡片上就多出「拆除一座桥」：点一下桥面它就拆掉，部分木板回到堆场，跨水的路被切断，桥上的人在较近的一岸下桥。通往有建筑的岛的唯一渡口会被拒绝拆除，直到那些建筑拆掉或另有渡口，所以不会有人被困住。',
      '哪里都能架桥。点击你想架桥的水面，或对岸的陆地，工队会在那里勘定最窄的渡口，包括镇中央那片大家本来能绕过去的湖。扩展后的地块，勘定范围也覆盖外圈。',
      '桥头留空。桥面和引道上不能再放建筑；已经站在上面的，助手会指出是哪一座并请你搬开：要去对岸的人走到那里就停住了。',
      '新来的人一到就安排住处，和其他人一样按合住规则分配，而不是在有空床的房子旁露宿到第二天早上。',
      '又有孩子了。独自来的人现在也能成家，一对新人只需要一张床而不是整栋空房，所以由新人组成的大城又有家庭和新生儿了，而不只靠路上来人。',
      '可以送人走了。成年人的卡片上有「送走」：给几天工钱，他们就上路，床位和岗位当天空出。还有城门：在人口面板关上城门，就不再接纳新人。新人现在只在有空缺岗位时才来，大地块不会再挤满无事可做的人。',
      '库存保留。市场面板上每种货物都能设一个保留量：市场绝不会卖到低于它，为下个时代攒的铁矿石就留在仓里。它不会为此买进。',
      '面包。需要原料的行业现在按库存能覆盖多少就干多少，而不是要么全干要么不干：三家面包房二十个面包师以前要凑齐两百面粉和五十木材才肯烤一个面包，差一点就一个也不烤，麦子和面粉却堆着。动态会写明缺什么、多少人开了工。',
      '助手不再要你建第七座农场。已有农场时，它会说田里是缺人还是缺等级，以及还有什么能养活一座城。',
      '建造光标说实话了。它问的是和放置同一条规则，绿色就是能放；被拒时会在屏幕上说明原因，而不只是写在动态里。',
    ],
  },
  {
    version: '2.5',
    date: '2026-09-10',
    title: '猎人小屋，和你没在看的地块',
    notes: [
      '狩猎现在和其他行业一样计产。屏幕上能看到的追猎只是一天的可见部分；陷阱、绳套和地块边缘之外的猎场带回其余部分，所以满员的猎人小屋不再十个猎人分一群猎物、报出"每天 0"。升级的小屋和满满的箭筒会如期提高收获。',
      '动物现在会分布在整块扩展后的土地上，猎人小屋的卡片会写明地上有多少猎物、多少在可及范围内。',
      '注意力属于你，而不是地块。在任何一块地上做点什么，你名下的每块地都算被照看，本设备、其他设备和金库的裁定都一样。你留着运转的地块按你离开时的样子继续按时钟计收，开着与否都一样。',
      '市政厅可以建了。它在城镇时代的条件里、在每张清单上，唯独不在建造面板里；现在在"公共"一栏，480 金币、20 木材、30 石料。',
      '手机上可以搬建筑了。点一下就放在手指的位置；以前的虚影只跟着鼠标走。',
      '有人住的房子可以拆了。这家人会搬到有空位的房子，没有的话就露宿到新房建起，卡片上会说明。市场、银行和市政厅则会说明为什么不能拆，而不是把按钮藏起来。',
      '第一天。新聚落打开时会有一张卡片，说明游戏为什么付你钱，并给出五件事——一个人、一座房子、银行、一次升级、明天再来——做了就自动打勾。随时可以跳过。',
      '世界地图上的排行榜。每座城市按金库裁定的等级排名，再按经营好坏排，旁边是它的旗帜、时代和 GLD。点一行就去看看。',
      '手机上过了一遍：每个面板都用手指点过。语言切换不再压在世界里的人口标签上，手指要点的东西都够大了。',
      '再开九张海图。世界从十二张海图、204 块地扩到二十一张海图、357 块地，七十二座新岛各有自己的名字，地图上的计数覆盖全部海图。',
      'GLD 兑换改走 Uniswap 的 Universal Router，按路径交易：一笔交易里先把 $EMERGE 卖进它自己的池子，再用所得买入 GLD，经 Permit2 支付并以报价器设下限——因为 Robinhood Chain 上就是这个路由器，而 GLD 的池子对的是 USDG。',
    ],
  },
  {
    version: '2.4',
    date: '2026-09-09',
    title: 'GLD 分红',
    notes: [
      '每笔收费现在三分：60% 由金库销毁，25% 留作提现，15% 进入分红池。提现扣留部分同样分配。',
      '每周一金库把分红池的 30% 送往开发，其余在 Robinhood Chain 上兑换成 GLD，并记到持有者名下：55% 归土地，按每块地被裁定的等级和主人当周在场天数加权；15% 归软质押。',
      '软质押是登记，不是锁仓。在银行的"分红"卡片登记一次，你整周的最低 $EMERGE 余额即计入，100,000 起，上限 5,000,000。周中卖出即放弃本周；其他一切不变。',
      'GLD 记在你的钱包名下，直到你领取，由金库发送。分红池、你的土地权重、你的质押和你的 GLD 都在卡片上，结算记录在公开账本上。',
    ],
  },
  {
    version: '2.3',
    date: '2026-09-08',
    title: '飞轮经过裁定：每次升级都有意义，每笔收费都进金库，金库只付它看得见的',
    notes: [
      '每次升级都有效果，建筑卡片会写明。工作场所仍是每级多 22% 产出；房子多两张床；学校、图书馆、实验室、诊所、医院、咖啡馆、酒馆、教堂等每级效果增强四分之一；市场每级出口多卖 5%；银行每级让所有建筑维护费便宜 5%；市政厅每级提高经营质量 2%；升级后的仓库在防备中算一个半；马厩、车站、公交站和出行舱站每级让人快 10%；升级后的监狱几率再减半并更早制止暴徒。',
      '经营收益现在由服务器裁定。地块按较小者计等级：发布的世界显示的等级，或主人实际在场每三天一级——在场由心跳记录，客户端无法伪造。评分用聚落同一个函数从发布的世界算出，关注度取自主人最近一次心跳。支付接口按客户端申报与服务器裁定中较小者支付。雇工按地块裁定上限的十分之一支付。',
      '为一块地每天可赚 250,000 的游戏重新定价：地块价格约为原来的三倍；新地块上限从 40,000 起；特许状为地块自身上限的四天（新地块 160,000，顶级城市 1,000,000），各等级同样划算；时代每已走一步一百万，即 1M、2M、3M、4M；扩建 1,000,000；改名、勘测和勘探翻倍；提现扣留 10%，一半销毁一半留存；雇工须持有 50,000，雇主开放职位付 10,000；转售收取 5% 登记费进入金库。',
      '竞技场可用 $EMERGE 下注，与金币并列。赌注进入金库，赢家由金库按显示赔率支付，输了留在金库。每场 50,000，每天 250,000。庄家优势按收费方式记账。',
      '声望。广场上的纪念碑，250,000，每块地一座，每天让所有人略微开心，城在碑在。旗帜，100,000，自选徽记，飘在你的名字上和每张世界地图上。',
      '收益无论游戏是否打开都按时钟支付。一位玩家看到"每天 16,000"却只收到 8,800，是因为标签页关了十一个小时：累积过去只在页面绘制帧时进行。现在自上次累积以来的时段按当时的关注度支付，一次最多一个月；超过当日上限的部分留到明天而不是丢失。支付接口在你最后一次访问后给一天宽限，之后关注度才开始下滑。',
    ],
  },
  {
    version: '2.2',
    date: '2026-09-07',
    title: '飞轮、每样一座，再也没有毁掉二十七栋楼的暴徒',
    notes: [
      '每笔收费的分配改为四分之三销毁、四分之一留在金库用于支付提现。银行新增"飞轮"卡片，显示金库账本：玩家付入、金库已销毁、留作提现、待销毁。',
      '建筑大师：120,000 $EMERGE 让一队工匠在广场驻扎三十天，你建造的每栋建筑和支付的每次升级都少花四分之一金币。再买会累加天数。在"链上"面板，与特许状和保险并列。',
      '每样一座。市政厅、监狱、酒馆、学校、港口：所有"有一座就起作用"的建筑现在每块地只能有一座。建造面板把已有的标为"已建"，光标拒绝第二座，聚落自建也不会再盖。房屋、仓库和所有有岗位的工作场所仍然多多益善。',
      '房子按等级住 3、5、7 人。每次升级房子多两张床，房子的卡片会显示住了几人、共几张床，以及升级后有几张。这就是升级房子的意义。',
      '现在算的是监狱的等级而不是数量：三级监狱把有人作乱的几率降到八分之一，暴徒在第一栋楼前就被制止。没有监狱时一个暴徒最多毁三栋；有监狱时按等级为三、二、一栋；天亮时仍在逃的暴徒会被全聚落围住。夜里的暴徒现在会惊醒附近的人，而不是独占整座镇子。这关闭了"二十七栋楼"的反馈。',
    ],
  },
  {
    version: '2.1',
    date: '2026-09-07',
    title: '十倍的收益，以及为它买单的收费',
    notes: [
      '收益是原来的十倍。地块的每日上限从一级的 60,000 $EMERGE 到人工智能时代十级城市的 250,000。五块地可以赚而不是四块，一个钱包每天最多可收取 1,000,000。单笔提现最多 1,000,000。',
      '每一笔收费现在进入金库，而不是直接到销毁地址。金库用自己的密钥销毁其中一半，多笔收费合并为一笔交易；另一半留在金库用于支付提现。你仍然只签一次名；玩家花掉的就是支付玩家的来源，金库付得起它欠的。账本公开在 /api/vault：收入、留存、待销毁、已销毁，以及销毁交易。',
      '"链上"面板新增"补给"卡片，三样东西付款到账即送达：一队五名移民（50,000，房子要有空位）、一批 400 木材、300 石料和 240 份食物的货物（40,000）、一次重建全部废墟并完成在建桥梁的修复（100,000）。',
      '特许状和保险按新上限重新定价：300,000 和 150,000。',
    ],
  },
  {
    version: '2.0',
    date: '2026-09-06',
    title: '城市等级、有去处的金币，以及值得持有的 $EMERGE',
    notes: [
      '城市等级。每块地都有一个等级，一到十级，由人口和完好建筑数决定。规模让你有资格升级，金币支付确认升级的公共工程：二级 1,500 金币，十级 130,000 金币。银行里的"城市"卡片显示等级、下一级的要求和按钮。已有的城市按现状评级，已经长到的等级不用付钱。',
      '收益随等级走。地块的每日上限从一级的 6,000 $EMERGE 到十级的 25,000，再乘以时代：人工智能时代的十级城市每天最多可赚 40,000。新认领的地块只能赚到成熟城市的零头，所以把手里的地块发展好比再认领一块更值。支付接口从你发布的世界读取等级，改存档得不到更高的上限。',
      '金币有了去处。公共工程、节庆（按人头收费，让全城更快乐，每天一次）、你自己下令修的桥，以及按建筑所建时代每个时代增加四分之一的维护费。金库是用来建设城市的，不是用来数的。',
      '特许状：销毁 100,000 $EMERGE，地块收益上限提高五分之一，为期三十天。保险：销毁 50,000 $EMERGE，火灾、地震、洪水或暴徒造成的损失减半，为期三十天。两者都在"链上"面板购买，记录在地块记录上，有效期内再买会累加天数。',
      '没有灾难能夷平一座城。地震或龙卷风最多损坏现存建筑的四分之一（最少三栋）。有玩家回来时四十栋建筑只剩两栋——那不是挫折，而是放弃的理由；现在不会再发生。',
      '监狱有用了。每座监狱把有人作乱的几率减半，最低到十分之一；有监狱时，扭打中的作乱者十次只有一次挣脱，而不是三次一次。一百五十人的镇子里两座监狱现在有明显的区别。',
      '房子住得下一家人。一栋房子按容量住人，一级三人，每次升级更多，所以独自到来的新人会与人合住，而不是一个人占一整栋。"一栋房子只住一个人"的问题没有了。',
      '手动架桥。建造面板新增"桥梁"工具：点击水对岸的陆地，工队就会勘定通往那里最窄的可靠渡口，开工 600 金币，木材和工钱按天计。料场木材不够时，工队会用金币买进而不是停工——这正是一些镇子不再架桥的原因。',
      '时代门槛也要求城市等级：城镇三级、工业五级、现代七级、人工智能九级。',
    ],
  },
  {
    version: '1.6',
    date: '2026-09-05',
    title: '居民、培训，以及随城市成长的收益',
    notes: [
      '操作栏新增"居民"面板。每位成年人的行当、技能和工作地点，无业者排在最前，可按行当筛选。每个行当的在岗人数对比岗位数，以及有多少空缺。每个工作场所的在岗人员与岗位，废墟有标记。不用再猜某栋建筑是什么、缺哪些工作。',
      '定向培训。把一个人培训成任何有工作场所的行当，或一次填满某个行当的全部空缺，由最能腾出的人担任：先是无业者，再是人手多于岗位的行当，再是技能最低的人。每人 60 金币。受训者四十天内不会被聚落自行调岗，并带着技能起点，有学校则翻倍。',
      '收益随时代增长。地块每推进一个时代，每日管理收益上限提高基础值的 15%：城镇比聚落最多多 15%，人工智能时代的城市最多多 60%。支付接口从地块记录读取时代，而该记录只有经过门槛与销毁验证的推进才能提高。',
    ],
  },
  {
    version: '1.5',
    date: '2026-09-04',
    title: '所有时代，直到人工智能时代',
    notes: [
      '剩下的三个时代已经建成并开放：工业、现代和人工智能。地块一次推进一步，每步销毁 1,000,000 $EMERGE，须先达成条件。清单在"时代"卡片上。',
      '工业：砖与铁、带铁轨的石板路、烟囱。火车站让每个上班的成年人乘铁路，比马车快；渡船变成蒸汽船。工厂、铸造厂、电报局和煤气厂。烟雾笼罩镇子、消耗幸福，直到建起煤气厂。',
      '现代：混凝土与玻璃、带标线的柏油路、夹克和牛仔裤。公交车站让人们开上汽车，三分之一骑自行车；渡船变成摩托艇。医院、体育场、超市、写字楼和发电厂。医院拿掉糟糕一周的大部分风险。',
      '人工智能：白色复合材料、灯带、屋顶花园、安静的浅色道路。出行舱站让每个人坐上自动驾驶舱，最快；渡船变成水翼船。数据中心、研究园区、垂直农场和无人机港。',
      '已有的每栋建筑在你升级它时按新时代的样式重绘，在那之前保留旧貌。人们随时代换装换帽：软帽和三角帽、圆顶礼帽和护目镜、棒球帽和毛线帽、面罩。',
      '街道相连。道路会读取相邻格：与下一格或广场相接处路面不间断，其余每条边都有该时代的路缘和人行道。泥路上的车辙、石板路上的铁轨、柏油路中间的虚线、复合路面上的光缝。',
      '每个时代按自己的形状重建建筑，而不是换个颜色。城镇建起孟莎顶石屋、陡峭的山墙和高大的四坡顶大厅；工业时代是带烟囱的长排砖屋、作坊上的锯齿玻璃顶和平顶砖楼；现代是退台式混凝土住宅、宽大的厂棚和高楼；人工智能时代是带花园平台的圆角白色舱体和光之穹顶。',
      '人们真的在骑乘。每种交通工具都按人物比例绘制、分两层，骑手坐在汽车或出行舱里、跨在自行车上、坐在马车的车座上或有轨车厢里，也坐在船里。船只只出现在水面上。',
    ],
  },
  {
    version: '1.4',
    date: '2026-09-04',
    title: '时代：城镇',
    notes: [
      '地块可以从聚落时代推进到城镇时代。必须先达成条件：在本时代满六十天、四十人、三十栋建筑、有镇公所、银行、学校和监狱、金库 20,000 金币、没有废墟。然后花 1,000,000 $EMERGE，销毁，每一步一次。"链上"面板的"时代"卡片会逐项显示清单。',
      '城镇看起来就是城镇：推进之后新建或升级的建筑都是石墙瓦顶，泥路变成石板街，人们穿上羊毛外套、戴上帽子。之前建的保留木结构，直到你升级它。',
      '六种新建筑：礼拜堂、行会大厅、酿酒坊、印刷所、马厩和港口。马厩让每个上班的成年人坐上马车，比步行快。港口开通渡船：人们乘船过水，每座岛无需桥梁即可到达。',
      '建造面板按货架分类：住房、食物、材料、市政、照护与学习、休闲、交通和公用。后一个时代的建筑灰显并标出所属时代。聚落自建只会建当前时代允许的东西。',
      '另外三个时代已经命名并设好门槛，但尚未建成：工业、现代和人工智能。每个的清单已经在卡片上，地块可以提前朝它努力。',
    ],
  },
  {
    version: '1.3',
    date: '2026-09-03',
    title: '你的聚落再也不会丢失',
    notes: [
      '已发布的世界保存一年以上而不是一天半，服务器拒绝任何会让你的世界倒退的副本。每台设备在开始前都会读取进度最靠前的副本，回到标签页时再读一次。',
      '雇工：没有土地但持有 1,000 $EMERGE 的玩家可以在招工的地块接下工作，由金库支付其管理收益的十分之一，每天最多 2,500。上工算作地主的关注。',
      '先看看再说：首页不用钱包也能打开世界地图。观众可以拜访任何聚落、在聊天里说话，带着观众标记。',
      '扩建地块：土地本身变大，四周多出一圈新地，约多一半土地，花费 500,000 $EMERGE，每块地一次。',
      '世界地图上有了"主页"和"断开钱包"按钮。指南加了图片，还有这份更新记录。',
      '配乐：白天的聚落、黄昏、夜晚、危险、世界地图和拜访，六段循环。按音符键即可听到。',
    ],
  },
  {
    version: '1.2',
    date: '2026-08-30',
    title: '两百块地、地块市场与荒野',
    notes: [
      '十二张海图，约两百个聚落的空间。地块在玩家之间钱包对钱包出售，任何人都可以对任何地块出价。',
      '捕鱼、狩猎与采集。渔夫在岸边下竿并购买鱼饵；猎人追踪鹿、野猪和各生物群系的动物；采集者带回浆果和草药。这些都能在市场卖出。',
      '地震、龙卷风、洪水和瘟疫，可以花金币对抗；废墟可以重建；有人会变成暴徒，必须由聚落自己关进监狱或制止。',
      '金库充裕时聚落会自己建造所需。树可以清除，被建筑覆盖的空地上会重新长树。沙漠的树也能砍。',
      '游戏和指南全部有了中文。更好的寻路、每座桥一整块桥面，以及随着地块改善不断到来的移民。',
    ],
  },
  {
    version: '1.1',
    date: '2026-08-20',
    title: '指南、市场与竞技场',
    notes: [
      '一份解释每个系统的公开指南，包括今天哪些部分在链上结算、哪些不是。',
      '所有世界共用一个市场，工资由你设定，居民卖出东西时会有提示卡。',
      '自己岛上的竞技场，可以用金币押注决斗。学校、实验室、咖啡馆、画室、诊所和图书馆。建筑可以搬动和改良。',
      '向目标风格靠拢的画面全面升级、重绘的居民，以及一位告诉你下一步该建什么、为什么的地块助手。',
      '显示在线玩家数，聚落跟着你的钱包跨设备走。',
    ],
  },
];
